### ISSUE TITLE
The page.html layout is only valid for the documentation

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#106]
The `frequently-asked-questions.html` page uses it as well, but the top-menu is not highlighted and the menu doesn't fit.

I didn't want to just copy/paste the `page.html` file; we should introduce a dynamic/nested layout to handle them all. Do you know how to do that @rayrutjes ?

**Comment by rayrutjes** [comment]
You are right, we should make the Layout cleaner and use partials.
Regarding FAQ, I found it nice to add it to the top menu bar, but I also wanted to leave it in the left menu. Not sure what the best would be. This section might increase pretty quickly.

WDYT?

I can investigate the partial thing, just waiting for your go, so we don't come with 2 different implems at the same time 😂

**Comment by redox** [comment]
> Regarding FAQ, I found it nice to add it to the top menu bar, but I also wanted to leave it in the left menu. Not sure what the best would be. This section might increase pretty quickly.

Ah yes OK, got it 👍
