### ISSUE TITLE
Choosing the Autocompletion mode is misleading

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#11]
When using the auto-completion mode, if a user press "Enter" instead of selecting a product/category he will be redirected to the default search results page of Wordpress. This one is rendered without Algolia, using the default search of Wordpress. That's misleading because the results are probably not the same than the one you saw while using the auto-completion menu.

Solution 1:
 - replace the "PHP/backend" search of Wordpress by Algolia.

Solution 2 (probably better):
 - not anymore either "auto-completion" OR "instant-search"
 - but rather "auto-completion" AND "instant-search" -> auto-completion menu would be displayed on all pages that are not the search results page; instant search on the results page.

**Comment by redox** [comment]
(TL;DR: solution 2 has been implemented)

**Comment by deepankarpathak** [comment]
Redox : How can we use the same on Wordpress? Any update in that plugin?

**Comment by redox** [comment]
Hey @deepankarpathak, we'll release a new version later today so you can use both auto-completion menu & instant search results page.
