### ISSUE TITLE
Custom Post Types not being loaded by the plugin

### ISSUE THREAD

**Issue by jnijstad** [algolia/algoliasearch-wordpress#122]
Custom registered post types aren't being indexed as "Searchable Posts" by the plugin.
My custom post types are registered on the WP action 'init' as described in the [WP docs](https://codex.wordpress.org/Function_Reference/register_post_type) as so:

add_action( 'init', 'regsiter_my_custom_post_types');

The plugin is however not recognising the custom post types.
Instead only the default post types are being indexed as "searchable post" by Algolia.

When we take a look in the file "class-algolia-plugin.php", there's a line on 221:
```
// Add a searchable posts index.
$searchable_post_types = get_post_types( array( 'exclude_from_search' => false ), 'names' );
```
I suspect this gets triggered too early and should instead run only after the theme has been initialised. After the action 'init', like 'wp_loaded'.

I can reproduce this by simply taking `$searchable_post_types = get_post_types( array( 'exclude_from_search' => false ), 'names' );` and place it in my functions.php with the result:

```
$searchable_post_types = get_post_types( array( 'exclude_from_search' => false ), 'names' );

print_r($searchable_post_types); //shows only post, page and attachment
```

However when we wrap this code in the init action it'll get the desired result:

```
function test(){
  $searchable_post_types = get_post_types( array( 'exclude_from_search' => false ), 'names' );
  print_r($searchable_post_types); //correct result: includes custom post types
}

add_action('init', 'test');

```

### Technical info
* WP version: 4.5.3
* Algolia Search plugin version: 0.2.5

**Comment by rayrutjes** [comment]
Hi @jnijstad thank you so much for this very detailed issue.
Let me reproduce this and come back to you.
