### ISSUE TITLE
We need to validate the ADMIN api key

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#126]
Right now, it doesn't validate at save time and the queue get processed (down to 0). Once you enable the logging, you see errors but it's not clear.

Do you give up processing some tasks when we have an error? I think we shouldn't and keep the task in the queue until we succeed.

**Comment by rayrutjes** [comment]
Regarding the queue processing, it will stop once #129 is fixed.
Regarding the other issue, indeed the way we validate data is perfectible. I'll leave this open for the form validation part.
