### ISSUE TITLE
Connection issue from VM?

### ISSUE THREAD

**Issue by KieranYo** [algolia/algoliasearch-wordpress#131]
### What did you expect to happen?
Expected to index out records

### What happened instead?
Log details displays the following: `Hosts unreachable: Failed to connect to 3PGGZN3AI0.algolia.net port 443: Connection timed out,Resolving timed out after 2000 milliseconds,Resolving timed out after 4000 milliseconds,Resolving timed out after 4000 milliseconds`

When updating our Algolia account API keys we also receive the following message: `We were unable to authenticate you against the Algolia servers with the provided information. Please ensure that you used an the Admin API key and a valid Application ID.`

Are there known issues connecting to Algolia when the plugin is used inside a VM? (In our case VVV vagrant)

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version:  0.2.5

**Comment by maxiloc** [comment]
Yes we had the issue a couple time.
It's usually due to the vm missing certificates.
You need to make sure you are able to resolve APP_ID-dsn.algolia.net from your vm (APP_ID being your actual APP ID.
We usually use `curl -vvv https://APP_ID-dsn.algolia.net/diag` to debug those kind of issue

**Comment by rayrutjes** [comment]
@KieranYo if you manage to solve your issue, please give us some feedback so that we can add it to the documentation!

**Comment by KieranYo** [comment]
I'm not entirely sure if this solved the issue for my but I ssh'd into the vagrant box using `vagrant ssh` then ran the above mentioned command `curl -vvv https://APP_ID-dsn.algolia.net/diag` then it started working fine.
