### ISSUE TITLE
Stops syncing existing posts and does not create new indices

### ISSUE THREAD

**Issue by amitramani** [algolia/algoliasearch-wordpress#146]
### What did you expect to happen?
For all post types (products, posts, pages, product-categories, product-tags, brands) to be indexed in the Algolia app. 
### What happened instead?
Only the "product" and "posts" indices were created. The rest of them were not created, regardless of the fact that they are selected under "Indexing" menu of Algolia plugin (See attached plugin).
### How can we reproduce this behavior?
I can provide you my login for my WordPress site as well as to my Algolia dashboard, so you can check it yourself. 
Can you provide a link to a page which shows this issue?
https://www.tacknrider.com
### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version:Version 0.2.4
![algolia-engines-showing-only-3-engines](https://cloud.githubusercontent.com/assets/766461/17340791/bec55292-58bf-11e6-927c-ff2c62fbf112.png)
![algolia-wp-admin-showing-tasks-are-queued](https://cloud.githubusercontent.com/assets/766461/17340796/c2689422-58bf-11e6-9804-ba9af9992a39.png)

**Comment by rayrutjes** [comment]
Hi @amitramani,

In general, if the queue stops without logging anything on the plugin's `Logs` page, it often means that we are dealing with a PHP error.

To be able to see those errors in your php logs, you have to make sure WP_DEBUG is set to `true` in your wp-config.php file.

I am also a bit worried by all the errors I see by accessing your website:
![image](https://cloud.githubusercontent.com/assets/5570853/17343969/a5c7b44c-5900-11e6-928a-839ac6e43404.png)


To finish, I will try to make a new release by the end of the day that improves the UX of the autocomplete dropdown. I'll ping you so you can deploy the new version. It is entirely backward compatible with 0.2.4.

**Comment by rayrutjes** [comment]
@amitramani, I suggest you get the latest version, 0.2.8 : https://community.algolia.com/wordpress/

I think this will greatly improve the display of your autocomplete dropdown menu.

Keep me posted about the other issue!

**Comment by amitramani** [comment]
Thanks for the quick response. I was able to access the debug.log. Though there are PHP errors (related to Paypal plugin and others), I did not see anything related to 'algolia'.

Log is attached. 
[debug.txt](https://github.com/algolia/algoliasearch-wordpress/files/398208/debug.txt)

**Comment by amitramani** [comment]
I am about to install the latest version, 0.2.8. Do I need to delete my existing indices and then re-create them from the new version of the plugin?

**Comment by rayrutjes** [comment]
Hey again,

No you do not need to do anything special to update the plugin. Just replace the files and you should be good.

Regarding the php logs, there are a lot of errors.
Could your try disabling https://fr.wordpress.org/plugins/nextgen-gallery/ for testing purposes?
It looks like it doesn't like that we apply 'the_content' filter on it.

Not sure this is the issue but definitely worth a quick try 😄

**Comment by amitramani** [comment]
I disabled Nextgen Gallery. Still no luck. Initially, the task queues were processed. The existing indices (post, pages and products) were synced. But the new indices (brands, product-categories, product-tags) are not being created.

Any other ideas?

**Comment by amitramani** [comment]
It seems like the tasks are queued, but never get executed? I am confused why this is happening. 
Here is what my Logs screen shows. As you can see, the task is never run. 

20521	info	2016/08/02 at 06:22:53	About to run 1 task.	
20520	info	2016/08/02 at 06:22:52	New task re_index_items was queued.	Show log details
Array
(
    [index_id] => terms_product_tag
)
20518	info	2016/08/02 at 06:22:52	New task re_index_items was queued.	Show log details
Array
(
    [index_id] => terms_product_cat
)

**Comment by rayrutjes** [comment]
Could you:
1. Disable the Algolia Search plugin (clears the queue & logs)
2. Enable the Algolia Search plugin
3. Clear the php logs
4. Uncheck one of the indices and hit save
5. Re-check that same index and hit save

This will isolate the errors to one index processing.
If this does work without errors, retry it with another index from step 4

**Comment by amitramani** [comment]
I followed your instructions first by removing "Products". It was successful. I saw it was de-indexed from my Algolia dashboard. Then I re-enabled "Products". Again, it showed up correctly.

Then, I repeated the same steps with "Pages". It is now stuck in the bad state. i.e. 	About to run 1 task.

I will rety from scratch by disabling the plugin and re-enabling it back. Then I will try indexing one post-type at a time, so I can tell which one breaks it,.

Let me know if you have any other ideas and suggestions.

**Comment by amitramani** [comment]
So I repeated the procedure, picking one post type at a time. I found out that the problem happens when I select "Posts (posts_post)" to index. After that the queue is not processed. The tasks remain in the queue. Even after clicking on the Process button, they are not processed.

Here is what I observe when this problem happens. As shown below, the "Current task: re_index_items (page 5 of 5)" right away instead of processing it page by page. i.e. page 1 of 5, page 2 of 5, .... 

This is what I see under Indexing when this problem has occurred:

Task Queue pending tasks : 3

Task Queue status: Running

Current task: re_index_items ( page 5 of 5 )

**Comment by rayrutjes** [comment]
It looks like in your case you have a problem with the `posts_post` index.
At some point though you should have errors in the php logs or the plugins logs.

I guess best would be to start resolving these issues one by one.

Also, have you used some custom to extend the plugin?

**Comment by amitramani** [comment]
I have experimented with this thoroughly. What I have found so far is that whenever the Page post type is indexed, it causes the failure. I also noticed that even though the content of "Pages" is updated to the relevant Algolia engine, it does not get renamed from "wp_posts_page_tmp" to "wp_posts_page". 

I am not sure if this is helpful for you in debugging this further. At this point, I believe I have exhausted all the other options. Let me know what you find or if you need me to do other tests.

**Comment by rayrutjes** [comment]
If the wp_posts_page_tmp does not get renamed it means it is the posts_page index having a hard time indexing your pages.

Could you maybe try to replace: https://github.com/algolia/algoliasearch-wordpress/blob/master/wordpress/wp-content/plugins/algolia/includes/indices/class-algolia-posts-index.php#L101

With 

```php
$post_content = $post->post_content;
```

If this doesn't do the trick, I'll have to accept the initial DM offer to access your website.

**Comment by amitramani** [comment]
I just tried the change you suggested. Without de-activating and re-activating the plugin, when I selected "Pages" to be indexed, it finally worked!!

Should I de-activate and re-activate and try them all now?

**Comment by rayrutjes** [comment]
@amitramani you can definitely try to re-index everything now. That being said, at some point you will want to re-store the `the_content` filter.

That filter ensures all shortcodes of the post content are parsed.

In your case, I think one of the plugin you are using does not behave as expected when applying `the_content` filter. I that is indeed the case, then this is more an issue of the other plugin than ours. 
I'd be curious to know what page makes this all crash. Do you have shortcodes on your pages?

**Comment by amitramani** [comment]
Hi Ray
You were absolutely right in that it has something to do with the Pages type. I have another site that is very similar in plugins. On that site, the Algolia plugin works beautifully without any code changes. 

At this point, I am going through all my Pages one by one to find out which one is the culprit. Thanks so much for your help. I appreciate your assistance and promptness!

Now, moving on to Instant Search, I would really like to get that working. I can not figure out which index to use (from the guide/documentation). Is "searchable_posts" used for Instant Search?

**Comment by someguy9** [comment]
"$post_content = $post->post_content;" worked for me in, was having issues in class-algolia-searchable-posts-index.php
