### ISSUE TITLE
Handle slave indices

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-wordpress#148]
Right now, if you set "slaves" inside the settings of an index, you can't (at least if I got it right) update the settings of those newly-created slaves.

**Comment by KieranYo** [comment]
By way of example I have this filter

`add_filter( 'algolia_posts_index_settings', array( $this, 'my_posts_index_settings' ), 10, 2 );`

```
		function my_posts_index_settings( array $settings, $post_type ) {
			if ( 'deal' === $post_type ) {
				$settings = array(
					'attributesToIndex' => array(
						'unordered(post_title)',
						'unordered(subtitle)',
					),
					'customRanking' => array(
						'asc(post_title)',
					),
					'attributeForDistinct'  => 'post_id',
					'distinct'              => true,
					'attributesForFaceting' => array(
						'price',
						'trip_duration',
						'holiday_type',
						'is_exclusive',
					),
					'slaves' => array(
						'wp_posts_deal_price_asc',
						'wp_posts_deal_price_desc',
					),
					'attributesToSnippet' => array(
						'post_title:30',
						// 'content:20',
					),
					'snippetEllipsisText' => '…',
				);
			}
```

But as per the documentation [here](https://www.algolia.com/doc/guides/search/instant-search#configuration-script) there is no way to do update the ranking of those `slaves` indexes.

**Comment by Jerskouille** [comment]
Actually, handling slaves will probably be more complex than that. For instance, you can't do the move tmp -> normal on the master one if it has slave indices.

**Comment by KieranYo** [comment]
So the move tmp -> normal should be done before the slave indices are created?

**Comment by Jerskouille** [comment]
Exactly

**Comment by rayrutjes** [comment]
Thank you for the example @KieranYo,

We will are currently trying to implement the slaves feature in way that will be simple to use.

Can you both confirm that you want to use slaves for ordering?

We were thinking of creating an easy way to only pass an attribute that is part of a record as argument and automate the salve's handling.

How does that sound?

**Comment by KieranYo** [comment]
Hi @rayrutjes thanks for getting back to me.

To be honest I'm not stuck on how the ordering is done, as long as it's possible. If that means using slaves then so be it. I will leave it to your best judgement though of course.

**Comment by virtuman** [comment]
I second what @KieranYo said
