### ISSUE TITLE
Result counts in facet modules

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#149]
Result counts in the faceting modules reflect the total # of (occasionally broken up) records stored on Algolia, rather than the actual number of corresponding records stored in the WP database. See the difference between the counts shown below, in which "Strategies" is the selected facet. In this case, there are 2,007 records that were stored on the Algolia server, corresponding with 1,672 records stored in the Wordpress db. Both numbers should read "1,672".

![image](https://cloud.githubusercontent.com/assets/3789432/17487662/a87459cc-5d4a-11e6-9d7e-2172bea27915.png)

### Technical info
* WordPress version: 4.5
* Algolia Search plugin version: 0.2.6

**Comment by rayrutjes** [comment]
Hi @ethansmith,

We are aware of this issue and we have even added it to the FAQ [here](https://community.algolia.com/wordpress/frequently-asked-questions.html#posts-count-are-wrong-on-facets-when-using-instantsearch-js).

The thing is that we use the DISTINCT feature of Algolia that allows us to split a single post into multiple records on the engine's side. By doing that though we suffer from a limitation of the engine which is that the counts does not play well with facets counts.

For now we recommend hiding the count.

In the future we need to find a solution for this, and the solution has to come from the WordPress plugin and not from the engine.

Currently we split each post into multiple records to be sure we don't reach the engine's hard limit in terms of payload which is fixed to 10kb. Maybe we could allow to disable this 'splitting' on a per index basis to allow counts to be relevant. But then again we have to make sure that the payload of the records do not exceed 10kb.

In your use case, 
- Do you have large post contents?
- Would you trade the records splitting in favor of correct counts?

**Comment by ethansmith** [comment]
Thanks Raymond! To briefly answer your questions:

Our use case does not require large post content loads, and in case some posts did run up against the 10kb limit, I'd be comfortable truncating some of the fields we index in order to stay under that limit. So in our case, yes, I'd happily trade record splitting for correct counts. 

It seems like one possible solution may be for the wp plugin's js to pull info on which posts had been split in order to calculate correct counts and replace default counts with these. Those calculations might require too much overhead to comply with your "instant" response time requirements, though...

**Comment by virtuman** [comment]
We have exact same requirement and we are also more than comfortable with truncating the post content to limit object size to under 10KB. 

Although, according to algolia [ADVICE] tab, it states that we are well under 10kb as-is, yet our facet counts are waaaaaaaaaaaaaaaaaay off

*from [ADVICE] tab* :
The average size of your records is 2.15KB.

**Comment by rayrutjes** [comment]
@virtuman I get your frustration and we are currently investigating to see how we could mitigate this issue.

Currently we split posts based on the DOM. This ensures we always have very light payload sizes.

I'll keep you posted and I am flagging this as a bug 👍

**Comment by rayrutjes** [comment]
@ethansmith @virtuman good news here, the engine will soon allow us to solve this, I'll keep you posted!

**Comment by ethansmith** [comment]
Great news! Thanks for the update.

**Comment by rayrutjes** [comment]
@ethansmith this has been fixed in the instantsearch.js implementation. This is the trick to make it work: https://github.com/algolia/algoliasearch-wordpress/pull/180/files#diff-9feb5a3006c48d882299ea367604dce8R61

Note however that this feature is not working yet in the Algolia dashboard.

Let me know if you manage to make it work on your side!

**Comment by ethansmith** [comment]
@raymond, it took a while for me to finally follow through on this, but yes, your fix worked. Thanks!
