### ISSUE TITLE
Customising relevance by category

### ISSUE THREAD

**Issue by michaeldyrynda** [algolia/algoliasearch-wordpress#151]
This is less an issue with the plugin and more a request to determine if what I'm trying to achieve is possible.

We previously had - under the standard search interface - search results displayed per category, and the categories were weighted based on what the client wanted to show first.

Ideally, we'd be able to rank results in the same way via Algolia, but the custom ranking does this based on integer values, with strings being ranked alphabetically. Perhaps there is some way to apply taxonomy to a category in order to weight them somehow, then rank them that way?

Any guidance would be helpful.

Can you provide a link to a page which shows this issue?

www.moshcam.com - if you click the magnifying glass and search for 'Parkway Drive' and hit enter, this will take you to the search page where we're grouping the results from the Algolia search and displaying them in the manner outlined above.

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version: 0.2.3

**Comment by redox** [comment]
Hi @michaeldyrynda,

this is an interesting personalization use-case!

We're currently working hard to bring personalized search experiences to all Algolia customers \o/ We already have some MVPs running here and there but it will require a bit of custom code for now.

Our current approach is not so about playing with the `customRaking` per category because the `customRanking` is statically defined at indexing time per index: hard to make it scale for a lot of categories. Instead, we are rather applying some optional filters to the query depending on the user's preferences. Those filters would then "boost" some records if they match the category the user has.

So a few questions:
 - are you happy writing custom JS code & using a beta feature?
 - do you have a way to retrieve/have at search time (in the JS code) the list of categories you want to boost for the current user?

**Comment by michaeldyrynda** [comment]
Happy to write some custom JS and I've got handy - server-side, but can expose via JS client-side - the categories I want to boost.

**Comment by redox** [comment]
So, keep in mind this is still beta. As of today, it won't work if your index is a multi-million records index.

So a few things to do:
 - upgrade to the latest 0.2.8 version of the plugin
 - ensure the `category` values are in your record (you can follow our documentation to add [custom attributes](https://community.algolia.com/wordpress/custom-attributes.html)). Your records need to look like:
```js
{
  "objectID": ".....",
  "categories": ["cat1", "cat2", ....],
  [...]
}
```

 * ensure the `categories` attribute is part of your `attributesForFaceting` index setting (you can follow our documentation to [customize index settings](https://community.algolia.com/wordpress/indexing-settings.html) if it's not the case.
 * update the `ranking` index settings to put the `filters` ranking criterion first (you can follow our documentation to [customize index settings](https://community.algolia.com/wordpress/indexing-settings.html). You should have `'ranking': ["filters", "typo", "geo", "words", "proximity", "attribute", "exact", "custom"]`.
 * in your JavaScript code, you need to add an extra query parameter to your query:

```
# let's say the current user is associated to `cat2` & `cat3`
index.search("the user query", { optionalFacetFilters: ["category:cat2", "category:cat3"] });
```

The result of that is that every single matching category filter will increase the value of the `filters` criterion, making our [tie breaking](https://www.algolia.com/doc/guides/relevance/ranking) algorithm retrieve the records with the highest number of filter first.

Let us know how that goes!

**Comment by michaeldyrynda** [comment]
Thanks for the pointers @redox - I'll have a crack at this next week!

**Comment by rayrutjes** [comment]
Hey @michaeldyrynda, I'm curious, did you end up reaching your goal here?

**Comment by michaeldyrynda** [comment]
Hey, I’ve not had a chance as yet - we’ve been busy with other work sadly, so this has taken a backseat for us at the moment. The client has been happy with the autocompletion so far, though.

Michael Dyrynda

Sent from
https://polymail.io/

On Tue., 23 Aug. 2016 at 12:35 am Raymond Rutjes

<
mailto:Raymond Rutjes <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hey
https://github.com/michaeldyrynda
, I'm curious, did you end up reaching your goal here?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/algolia/algoliasearch-wordpress/issues/151#issuecomment-241442816
, or

**Comment by rayrutjes** [comment]
Hey @michaeldyrynda, I'm closing this for now, but feel free to re-open the thread once you took the time to test @redox's solution!
