### ISSUE TITLE
Provide the plugin itself as a Composer package

### ISSUE THREAD

**Issue by dnaber-de** [algolia/algoliasearch-wordpress#152]
For what I see, this repository does not only contain the source of the alolia search WordPress plugin but a complete development environment. Is there maybe an existing repository that I didn't find yet?

It would be nice to have a defined composer package (with type `wordpress-plugin`) that could be used as is in production.

**Comment by rayrutjes** [comment]
You are right @dnaber-de, this repository contains the full development environment.
We are willing to cleanup things a bit here and have an issue opened here: #125 
Feel free to suggest ways to cleanup this repository even more there.

Regarding composer, not sure it is much used in the WordPress community, but I'd gladly expose a package through packagist.

Do you have some examples in mind that exposes their plugin through composer?

**Comment by dnaber-de** [comment]
> Regarding composer, not sure it is much used in the WordPress community, but I'd gladly expose a package through packagist. 

Unfortunately. But it would make live for developers much easier. 

> Do you have some examples in mind that exposes their plugin through composer?
The most popular one might be WooCommerce: https://packagist.org/packages/woocommerce/woocommerce

**Comment by rayrutjes** [comment]
@dnaber-de thank you for the reference. I will take a look and try to come up with a clean way to expose this plugin through composer.

I also secretly hope that WordPress is moving towards composer + GIT :p

**Comment by rayrutjes** [comment]
Hey @dnaber-de, plugin is now available on packagist!
Let me know if it works smoothly for you!

**Comment by dnaber-de** [comment]
Works as expected, thanks a lot!

**Comment by rayrutjes** [comment]
@dnaber-de that is great to hear!!! Feel free to open more of those very useful issues ;)
