### ISSUE TITLE
Woocommerce product indexing and instantsearch support

### ISSUE THREAD

**Issue by virtuman** [algolia/algoliasearch-wordpress#155]
### What did you expect to happen?
Looking to get woocommerce products to get indexed with all required attributes to replace native wordpress+woocommerce search with algolia search.

In my understanding the following is required:

1. Index required post_type product properties + taxonomies + product attributes
2. There's already a Native Search override but it doesn't have any widget or sidebar for faceted search
3. Instantsearch integration

### What happened instead?
1. Post types get indexed but woocommerce category and product specific attributes are not being indexed
2. search probably works but no faceted / layered navigation is displayed
3. related to 2. that category listing page should act similar to search results, ie. display faceted / layered navigation sidebad
4. algolia-instantsearch.js is getting enqueued but I wasn't able to figure out if it actually is used anywhere? no reference in the code to instanctsearch anywhere except for enqueuing the script. Is it supposed to do anything in current implementation based on some widget or some element names?

### How can we reproduce this behavior?
Instantsearch doesn't seem to do anything on a default wordpress + algolia install, without installing woocommerce

but woocommerce specific questions would require a fresh install of:
default install of wordpress + woocommerce with sample data + algolia 

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version: 0.2.8

**Comment by rayrutjes** [comment]
This relates to #156

Again WooCommerce integration with Algolia will be shipped as a separate plugin to isolate code that depends on WooCommerce.

Native Search overriding is kind of misleading and is not something we want to push to hard. Instead we have to find a way to let users implement custom instantsearch.js implementations.

Here is a suggestion of flow:
- Create a new instantsearch.js instance in the admin UI
- Insert an [instantsearch] shortcode on a page (similar experience than  to create a cart page on WooCommerce)
- Provide some basic instantsearch/WordPress Widget that could be enabled/disabled/configured per instantsearch instance

We also need to address the ordering of products.

Please share your 'ideal' way of integrating the instantsearch.js experience.

**Comment by rayrutjes** [comment]
@virtuman  Closed for the same reasons as #156 
Please checkout our new version 0.4.0 which integrates instantsearch.js

Let us know how it works out for you and stay tuned for the Algolia plugin that integrates WooCommerce !

**Comment by avengeralive** [comment]
How to 'Create a new instantsearch.js instance in the admin UI'?

**Comment by rayrutjes** [comment]
@avengeralive , the text you are quoting was a suggestion of flow. Not something that is currently do-able.

If you are interested though, there are a lot of changes / fixes coming in the next release: https://github.com/algolia/algoliasearch-wordpress/milestone/10
