### ISSUE TITLE
Add ability to STOP re-indexing queue (triggered by re-index all).

### ISSUE THREAD

**Issue by virtuman** [algolia/algoliasearch-wordpress#157]
### What did you expect to happen?
Need to add an ability to CANCEL or STOP [re-index all]
Since we have a lot of content (and I assume this is the case for many algolia customers) - re-index all may be super slow, and is super time consuming... especially during initial setup when you are trying to figure out best options, etc.. Would be great to have an ability to stop or cancel full re-index.
Also no way of telling what's currently in queue

### What happened instead?
Cancel Full Re-Index option
View current queue of index

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version: 0.2.8

**Comment by rayrutjes** [comment]
Stopping re-index tasks is definitely something we need. Do you think stopping the queue and allowing to clear it would be enough to begin with?

**Comment by virtuman** [comment]
That's exactly what all of us would LOVE to have. I notice there's a Deactivator class that I assume does pretty much exactly this, that is if you deactivate plugin and then activate it again?

Thank you.

**Comment by rayrutjes** [comment]
I see we can't hide anything from you @virtuman :p

Currently you can disable/re-enable the plugin which will put your plugin in a clean state regarding logs and tasks.

That being said, it is not very scalable as we execute to deletion of all tasks/logs in a single thread which will break if we have a lot of logs/tasks.

This issue has to be fixed for sure!

**Comment by ethansmith** [comment]
+1

**Comment by rayrutjes** [comment]
What we need here is:

- [ ] To not trash tasks that are still failing after 3 attempts,
- [ ] To allow cleaning all pending tasks see #341.

**Comment by rayrutjes** [comment]
@virtuman @ethansmith stay tuned for this, it has just been merged in #342 and will be available in release 1.3.0.

Thanks a lot for reporting this in the first place!
