### ISSUE TITLE
Current Indexer logic is not using WP_Query in the best way and counters pulled separately

### ISSUE THREAD

**Issue by virtuman** [algolia/algoliasearch-wordpress#159]
### What did you expect to happen?
Expected to have a point of integration (ie apply_filters on WP_Query) for individual post_type in Post and User Indexers to be able to apply custom select logic (ie. do not select entries based on certain criteria / business logic to speed up full re-index, instead of selecting everything and rely on shouldIndex, etc. we have a lot of entries that go off website after they expire and with limits through shouldIndex it is resource wasteful to select hundreds of thousands of entries, just to skip them based on logic in shouldIndex) 
But current implementation would not support this filter since wp_count_posts is called separately to retrieve total post type count.

### What happened instead?
`WP_Query` and `wp_count_posts( self::$post_type )` are called separately and wp_count_posts does exact same thing that WP_Query does on it's own anyway.
Both methods don't need to be called alongside each other since WP_Query returns a full count as part of it's logic, ie:
https://codex.wordpress.org/Plugin_API/Filter_Reference/found_posts
https://wordpress.org/support/topic/confusion-with-wp_query-found_posts  
Not only current implementation is not inline with proper codex implementation, but this would also allow to use apply_filters on WP_Query from each indexer or for even for posts indexer to apply different filters for each post_type.

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version: 0.2.8

**Comment by rayrutjes** [comment]
Hi @virtuman,

This is a tricky one. The thing is that we want to let users easily skip posts with shouldIindex filter even based on custom meta fields that may be introduced by other plugins. This seems rather difficult to achieve only with WP_Query.

I totally get your 'optimization' point, but premature optimization being the root of all evil, I'd have to pass on that argument for now ;). Also, we make sure that every task execution is ran in its own php process to ensure the indexation is scalable.

I think what we have now is developer friendly, but I'd gladly take additional inputs if you think it can be improved.

We are also thinking of introducing a CLI tool that would allow for faster indexation.

I'll leave this discussion open for now as we might want to bat ideas around here while enhancing the indexing.

**Comment by rayrutjes** [comment]
As explained, I don't think letting people tweaking the WP_Query makes sense in our case. Since a recent release we even 'suppress_filters' so that we index all posts even when plugin such as WPML introduces filters.

I'm closing this for now. Feel free to open a new issue if you feel this still applies to the latest version. I'd gladly improve this part!
