### ISSUE TITLE
Need clarification on when Searchable Posts used vs Posts ?

### ISSUE THREAD

**Issue by virtuman** [algolia/algoliasearch-wordpress#160]
Maybe its documented somewhere but I wasn't able to find or figure it out:
when is Searchable Index should be used vs Posts index?
Posts seems to allow to select more granularly which Post Types to index, and Searchable Posts is different only in a way that it will select all Post Types and Taxonomies are marked as searchable.

Is there any benefit to using one indexer over the other? Or is Searchable Posts used in some other way and is required to be used for something that was not very obvious from documentation?

Thank you.

**Comment by rayrutjes** [comment]
First of all thank you for all the hard work here @virtuman , appreciated!

I agree, we need to clarify the difference between Searchable Posts and Posts.

In the end I think best would be to change a bit our approach here to let users create indices by choosing what they will contain in terms of post types taxonomies and users.

This will also allow us to remove the code duplicate between Search Post index and Posts Index.

This is our focus right now.

**Comment by virtuman** [comment]
All of the Indexer classes denoted Final, do you think that maybe Posts_Index shouldn't be Final and then make it a little less flexible to promote extensibility for advanced implementations?
We are currently implementing Woocommerce Product indexing to work alongside with instansearch (just like you have on magento implementation), but looks like we need to write a little more code because while it is super easy to extend indexing of Posts entries - it has a couple of minor limitations that force us to write a looooot of code that we'll need to continuosly compare against your future upgraded versions. Just a thought anyway.

**Comment by rayrutjes** [comment]
@virtuman we need to re-factor a bit the indices classes.
Indeed we should make it easy to create for example 2 indices that both index for example products.

Currently this indeed requires some code.

We are thinking of creating a single 'index' class that can contain any content type.
That will ease extensibility. WDYT?

Would you mind sharing your custom class you used for Products Index so that we can make sure we do not forget anything?

**Comment by rayrutjes** [comment]
In the end we may want to merge the Searchable_Posts index class with the Posts_Index class.

**Comment by rayrutjes** [comment]
Hi @virtuman , 

Basically to clarify, searchable_posts index contains all posts flagged as not being excluded from search.
It is also the basic index used for the search page.
The other indices are the one that will be used in the Autocomplete experience, and are scoped to 1 post type in particular.

If users enable Algolia to power the search page, and if that index is not flagged for indexing, we now display a notice on every admin page of WordPress to alert about the bad configuration.

I believe this makes it much clearer.

I'm closing this for now, feel free to open a new issue if you have anything else to discuss ;)

Thanks for all the hard work, very much appreciated!

**Comment by Salamander3** [comment]
So, do i need to select every CPT or selecting searchable_posts is enough? I don't want extra records if searchable_posts already contains all CPTs.
