### ISSUE TITLE
How to scope results per language with WPML integration

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#168]
Explain:
- How to scope results per language with autocomplete.js
- How to scope results per language with instantsearch.js

**Comment by royduin** [comment]
I just figured some stuff out, I wanted to show the results per language. So I've a Wordpress install with WPML and two languages configured: Dutch and French I only wanted Dutch search results on the Dutch website and French on the French website. What I've done to accomplish this:

1) Added the code suggested here in my theme `functions.php`: https://community.algolia.com/wordpress/wpml.html
2) Copied the the templates from the `templates` directory in the Algolia plugin to my theme in a `algolia` directory
3) Modified the just copied `autocomplete.php` template and added this after the `attributesToSnippet` array:
```
facetFilters: 'wpml.language_code:'+jQuery('html')[0].lang.substr(0,2)
```

4) Modified the just copied `instantsearch.php` template and added this after the `facetingAfterDistinct`:
```
facets: ['wpml.language_code']
```

And added this between the other widgets.
```
search.addWidget({
	init: function(options){
		options.helper.addFacetRefinement('wpml.language_code', jQuery('html')[0].lang.substr(0,2));
	}
});
```

Maybe this is something to add to the docs or better: implement this in the plugin with a detection if WPML is installed.

**Comment by sebastiansson** [comment]
Hi!

What's the status on this? I've added `facetFilters: 'wpml.language_code:'` to autocomplete.php, and it works. But of course I don't want to modify the plugin files directly. How do we solve it? I tried to find something explaining this in your docs, without success.

Or do you guys see this as something where we should use the autocomplete.js library separately instead of the out-of-the-box search input a.k.a `get_search_form()`?

**Comment by rayrutjes** [comment]
Hey @sebastiansson , indeed I would recommend not customizing the plugin files directly.
Instead you can copy paste the autocomplete.php file in your own theme folder under a directory called Algolia.
You can customize that new file instead.

This is explained here: https://community.algolia.com/wordpress/customize-autocomplete.html#algolia-search

Does that make sense @sebastiansson ?
If by any chance you are willing to open a PR to complete the docs about WPML, please do it :)
