### ISSUE TITLE
Multiple autocomplete popup instances: width

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#172]
@rayrutjes, I know this is related to an issue you just addressed in the most recent update. Minor bug I noticed:

### What did you expect to happen?

For better or worse, the wp theme I'm using creates two headers on page load: one for desktop, and one for mobile. Then when window size changes visibility on both headers is toggled. Each one of these headers contains a search input which the Algolia script replaces with autocomplete input and associated popup element. I'd expect the width of each popup element to be the same as the related input element.

### What happened instead?

The width of all popup elements is defined by the width of the last/final/_n_th input that's identified and replaced. In my case, both popup elements match the width of the mobile header's search input.

### How can we reproduce this behavior?

Load multiple search inputs with various widths. 

Can you provide a link to a page which shows this issue?

PM me if you'd like to see an example.

### Technical info
* WordPress version: 4.6
* Algolia Search plugin version: 0.3.0

**Comment by rayrutjes** [comment]
Thank you for catching this one @ethansmith, this is definitely a bug and flagged as is ;)

Will try to fix this one after I've completed the integration of instantsearch.js #170

**Comment by rayrutjes** [comment]
@ethansmith I'm having a hard time reproducing this one, would you mind sharing the theme you are using or maybe give me more context?

For me the width of each dropdown is actually determined by each related input size.
There is probably an edge case related to the way we handle the resize event.

**Comment by ethansmith** [comment]
@rayrutjes, pm sent to your email with a link.

This edge case may well have to do with the fact that both of the search inputs are actually hidden on initial page load. If you close and then open the autocorrect window from either desktop or mobile headers, the width will get recalculated correctly.

**Comment by rayrutjes** [comment]
@ethansmith any chance you try the little tweak of #177 ?

**Comment by rayrutjes** [comment]
Hi @ethansmith 
Haven't heard back from you but the previously linked PR should fix your issu.

**Comment by ethansmith** [comment]
Hi @rayrutjes. Worked like a charm. Thanks! 👍

**Comment by rayrutjes** [comment]
That's great to hear 😄  @ethansmith
