### ISSUE TITLE
Detect broken images in instantsearch.js templates

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#182]
It would be nice if we could somehow detect broken images and display a fallback image or simply a background that fills the gap:

https://github.com/algolia/hn-search/blob/master/app/assets/javascripts/controllers.js#L676-L697

**Comment by vvo** [comment]
@maxiloc Do we do that in magento? I am always relunctant fixing user side bugs inside your own code, it can bite you afterward.

**Comment by vvo** [comment]
For example, waiting for the onload event on images delay images display for everyone only because some users might have broken images somewhere. This means we potentially have a performance impact because we are trying to fix a user bug.

**Comment by maxiloc** [comment]
No. Magento has a placeholder system nothing is done on our side

**Comment by rayrutjes** [comment]
Thank you for discussing this @clement-leprovost .
I think indeed that this can become a pain to debug for users that do not realize what is happening.

**Comment by vvo** [comment]
If any users comes here saying "When images are in 404 could we display something". But I don't believe anyone will come here, they will just fix their own data which is the right way to go

**Comment by redox** [comment]
> For example, waiting for the onload event on images delay images display for everyone only because some users might have broken images somewhere. This means we potentially have a performance impact because we are trying to fix a user bug.

You can experience it live on hn.algolia.com ; I think it's a pretty smooth ux.

**Comment by rayrutjes** [comment]
Not sure to see where it comes into play on HN @redox , could you screencap?

**Comment by vvo** [comment]
@redox Yes looks nice on HN indeed.

As for the wordpress extension, as soon as you include this code, people having their own lazyloader etc might be confused that your code is conflicting with theirs. Things like that.

I am not against it, but just that it will potentially hide or create issues for users of the extension.

> Not sure to see where it comes into play on HN @redox , could you screencap?

You have to activate experimental mode.

**Comment by rayrutjes** [comment]
Wow experimental mode looks gorgeous!
That being said, I kind of agree with @vvo on this one.

I think it would be wiser to not include this for now. Let's wait and see if this could actually benefit users.

**Comment by redox** [comment]
> As for the wordpress extension, as soon as you include this code, people having their own lazyloader etc might be confused that your code is conflicting with theirs. Things like that.

Definitely 👍 

> I think it would be wiser to not include this for now. Let's wait and see if this could actually benefit users.

Yep, reasonable decision 💯
