### ISSUE TITLE
Make docs header compliant with other community websites

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#194]
~~[ ] Typography~~

- Font-weight

/cc @AntoinePlu

**Comment by LukyVj** [comment]
Can you be more clear about that ? 

It's the exact same font.. ? 

Places.js : 
![](https://puu.sh/rrHf5/0388449011.png)

WordPress : 
![](https://puu.sh/rrHf5/0388449011.png)

The only diff is the font weight I think.

**Comment by rayrutjes** [comment]
Please check this out with @AntoinePlu who initially brought this to my attention ;)

**Comment by LukyVj** [comment]
So @AntoinePlu @rayrutjes I think the problem is reversed. 
Here, we do have the proper navigation bar. 

The issue is that, all the community websites should have such nav bar (max-width: 1440px) 

So I think we can close this issue while I'm updating all the navbars of all the community websites.

**Comment by rayrutjes** [comment]
![image](https://cloud.githubusercontent.com/assets/5570853/18960471/32154bb2-866a-11e6-8e92-4ac37253d905.png)
I don't like the current display, it was better in full width.

**Comment by LukyVj** [comment]
Same for me actually.. :/
