### ISSUE TITLE
Autocomplete should use the same template overriding strategy than instantsearch

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#203]
Right now we do

```php
$templates = array(
  'header'          => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-header.php',
  'post-suggestion' => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-post-suggestion.php',
  'term-suggestion' => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-term-suggestion.php',
  'user-suggestion' => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-user-suggestion.php',
  'footer'          => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-footer.php',
  'empty'           => plugin_dir_path( __FILE__ ) . '../templates/autocomplete-empty.php',
);
```

and we should rather use the `locate_template` as in instantsearch, to easily patch the templates in the `algolia` copy of the `templates` folder.

**Comment by rayrutjes** [comment]
Definitely, I should also take this opportunity to maybe actually make use of the empty template!

**Comment by redox** [comment]
Also, we should include the autocomplete JS implementation in those templates. I wanted to customize the look and feel of the dropdown menu, and it's not super convenient for now.

**Comment by rayrutjes** [comment]
Agreed @redox, will do, makes sense to re-produce the IS implementation.
