### ISSUE TITLE
Make deep linking possible for instantsearch.js refinements

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#208]
Currently we use only the query string `s` parameter in instantsearch.js.

I think we should use anchors by default and only use the `s` parameter at initialization.

This will allow users to deep link to a specific refined search while still acting as a drop in replacement for the WordPress search by interpreting the `s` parameter.

**Comment by rayrutjes** [comment]
If we implement this, we should also add an option to the Autocomplete configuration to let the user choose wether to redirect to basic WordPress pages or to the search page with enabled refinements.

**Comment by rayrutjes** [comment]
Given that we've had very few requests for this feature and that we can not assume what kind of urlSync mapping is being used for the instantsearch.js experience, I'm closing this for now.

**Comment by harshmaur** [comment]
Hi @rayrutjes, I was looking for a feature to enable complete urlSync on my wordpress instantsearch page. I do not see any option yet to enable to same. Can we have it?

**Comment by rayrutjes** [comment]
Hey @harshmaur ,

What do you mean by "complete"?

**Comment by harshmaur** [comment]
Hi @rayrutjes , Currently it tracks ['q'] and one more variable I think. However if someone selects a category or goes to next page, I want those to be tracked in the url as well. So by complete, I want algolia to track all the parameters which we get when we use instantsearch.js by manual implementation `urlSync: true`

**Comment by rayrutjes** [comment]
I see @harshmaur ,
I now remember that this is because we thought it was more important to track the native `s` query than the other ones.
The issue is that the `s` parameter is a query param, and the other ones would eventually be hashtags.
As of today, instantsearch v1 doesn't support mixing hashtags and query parameters in the urlsync feature.

**Comment by harshmaur** [comment]
I dont know if I quite understood you @rayrutjes. Which hastags are you talking about? I have used vanilla instantsearch.js in one of my projects before and I used to get tracking for all filters I applied. 

Are you saying its not possible to do in wordpress yet?

**Comment by rayrutjes** [comment]
Actually it is possible if you choose to pass the the `s` parameter as an anchor instead of as a query parameter.
Replacing the value of urlSync here with an empty object or `true` should do the trick: https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/instantsearch.php#L58

**Comment by harshmaur** [comment]
Well @rayrutjes I would have done that, but I thought if there is an easier way without modifying the plugin itself.

**Comment by rayrutjes** [comment]
You can duplicate the template file in an "algolia" folder of your theme: https://community.algolia.com/wordpress/customize-search-page.html#algolia-search

**Comment by harshmaur** [comment]
It only broke the code and algolia started giving this weird error. `Invalid value for "synonyms" parameter, expected boolean`

**Comment by harshmaur** [comment]
@rayrutjes Can you help?
