### ISSUE TITLE
Template Overriding not working

### ISSUE THREAD

**Issue by rahilwazir** [algolia/algoliasearch-wordpress#211]
### What did you expect to happen?

Wanted to override the autocomplete [templates](https://github.com/algolia/algoliasearch-wordpress/tree/master/templates), by copying them under theme `mytheme/algolia`. E.g:

- `mytheme/algolia/autocomplete-empty.php`
- `mytheme/algolia/autocomplete-footer.php`
- ...

Reference [Docs#Customization](https://community.algolia.com/wordpress/customization.html#customizations)

### What happened instead?

It didn't work.

### How can we reproduce this behavior?
Follow the [Docs#Customization](https://community.algolia.com/wordpress/customization.html#customizations), copy files from `templates` directory to `mytheme/algolia` and modify the templates, it won't reflect changes to autocomplete view.

Can you provide a link to a page which shows this issue?
- Not available at the moment

### Technical info
* WordPress version: 4.6
* Algolia Search plugin version: 0.5.0

As far as I see the method `Algolia_Public()->inject_autocomplete_templates()` is using hardcoded `plugin_dir_path( __FILE__ )` plugin directory path to locate templates. It would always load the plugin templates unless we change the path using the filter `algolia_autocomplete_templates`.

And yes applying filter to the hook (`algolia_autocomplete_templates`) working.

**Comment by rahilwazir** [comment]
Not sure is this a duplicate to https://github.com/algolia/algoliasearch-wordpress/issues/203?

**Comment by rayrutjes** [comment]
Yes it it @rahilwazir ;) But thank you for the reflex of creating issues, appreciated!
This will be fixed very soon!

Closing it in favor of #203
