### ISSUE TITLE
Need multiple thumbnail sizes

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#218]
Right now, we use a single & default (150x150) thumbnail for the post featured image. It turns out, those images have a 2:1 ratio most of the time, and such square size doesn't really fit.

For instance:

![screen shot 2016-09-06 at 10 58 39](https://cloud.githubusercontent.com/assets/29529/18267743/e000b2c2-7420-11e6-9065-0561e88d9fea.png)

We should include additional thumbnail sizes in our records like we used to do in https://github.com/algolia/algoliasearch-wordpress/blob/v0/core/WordpressFetcher.php#L55-L93.

**Comment by rayrutjes** [comment]
Definitely!
