### ISSUE TITLE
Error on publishing or updating blog posts and woo products

### ISSUE THREAD

**Issue by k1raoufi** [algolia/algoliasearch-wordpress#25]
When publishing or updating a post, I get the following error. Deactivating the Algolia plugin fixes the issue. Thank you.

Notice: Undefined index: default_attribute in /www/wp-content/plugins/algoliasearch-wordpress-master/AlgoliaPluginAuto.php on line 76 Fatal error: Uncaught exception 'Exception' with message 'Unknown attribute: meta' in /www/wp-content/plugins/algoliasearch-wordpress-master/core/Registry.php:68 Stack trace: #0 /www/wp-content/plugins/algoliasearch-wordpress-master/core/Indexer.php(109): Algolia\Core\Registry->__get('meta') #1 /www/wp-content/plugins/algoliasearch-wordpress-master/AlgoliaPluginAuto.php(77): Algolia\Core\Indexer->indexTerm(Object(stdClass), 'category') #2 [internal function]: AlgoliaPluginAuto->termTaxonomyUpdated(5, 'category') #3 /www/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #4 /www/wp-includes/taxonomy.php(4101): do_action('edited_term_tax...', 5, 'category') #5 /www/wp-includes/taxonomy.php(3672): _update_post_term_count(Array, Object(stdClass)) #6 /www/wp-includes/taxonomy.php(3645): wp_update_term_count_now(Array, 'category') #7 /www/wp-includes/post.php(5909): wp_update_term_count(Array, 'category') #8 [internal function]: _update_term_count_on_transition_post_status('publish', 'publish', Object(WP_Post)) #9 in /www/wp-content/plugins/algoliasearch-wordpress-master/core/Registry.php on line 68

**Comment by maxiloc** [comment]
I am not able to reproduce it.
