### ISSUE TITLE
Abundance of sync_item records upon updating a post

### ISSUE THREAD

**Issue by diedexx** [algolia/algoliasearch-wordpress#250]
### What did you expect to happen?
When updating a single post I expect a post with post_type 'algolia_task' with title 'sync_item' to be written to the database so it can be handled by the Task_Dispatcher.  After the task is handled, I expect it to be removed from the database.

### What happened instead?
Instead, when updating a post in the wp backend, multiple post with post_type 'post' and title 'sync_item' are added to the database. 
<details>
<summary>screenshot of the db entries (click)</summary>
![_mysql_5_6_31-0ubuntu0_14_04_2__vvv_yoast_wp_posts](https://cloud.githubusercontent.com/assets/5352634/18514585/71698eb0-7a92-11e6-99a5-a43d477360f3.png)
</details>
It _appears_ as if the creation of these records keeps on going until the initial "update post" request times out and an error 500 is given.

Since these records do not have the 'algolia_task' post_type, they're not handled by the dispatcher and will remain in the database. Also, because they _do_ have the 'post' post_type, they're all shown in the post overview as private posts.
<details>
<summary>screenshot of the posts table (click)</summary>
![posts_ _yoast_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/18514762/20c5737e-7a93-11e6-8cb0-7939c06fb8f8.png)
</details>

The logs provided by this plugin remain empty when this occurs.

### How can we reproduce this behavior?
Create a post with a title and leave the content empty. Publish the post. 
Now, (without changing anything (has no effect on the bug)) click "update".
If you check your wp_posts table in the database now, you can see the sync_items stacking up. While this is happening, the post is still not done with updating.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 0.6.2

I am not using any of the filters which are provided by this plugin when this occurs.

<br>
keep up the good work! 👍

**Comment by rayrutjes** [comment]
Thx a lot @diedexx , are you using post type switcher plugin?

**Comment by diedexx** [comment]
I do, didn't realise that..
Are there any plans on improving compatibility with post type switcher in the near future?

**Comment by rayrutjes** [comment]
Yes @diedexx , this issue should fix yours: https://github.com/algolia/algoliasearch-wordpress/issues/233

I hope I'll have some time to do this tomorrow ;), should be an easy fix,

I'll keep you posted!

**Comment by diedexx** [comment]
Sounds good! Thanks!

**Comment by rayrutjes** [comment]
@diedexx shouldn't spawn posts anymore ;)
