### ISSUE TITLE
Add WP-CLI support

### ISSUE THREAD

**Issue by Mamaduka** [algolia/algoliasearch-wordpress#252]
First indexation (or even re-indexing all data) is heavy process, when you're dealing with few thousand records.

[ElasticPress](https://github.com/10up/ElasticPress) has good example of similar implementation.

**Comment by rayrutjes** [comment]
Thx for submitting this @Mamaduka , providing a command line tool is indeed something we will consider.

By the way we also recently raised the number of posts to index per batch to 50.

We will keep you posted on this ;)

**Comment by rayrutjes** [comment]
Hi @Mamaduka , I started some work on this yesterday. Basically you should be able to run:

```bash
$ wp algolia process-queue
```

To test this, you can disable automatic processing of tasks by adding `define( 'ALGOLIA_AUTO_PROCESS_QUEUE', false );` to your `wp-config.php` file.

Currently there is an error at the end of the processing but the tasks are processed just fine.

Let me know if this is what you expected to see implemented, and I'll finish ASAP.

Checkout #259 to test this feature.

**Comment by Mamaduka** [comment]
@rayrutjes yes I think this looks good as a first pass for WP CLI support. Is it possible to override bulk size via CLI command?

Maybe something like this:
```
$ wp algolia process-queue --batch_size=500
```

**Comment by rayrutjes** [comment]
Sure @Mamaduka makes a lot of sense. I would just like to fix the error I currently get at the end of the queue processing.

**Comment by rayrutjes** [comment]
Hey @Mamaduka I merged a first version of the CLI with 2 commands, see #259 

I will quickly add some other commands in upcoming releases.

Feel free to let me know what you think ;)
