### ISSUE TITLE
Inability to combine indices

### ISSUE THREAD

**Issue by imjared** [algolia/algoliasearch-wordpress#254]
### What did you expect to happen?

In v0.1 of Algolia Realtime Search (old school, I know), it seems like each post type that got indexed would get pushed into one index. I'm using v0.6.2 now and expected ability to customize where post types were indexed.

### What happened instead?

Each post type is created a separate index. Because we have several post types, we have several indices. We have to search each index individually so instead of the most relevant results overall (eg. a film or a festival) we get irrelevant results in some post types and relevant results are therefore lost in the noise.

### How can we reproduce this behavior?

It seems to be the default behavior.

### Can you provide a link to a page which shows this issue?

Sure. https://filmlinc.org Click the "search" text in the top right (desktop only). Try searching for "two friends" as if you were looking for information about the film "Two Friends". There's a lot of not-so-useful content in the results widget.

### Technical info
* WordPress version: 4.5.4
* Algolia Search plugin version: 0.6.2

Apologies if I'm missing something obvious. I've combed through the WordPress plugin docs and it doesn't seem like there's a way to sync multiple post types to a single index. 

We're using autocomplete.js and it doesn't seem like there's a way to combine indicies from the frontend. Looking in the instantsearch docs don't seem to have a way to combine indices either but [this issue](algolia/instantsearch.js/issues/1056) makes me think it's doable if we switch to instantsearch.js.

Ideally, we'd like to send multiple post types to the same index and have an attribute of "type" that we could show to our users.

**Comment by rayrutjes** [comment]
Hi @imjared , thank you for creating this issue!

The searchable posts index contains all post types that are "searchable". You could use that one in your autocomplete.
This index also includes the 'post_type' and 'post_type_label' that you could display along with the results.

Since 0.6.x it is now very easy to customize the autocomplete experience.

Copy paste the 'templates' folder and rename it to 'algolia' in your theme and go edit the autocomplete.php file.

I hope this helps, let me know if something is not clear,

**Comment by imjared** [comment]
Well how about that. Had a feeling there was something simple I was missing. As usual, you all are rock stars.

**Comment by rayrutjes** [comment]
Thx for the kind words @imjared ;) feel free to re-open issues if you have any question!

**Comment by ChrisButterworth** [comment]
I'm having the same issue still, I've copied over the templates to customise the template and some configuration but still can't see how you'd merge indices together to get the most relevant result at the top rather than the first result of the first index.

**Comment by ChrisButterworth** [comment]
Figured this out, needed to select "All Posts" within the settings and use the `algolia_post_types_blacklist` filter to exclude post types
