### ISSUE TITLE
Fatal Error on saving UI configuration tab

### ISSUE THREAD

**Issue by deepankarpathak** [algolia/algoliasearch-wordpress#26]
Got some unexceptional error while saving the plugin. Pasting the exact error below. 

Fatal error: Uncaught exception 'AlgoliaSearch\AlgoliaException' with message 'Operations quota exceeded, change plan to get more Operations.' in /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/lib/algolia/algoliasearch.php:532 Stack trace: #0 /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/lib/algolia/algoliasearch.php(408): AlgoliaSearch\Client->doRequest(Object(AlgoliaSearch\ClientContext), 'PUT', 'M77JEJ0MR1-3.al...', '/1/indexes/wpek...', Array, Array) #1 /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/lib/algolia/algoliasearch.php(987): AlgoliaSearch\Client->request(Object(AlgoliaSearch\ClientContext), 'PUT', '/1/indexes/wpek...', Array, Array) #2 /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/core/AlgoliaHelper.php(53): AlgoliaSearch\Index->setSettings(Array) #3 /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/core/AlgoliaHelper.php(144): Algolia\Core\A in /home/edukart/public_html/alpha/wp-content/plugins/algoliasearch-wordpress-0.0.3/lib/algolia/algoliasearch.php on line 532

**Comment by redox** [comment]
Hi @deepankarpathak,

thank you for the report. Unfortunately, that's not a bug: it says that you've reached the maximum number of operations included in your plan -> I assume you were tested it with our Hacker/FREE plan?

```
'AlgoliaSearch\AlgoliaException' with message 'Operations quota exceeded, change plan to get more Operations.'
```

You'll need to remove unused indices/records or upgrade to a bigger plan. Let me know if you need some help with that!

**Comment by dannymichel** [comment]
@redox how do i 

> remove unused indices/records

**Comment by zerbfra** [comment]
This IS a bug. When the limit is reached, it gives a 500 error on server.
Here is the php error log:

[error] 1044#0: *40656255 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'AlgoliaSearch\AlgoliaException' with message 'Operations quota exceeded, change plan to get more Operations.' in /usr/nginx/wordpress/wp-content/plugins/search-by-algolia-instant-relevant-results/includes/libraries/algoliasearch-client-php/src/AlgoliaSearch/Client.php:992

**Comment by rayrutjes** [comment]
Hi @zerbfra ,

This error should be catched indeed. Can you confirm you are using the last version of the plugin?
If so, please do open a new issue so that we can address it.

**Comment by zerbfra** [comment]
I'm on the last version of the plugin.
I will open a new issue
