### ISSUE TITLE
Apostrophes in post_type_label: autocomplete

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#262]
### What did you expect to happen?

Apostrophe in my cpt label to display as apostrophe

### What happened instead?

Apostrophe displayed as encoded html `&#039; `

![image](https://cloud.githubusercontent.com/assets/3789432/18764428/43be606e-80c6-11e6-86da-f83b29ff6279.png)

### How can we reproduce this behavior?

Index a cpt with an apostrophe in its label.

Can you provide a link to a page which shows this issue?

See image above.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.0

**Comment by ethansmith** [comment]
FWIW, I'm getting around this issue in the short term by using `&rsquo;` rather than `&#039;` in my cpt label.

**Comment by rayrutjes** [comment]
I think your use case makes sense @ethansmith so I wen't ahead ;)
