### ISSUE TITLE
Problem with Algolia Plugin

### ISSUE THREAD

**Issue by KogtaSaloni** [algolia/algoliasearch-wordpress#27]
Hello
 I want to use the Algolia Plugin for Wordpress. But I have been facing a problem.
After filling in the credentials, browser does not get redirected anywhere.
Also, the interface for the settings looks nothing like the one shown on the Github page(the 7 bars on top are not peresent).

Help will be appreciated
Thanks

**Comment by redox** [comment]
Hi @KogtaSaloni,

thanks for the bug report. Could you check if you have some JavaScript errors in your JS console?

**Comment by KogtaSaloni** [comment]
Yes, there is:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by redox** [comment]
Hmmm, not sure it's related; could you try to dig deeper -> which network call returned a 500 error?

**Comment by KogtaSaloni** [comment]
Hey!

This is the complete error that I am encountering:
Failed to load resource: the server http://localhost/wp-admin/admin-post.php responded with a status of 500 (Internal Server Error)

Does this have anything to do with hosting the website on localhost?

**Comment by KogtaSaloni** [comment]
![1](https://cloud.githubusercontent.com/assets/8505782/8078312/6ca6b44a-0f7a-11e5-857f-2b1bbcd0adf3.png)

Is this how the interface should look?

**Comment by redox** [comment]
@KogtaSaloni Oh ok, so that's expected. You need to create an Algolia account and fill your credentials. Once setup, the other tabs will be displayed.

**Comment by KogtaSaloni** [comment]
After putting in the details, this is what I am getting:

![2](https://cloud.githubusercontent.com/assets/8505782/8078373/087e74ac-0f7b-11e5-8491-e0c4dfe9c1d9.png)

**Comment by maxiloc** [comment]
Can you check if you have something in your php/apache errors log.

**Comment by KogtaSaloni** [comment]
This is latest entry of /var/log/apache2/error.log:

[Wed Jun 10 13:57:56.748731 2015] [:error] [pid 30045] [client 127.0.0.1:53718] PHP Fatal error:  Uncaught exception 'Exception' with message 'AlgoliaSearch requires the CURL PHP extension.' in /var/www/html/wp-content/plugins/algoliasearch-wordpress-master/lib/algolia/algoliasearch.php:132\nStack trace:\n#0 /var/www/html/wp-content/plugins/algoliasearch-wordpress-master/core/AlgoliaHelper.php(16): AlgoliaSearch\\Client->__construct('FKSP7HR4GJ', '1f2bcea581aded7...')\n#1 /var/www/html/wp-content/plugins/algoliasearch-wordpress-master/AlgoliaPlugin.php(223): Algolia\\Core\\AlgoliaHelper->__construct('FKSP7HR4GJ', '70f129fb31aa236...', '1f2bcea581aded7...')\n#2 [internal function]: AlgoliaPlugin->admin_post_update_account_info('')\n#3 /var/www/html/wp-includes/plugin.php(496): call_user_func_array(Array, Array)\n#4 /var/www/html/wp-admin/admin-post.php(69): do_action('admin_post_upda...')\n#5 {main}\n  thrown in /var/www/html/wp-content/plugins/algoliasearch-wordpress-master/lib/algolia/algoliasearch.php on line 132, referer: http://localhost/wp-admin/admin.php?page=algolia-settings

**Comment by maxiloc** [comment]
Yes, so you need to install curl to be able to use the extension

**Comment by KogtaSaloni** [comment]
Thank you so much!
You guys are great :D
