### ISSUE TITLE
cURL < 7.34 fallback

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#273]
Below 7.34 cURL doesn't handle TSL 1.1/1.2 nor SSLv2 making it not work depending on the certificates.

We should implement a fallback here.

**Comment by rayrutjes** [comment]
If domain is served over https and curl version < 7.34 we should fallback to the stream transport.

Be careful about BC because WP_Http seems to be introduced recently, so filters like `use_curl_transport` & `http_api_transports` do not seem to be called in older version of WordPress.

Also it seems we have to double check the behaviour of the stream transport, it does not seem to work very well with non blocking / short timeouts.

**Comment by Mamaduka** [comment]
`use_curl_transport ` - introduced in WP 2.7.0
`http_api_transports` - WP 3.7.0

Based on plugins readme.txt you support WP >= 3.7.0.

Also I would recommend bumping minimum required WP version. Most major plugins support WP >= 4.4.0.

BuddyPress has pretty good guidelines for WP version compatibility - https://codex.buddypress.org/getting-started/wordpress-version-compatibility/

**Comment by rayrutjes** [comment]
You are probably right @Mamaduka we should probably drop support for versions below 4.4.0.
Thx for the link.

Regarding the implementation details, problem is WP_Http was only introduced very recently. At least, `Requests` static class was used before in the `wp_remote_post` calls. Just need to figure in what WordPress version the `Requests` class has been removed in favor of the `WP_Http ` class usage.

**Comment by Mamaduka** [comment]
@rayrutjes `WP_Http` abstraction class was in core since 2.7. In 4.6 it was "replaced" with Requests library. You can find detailed info here - https://core.trac.wordpress.org/ticket/33055.

Core team usually recommends using wrapper function (`wp_remote_*`) instead of calling classes directly. Which I think is the way Algolia plugin utilizes this API.

**Comment by rayrutjes** [comment]
We are focusing on cURL as it is also used by the API client.
We will also drop support for lower versions of WordPress in the near future.
