### ISSUE TITLE
Changes on the call to action in the header

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#286]
- [x] WP small logo in the button should be next to the label and both center aligned.
- [x] WP small logo in `16x16px`
- [x] Button max-width in `200px`
- [x] Keep it in red `#FB366E`

**Comment by LukyVj** [comment]
@AntoinePlu Are you sure this is what you want ? 
![](https://puu.sh/rqBXL/2e355f9839.png)

**Comment by LukyVj** [comment]
Fixed in 56fe579
