### ISSUE TITLE
Align the compatibility descr with the button

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#287]
Like in this example, could we have the compatibility description on two lines next to the button ?

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3l1E0n0b2L391Z1i0L2U/Image%202016-09-28%20at%2011.22.30%20AM.png?X-CloudApp-Visitor-Id=667340&v=1ddcf28c)

**Comment by LukyVj** [comment]
Why does the button is red ? It's from the sketch, right ?

**Comment by LukyVj** [comment]
Fixed in 56fe579
