### ISSUE TITLE
Fix the diagonal issue in the header

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#289]
I know we limited the diagonal for wide-screens but on my classic resolution at 1440px on my laptop, I'm seeing the the beginning of that and we shoudn't. cc @Shipow 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0d1q002t0K1Z3g1Y2A21/Screen%20Shot%202016-09-28%20at%2011.30.51.png?X-CloudApp-Visitor-Id=667340&v=f75424cf)

**Comment by LukyVj** [comment]
Should be fixed in 56fe579

**Comment by LukyVj** [comment]
But I let the issue open, until I got your word about the fix :v:

**Comment by AntoinePlu** [comment]
LGTM @LukyVj 👍
