### ISSUE TITLE
Changes on feature focus description

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#290]
On the SVG Icon:

- [x] `margin-bottom: 24px`

On the feature Title:

- [x] Switch the font to `Open Sans`
- [x] with a `font-weight: 600`
- [x] and a `color: #55606E`
- [x] `margin-bottom: 8px`

On the feature Description:

- [x] Article `max-width: 400px`
- [x] On `<p>`: `font-size: 14px`
- [x] `line-height: 22px`

**Comment by LukyVj** [comment]
Fixed in 56fe579
