### ISSUE TITLE
Align the features blocks

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#295]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3S092C3g101C040g0w2U/Artboard%20Copy.png?X-CloudApp-Visitor-Id=667340&v=f28cecad)

**Comment by LukyVj** [comment]
I had the same feeling as you. But you have to know, the containers are aligned : 

see the blue lines. 

![](https://puu.sh/rqEGX/f952aabf63.png) 



But I will make it less crazy :)
