### ISSUE TITLE
Delete the Github counter from the Banner-Header

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#297]
Can we delete the Github counter from the banner-header?
We already have it down the page, we also already have the GitHub link in the community header.
IMHO we're bringing to much information for this space.

**Comment by rayrutjes** [comment]
I agree with @AntoinePlu we can postpone that information IMO as well.

**Comment by Shipow** [comment]
agree. + the lambda wp user don't need that info.

**Comment by LukyVj** [comment]
Braa On it :)

**Comment by LukyVj** [comment]
FIxedin 	38908b8
