### ISSUE TITLE
Align Feature description to the images

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#298]
Can we vertically-align the content of every feature block like this ?

![](https://d3vv6lp55qjaqc.cloudfront.net/items/281h0y163n0g2W2g0k2r/autocomplete.png?X-CloudApp-Visitor-Id=667340&v=01dc0a1c)
![](https://d3vv6lp55qjaqc.cloudfront.net/items/453E3d0M3n1a2C2s1G3s/realtime.png?X-CloudApp-Visitor-Id=667340&v=9649b5c7)

**Comment by LukyVj** [comment]
Sure
