### ISSUE TITLE
Fix typo in the header

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#311]
Actually we have : `Compatible from 3.7 to latest version of Worpress`

Can we fix `Wordpress` to `WordPress` please?

**Comment by JanPetr** [comment]
And it should be `.. to the latest version ...` , with `the`

**Comment by rayrutjes** [comment]
Yes, we can even remove this part entirely. Users expect it to work that is all.

**Comment by LukyVj** [comment]
So, @AntoinePlu @rayrutjes we remove it or not ?

**Comment by LukyVj** [comment]
Fixed in 9ffb23c
