### ISSUE TITLE
Update image SVG

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#314]
I saw we're using a different color in background, in that case, can we update the SVG image to avoid this bad contrast? 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3n0A3n0z1k33463r2q1J/Image%202016-09-29%20at%203.06.19%20PM.png?X-CloudApp-Visitor-Id=667340&v=6c866b58)

You can replace it by this one, I delete the tag background : 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2M42450I0Z1H2q3N0a26/facets-illus.svg)

**Comment by LukyVj** [comment]
Fixed in 	cd2d88b
