### ISSUE TITLE
Change "Algolia's infra and features" background

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#316]
Now that we delete the previous section designed at first, can we put back the right background color to have the original contrast between the BG and the feature's blocks ?

- [x] `background-color: #F3F4F7`
- [ ] Add Algolia logo in the missing block, `color: #697782`

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0C1R0l2S2z3L1s0Q1o3x/Image%202016-09-29%20at%203.09.55%20PM.png?X-CloudApp-Visitor-Id=667340&v=2a597f1b)

**Comment by LukyVj** [comment]
Is this suiting your wishes ? 
![](https://puu.sh/rrOe7/569292d49a.gif)

**Comment by AntoinePlu** [comment]
The logo doesn't seems totally aligned vertically, but however LGTM 👍

**Comment by LukyVj** [comment]
Ok, I'll investigate 
! thx

**Comment by LukyVj** [comment]
Fixed in 1e0f02c
