### ISSUE TITLE
Fix header fonts

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/algoliasearch-wordpress#317]
Hey guys,

Regarding the headline in the hero-banner, we're getting better than before !
But if I can, I would suggest few little changes to be like it's supposed to be.

- [x] Reduce margin-bottom on h1 to `margin-bottom: 0.3em;`
- [x] Add a max-width on the subtitle to `max-width: 420px;`
- [x] Change the font-weight on the subtitle to `font-weight: normal;`

BEFORE:
![](https://d3vv6lp55qjaqc.cloudfront.net/items/2A3h1I26412R3f0S232B/Screen%20Shot%202016-09-29%20at%2015.21.34.png?X-CloudApp-Visitor-Id=667340&v=5428f68a)

AFTER:
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3v1t311a1z1T02302I23/Screen%20Shot%202016-09-29%20at%2015.21.45.png?X-CloudApp-Visitor-Id=667340&v=858365e3)

**Comment by LukyVj** [comment]
lez do this

**Comment by LukyVj** [comment]
By the way. I like `max-width: 420px;` ;)

**Comment by LukyVj** [comment]
Fixed in c956739
