### ISSUE TITLE
Template locations

### ISSUE THREAD

**Issue by peiche** [algolia/algoliasearch-wordpress#326]
I'm a theme developer. The templates for instant search and autocomplete were simple to customize, but I would like to customize the location. I have the template files in `/algolia` per the documentation, but I'd prefer to have them in a location of my choosing. I imagine this could be accomplished through a filter, similar to how the plugin's stylesheets can be removed.

**Comment by rayrutjes** [comment]
Hi @peiche ,

Thanks for submitting the feature request,

This seems like a nice feature to have, let's implement it!

**Comment by rayrutjes** [comment]
Hi @peiche ,

Please stay tuned for the upcoming 1.3.0 release which will allow you to entirely customize the templates locations, see: #344.

I'd gladly assist you in the templates customization ;)

**Comment by rayrutjes** [comment]
@peiche please base your implementation on 1.3.0.

I also started a documentation for theme authors: https://community.algolia.com/wordpress/customize-templates.html

Let me know how you feel about it, I'd gladly add missing sections or improve the guide.
