### ISSUE TITLE
Make notifications filterable

### ISSUE THREAD

**Issue by diedexx** [algolia/algoliasearch-wordpress#328]
In my current setup I have a WordPress install which is using the algolia index of another install. I need autocomplete to be enabled, but I don't want to index, and thus overwrite, anything on the index it is using. (basically read-only.)

Since I have autocomplete enabled and haven't selected anything to index, the plugin tells me that I should at create one index via the plugin.
![posts_ _yoast_academy_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/18984720/653c3372-86f4-11e6-8c48-baf2f62f3bfb.png)

It'd be great if these notifications could be hidden with a filter, so I don't see them on every admin page.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.1.0

**Comment by rayrutjes** [comment]
Hi @diedexx ,

That makes a lot of sense, let's do this!

**Comment by rayrutjes** [comment]
@diedexx would it be enough if we add a constant allowing to disable all 'help' notifications?

**Comment by diedexx** [comment]
@rayrutjes  yes, that would work
