### ISSUE TITLE
jsInline minification shipped with CacheEnabler breaks the JS

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#346]

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by rayrutjes** [comment]
> Okay,

> looks like CacheEnabler has its own Regex Minifier which can break some JS codes, and even more

**Comment by rayrutjes** [comment]
@PeterDaveHello I found the issue, it was caused by the comments starting with  `//`, see 	81ce697

Stay tuned for the 1.3.0 release ;) Thank you again for finding this!

**Comment by PeterDaveHello** [comment]
Awesome, thanks @rayrutjes !
