### ISSUE TITLE
[Feature] Is it possible to add options for loading js/css assets from public CDN?

### ISSUE THREAD

**Issue by PeterDaveHello** [algolia/algoliasearch-wordpress#363]
As algoliasearch-wordpress can totally speed up the search speed (and also power it up), I wonder if you'll like to add options to let users allow load the plugin from CDN like @cdnjs, @jsdelivr or @unpkg ? For those individual bloggers, who don't have the powerful enough server and their own CDN, this can make this plugin been loaded n-times faster, what do you think?

**Comment by rayrutjes** [comment]
Hi @PeterDaveHello , thx for suggesting!

I think we could definitely allow people to switch to assets served from a CDN.

Let me flag this as a new feature to implement!

**Comment by rayrutjes** [comment]
In the end, we won't implement this because we don't want to push in favor of one or another CDN.

Also we think this can be achieved fairly easily by just registering your custom scripts pointing toward the CDN of your choice.

Maybe we could add some information about it in the documentation though.

Feel free to re-open if you think I missed something here.

**Comment by PeterDaveHello** [comment]
Thanks @rayrutjes, just one question, if the CDN option is disabled by default, and there is no default CDN provider but only the options, will there still be concerns about that? Actually, for most of the individual bloggers may not know how to make their own domain CDN enabled, this issue could be an easier way to do that, thanks again.

**Comment by rayrutjes** [comment]
Hmmm you mean providing several fields for putting the urls of CDN hosted scripts as alternatives to the local ones?

**Comment by PeterDaveHello** [comment]
I mean options like unpkg, jsdelivr & cdnjs, the URLs can be built-in :smile: maybe even combination of fields of putting the URLs like you say :+1:
