### ISSUE TITLE
Algolia search is pulling shortcodes into search

### ISSUE THREAD

**Issue by Melaluca** [algolia/algoliasearch-wordpress#365]
### What happened instead?

Using the Algolia wordpress plugin. Only issue is when you commence searching via a letter or two it brings up some page meta/short code

No cacheing plugin being used.
### How can we reproduce this behavior?

Demonstrated in this video here: https://www.opentest.co/share/6bb58c20893911e69225c7c933a8d325

Can you provide a link to a page which shows this issue?

saasjunkie.co/home

> > Then put the letter 'A' in the search filed and you will see what I mean. 
### Technical info
- WordPress version: Latest (4.6.1) Wordpress being used. Divi Theme (+ Child Theme) and Builder 3.0 being used.
- Algolia Search plugin version: Version 1.3.0

Thank you.

**Comment by rayrutjes** [comment]
Hi @Melaluca and thx for reporting this,

I've observed the same on other websites without having had the time yet to investigate.

String thing is that we are correctly applying the `the_content` filter before sending the post_content to Algolia, and it works for a lot of shortcodes.

Do you have an idea in your case why the shortcodes are not replace when we apply the `the_content` filter?

**Comment by Melaluca** [comment]
Elegant Themes (Divi Builder Owner) replied to my support ticket:

_____________
I see what you mean, i've afraid it can't be done any thing on this.
Divi contents has shortcodes on them and your search plugin is searching through its content where its finding the texts of the shortcodes.

I'm afraid in this case there's no option excerpt for disabling the suggestion sub content.

Thanks
_________________

Unsure what to do at this point. I cant use Algolia if the shortcodes are going to show up :(

Any help would be immensely appreciated.

Thanks in advance.

**Comment by rayrutjes** [comment]
@Melaluca is there any chance you could send us a copy of the theme you are using so that we can fix this issue? Please send it to support+wordpress@algolia.com

**Comment by Melaluca** [comment]
Have emailed as requested. Thanks in advance

**Comment by rayrutjes** [comment]
After investigation, it seems that this is kind of the same issue as #393 

Indeed, the Divi builder needs to be initialized prior to being able to replace shortcodes in the post content, and it does not seem to happen when only triggering the `the_content` filter.

Will try to compute something that works for bothe Visual Composer and Divi builder.

For the Divi builder, my guess is that we are going to need to use a solution that looks like this one: http://wordpress.stackexchange.com/questions/224964/why-do-shortcode-doesnt-work-in-a-rest-request

Stay tuned,

**Comment by rayrutjes** [comment]
We are still waiting for the support answer of Elegant Theme. Stay tuned.

**Comment by rayrutjes** [comment]
According to Elegant Theme, the Divi theme is greatly dependent on the frontend lifecycle and there is no easy way to replace shortcodes with the real content if it is not for rendering.

Unless Divi theme makes it easier for external plugins to register the shortcodes programatically, I see no easy way to resolve this issue.

Closing this for now, but I of course stay open to suggestions ;)

**Comment by hellohereiam** [comment]
My idea would be to add an option to your plugin to str_replace known shortcodes from popular builders such as divi builder. I know it would be better if this was taken care of from eleent themes side, but as they don't seeming to move on the issue, this might be a nice intermediate solution that should be fairly easy to integrate.

Best, T

**Comment by rayrutjes** [comment]
@hellohereiam that'd be awesome,

Feel free to submit a PR if you feel confortable doing so.

**Comment by hellohereiam** [comment]
@rayrutjes ok, I have added a simple regular expression here #494. This is tested on support.wrklst.com and seems to work fine. I don't think it is in conflict with anything else and could easily be extended to other visual builders.

I hope I did the whole PR thing correctly, as this was my first time creating a PR.

Let me know what you think.

**Comment by rayrutjes** [comment]
First off all thanks a lot for putting this together @hellohereiam !
The concern I have is that your solution removes the shortcodes but doesn't replace them with the actual content. This means that the underlying content doesn't get indexed and that is a big issue for users putting a lot of content behind Divi shortcodes.

Do you maybe have a clue on how we could replace those shortcodes with the actual content behind the shortcodes?

**Comment by hellohereiam** [comment]
I am not sure I understand. I have tried this and just getting rid of the short codes will still index the content. The short codes are encapsulating the textual content for styling, so the actual content text is still within the content and not referenced through shortcodes – or am I missing something? This is at least true for my test page at https://support.wrklst.com where I have the modified plugin running. 

Here is an example of content with short codes:
`[et_pb_something]Some content that should be indexed[/et_pb_something]`

With the regex replacer it would come out to:
`Some content that should be indexed`

Which is exactly what I would the Algolia plugin expect to index.

**Comment by peiche** [comment]
I'm trying to do something similar to exclude shortcodes for the [Aesop Story Engine](https://wordpress.org/plugins/aesop-story-engine/) plugin. I have thus far been unsuccessful. You can see it in action on my site, [eichefam.net](https://eichefam.net). All shortcodes in the plugin start with `aesop_`.

**Comment by tobiasvielmetter** [comment]
@peiche check #572. 

this should work
``
if(function_exists( 'et_pb_is_pagebuilder_used' )) {
           $noise_patterns[] = '/\[\/?aesop_.*?\]/';
        }
``

**Comment by peiche** [comment]
Apart from wrapping it in an if block, I tried that. It didn't work. Should I have to reindex first?

**Comment by tobiasvielmetter** [comment]
sorry, the if doesnt make any sense. that would need to look for a function that would only be available if the said plugin is active.

yes you will have to reindex after activating, since the regex is used at time of indexing.

**Comment by rayrutjes** [comment]
Actually, I think we need to find a more global solution because today I came across couple of website with some unescaped shortcodes as well.

**Comment by peiche** [comment]
After a reindex, I got it working. (Thanks @tobiasvielmetter!) I was going to submit a PR with my changes. @rayrutjes should I hold off?

**Comment by rayrutjes** [comment]
Well I'd gladly see the PR but I'm not sure we'll merge it. I think we need to remove all remaining shorcodes after the content was first parsed.
If we add a single regex rule for every shortcode out there, it will slow down the indexing a lot.

**Comment by tobiasvielmetter** [comment]
I agree, a general regex for all shortcodes after the_content filter would be preferrable, as shortcodes are never useful in the index.
