### ISSUE TITLE
Bundle js libraries to avoid conflicts

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#372]
In some cases, autocomplete.js library will conflict with other libraries because they both register the same variable on the `window`: `autocomplete`.

We should provide with a way to encapsulate the libraries while still being able to take the benefits of WordPress assets enqueing system.

**Comment by sliday** [comment]
Sample page: http://studyaway.ru/map My understanding it's https://wordpress.org/plugins/wp-google-maps/ who's messing with window.autocomplete

**Comment by rayrutjes** [comment]
Thx @sliday for adding a concrete example. Will try to find a solution ASAP.

**Comment by KZeni** [comment]
+1. This is conflicting with the WP Google Maps plugin for me, too.

**Comment by rayrutjes** [comment]
A fix for this has just been merged: #465 
Will be released under 1.7.0 tag.
