### ISSUE TITLE
Add indexing troubleshooting section

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#373]
We should add a section dealing with all the common issues and how to fix them, including but not limited to:
- Memory limit => https://wordpress.org/support/topic/index-error-algolia/
- SSL problem => disable ssl check if certificate is not valid

**Comment by enikolov15** [comment]
Hi Rayrutjes,
Talking for the indexing issues, how can I add a database table of a WP pluging like wpForo to be indexed by algolia? So that algolia will show results from our forum posts?

Also is there any way to limit the search results to not show password-protected pages if not logged-in (pages that require login)?
Our website with algolia: http://glue42.com/
Best regards,
Emil

**Comment by rayrutjes** [comment]
Hi @enikolov15 
This plugin is intended for getting you up and running quickly by indexing the post types.

If you want to go further and do a custom implementation, you could directly use the [PHP API Client](https://github.com/algolia/algoliasearch-client-php).

In the plugin, by default, according to [this part](https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/indices/class-algolia-searchable-posts-index.php#L70), we do not index password protected pages.

I'd gladly hear more about how you want to use Algolia to see wether this plugin is a good fit or if you'd better be off using the API Client directly.

**Comment by enikolov15** [comment]
Thank you, Rayrutjes!
For the first I will ask for a dev to implement it (I'm just a product manager).
For the "not index password protected pages" - in our case it indexed them. I deleted the pages index and reindexed everything and algolia by default is showing again content from password protected pages (of course when one tries opening the page he is asked to login). Please see a screenshot of the issue: https://postimg.org/image/mdnje3ss1/

**Comment by rayrutjes** [comment]
@enikolov15 
I opened an issue [here](https://github.com/algolia/algoliasearch-wordpress/issues/490) to make sure we don't index those pages.

Did your developer already use some custom filters we provide that would explain that those pages gets indexed?

Tell your developer to not hesitate to reach out to find the easiest way to couple the website to Algolia.

**Comment by rayrutjes** [comment]
This is no longer required since we remove the local queue.
