### ISSUE TITLE
Copying autocomplete.php into custom theme has it generate code on every page

### ISSUE THREAD

**Issue by jon-heller** [algolia/algoliasearch-wordpress#379]
I followed the the [instructions](https://community.algolia.com/wordpress/customize-autocomplete.html) to customize autocomplete:

> To start customizing your dropdown menu, copy/paste the wp-content/plugins/algolia/templates directory in your own theme, and rename it to algolia. If your theme is named mytheme, then the folder should look like: wp-content/themes/mytheme/algolia.
> 
> You can then edit the algolia/autocomplete.php file to customize the autocomplete dropdown menu (suggestions, header, footer) templates & associated JavaScript code.

However, doing so appears to make all of the code in autocomplete.php inserted into the body of every page on our site, not just the search page.

While this doesn't appear to effect any rendering if our content, it's not ideal for a performance standpoint.

**Comment by rayrutjes** [comment]
Hi Jon,

We actually inject the content for the autocomplete in every footer of every page.

This is because the autocomplete dropdown menu will be attached to every detected input.

This could of course be optimized by extracting the content into a static javascript file, but this would also make it harder to customize for everyone. Feel free to do so though.

Feel free to suggest a better approach to this.

**Comment by jon-heller** [comment]
Thanks for the info! What about only having the autocomplete injected if a input exists on the page that matches one of the Algolia classes or IDs? That way it wouldn't be added to page that don't have some kind of Algolia search interaction.

**Comment by rayrutjes** [comment]
That is a nice idea but that would mean to parse the whole dom page to eventually load js + html.
This sounds a bit error prone.

That being said, we could introduce a hook that allows you to run your own logic to inject or not the autocomplete in the footer. Not sure how useful this will be though as most people use the dropdown on every page.

You could also copy paste the autocomplete.php in your theme folder and then do your own check inside it.

**Comment by jon-heller** [comment]
I didn't realize most people used the code on every page. I can see how that would be the most common use case though. So unless this becomes a more common request, just having us write conditional logic to display it makes sense. Thanks!

**Comment by rayrutjes** [comment]
You are welcome @jon-heller . Don't hesitate to ping us if you have anything else to discuss.
