### ISSUE TITLE
Woo Theme

### ISSUE THREAD

**Issue by k1raoufi** [algolia/algoliasearch-wordpress#38]
Does the woo theme only work when instant search is on? Every time I turn instant search off, search results show in a blog format and not the way displayed on the woo theme image.

**Comment by maxiloc** [comment]
When instant search is off you will have an autocomplete menu (if enable). And on the search page you will have the results formated by wordpress but fetch from algolia instead of your db to allow typo tolerance and all other algolia features

Is the autocomplete not working?

**Comment by k1raoufi** [comment]
Autocomplete is working great. 

I guess the confusion was that I was expecting/hoping the search results would show up similar to when instant search is on since I had selected Woo as the theme. 

The reason I removed instant search is because when it was on, the styling of my site would change. Easy fix was to turn it off.

**Comment by maxiloc** [comment]
Yes we provide an default implementation of instant search including js logic and css. As you can imagine, we cannot integrate correctly to every wordpress theme, so yes there a little css work to do. 

 You are right maybe theme is not the appropriate word. We'll work on that to make it clearer.
