### ISSUE TITLE
More than 500 sync-item created when save a post

### ISSUE THREAD

**Issue by yann-kelcible** [algolia/algoliasearch-wordpress#380]
### What did you expect to happen?

I've got a WP with algolia search plugin.

When I save a custom post-type named "indicator",  the save work and the sync is sent to Algolia.

The site have actually an htaccess protection for develop process.

### What happened instead?

When I save a custom post-type named "indicator", more than 500 private post named "sync-item" was created with the post-type "indicator" and the original save go the a white page.

Example of content : 
`{"index_id":"searchable_posts","post_id":242684,"post_type":"indicator"}`

What is the exact role of this post ? Should it disappear? 

Actually, I have les than 20 real post with post-type "indicator" but more than 230.000 private post named "sync-item" with post-type "indicator"

### How can we reproduce this behavior?

No idea, perhaps the htaccess protection ?
I should give you an access if you don't understand my issue !

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version:  0.6.2
* Algolia ID : VHGVWP9DUA

**Comment by rayrutjes** [comment]
Hi @yann-kelcible 

By default, we listen for changes on post types so that we can reflect the changes in Algolia.

Very "sync-item" reflects one change requiring an update for the object.

Are you indexing your custom post type?

**Comment by yann-kelcible** [comment]
Hi,
I understand the purpose of this sync item, but why when I save a post
(custom post-type indicator) more than 500 sync item is generated ? And why
they don't disappear ?

I suppose of my htaccess ? But the same thing happens without !

Thanks

Yann

Le mardi 18 octobre 2016, Raymond Rutjes <notifications@github.com> a
écrit :

**Comment by yann-kelcible** [comment]
This also happens on other custom post types and on standard (post)

on standard post, I edit one and save.  4336 sync-item is created !

**Comment by rayrutjes** [comment]
@yann-kelcible what you are describing is definitely not OK :/

Please upgrade your extension to the latest, 1.3.0 version.

To do so, you should totally uninstall the currently installed plugin.

Then you can install the new one directly from the `plugins` admin page of your wordpress instance.

I bet you are using post-type switcher plugin, which produces infinite loops. This has been fixed in latests releases.

Let me know how it goes ;)

**Comment by yann-kelcible** [comment]
Thank you @rayrutjes, I will try tomorrow !

**Comment by rayrutjes** [comment]
Sounds good @yann-kelcible , I'm closing this for now because I'm pretty sure it will fix the infinite loop issue.

That being said, if you have another issue, please open a new issue, happy to help ;)
