### ISSUE TITLE
Add ability to re-index a single index

### ISSUE THREAD

**Issue by Mamaduka** [algolia/algoliasearch-wordpress#384]
Current UX to achieve this result is confusing. Most user probably will re-index everything, which isn't really a good option based on your data size.

Another not so straightforward way to get same result is following:
- Remove indice from the indices list.
- Re-add indice and trigger index queue.

P.S. It would be nice to have similar feature in WP-CLI command: `wp algolia process-queue <indice-name>`.

**Comment by rayrutjes** [comment]
This is indeed a nice feature to implement. Feel free to submit a PR if you have time. Otherwise we will implement it in future releases.

Regarding the UI, for now we will keep it as his because at some point we will need to refactor it a bit.

**Comment by Mamaduka** [comment]
@rayrutjes should have some free time during the weekend and gonna work on PR.

**Comment by rayrutjes** [comment]
That'd be awesome @Mamaduka , let me know if there is anything I can help you with.
