### ISSUE TITLE
Can't use Restricted keys

### ISSUE THREAD

**Issue by SiR-DanieL** [algolia/algoliasearch-wordpress#387]
### What did you expect to happen?

By using generated restricted keys the plugin should be able to authenticate and work as if I was using the master Search-Only and Admin keys
### What happened instead?

Using a `search` key and another one with all the other permissions as Admin key, the plugin returns this error:

![](http://cld.wthms.co/16gPu/1DOpgr96+)

> Can you provide a link to a page which shows this issue?

No sorry
### Technical info
- WordPress version: 4.6.1
- Algolia Search plugin version: 1.3.0

**Comment by rayrutjes** [comment]
Hi @SiR-DanieL ,

To validate the admin API key, we do a call to the listIndices API endpoint. If this call fails, then the API key is rejected. What are the current scopes attached to your admin API key?

**Comment by SiR-DanieL** [comment]
Hi @rayrutjes,
These are the permissions for the keys that I'm using:

![](http://cld.wthms.co/UnnU/d50sRWm9+)

The first is used for the Search-Only field, the second as admin key.

**Comment by rayrutjes** [comment]
Thanks for reporting this, will re-produce it and fix it.

Still a bit confused because it should work given that the listIndexes scope is there. I'm probably missing something ;)

**Comment by rayrutjes** [comment]
Hey @SiR-DanieL , 

I just merged a fix for your issue.

It will be made available as part of 1.4 release which will be there ASAP.

You will need to add the `deleteIndex` ACL to your key though because the plugin is able to cleanup the indices when no longer needed.

I'm closing this for now, feel free to open a new issue anytime, and thanks again for submitting!

**Comment by rayrutjes** [comment]
@SiR-DanieL 1.4.0 is out, please update ;)

**Comment by SiR-DanieL** [comment]
Thank you! I'll update ASAP!

**Comment by rayrutjes** [comment]
@SiR-DanieL Please upgrade to 1.4.1 because in 1.4.0 only user generated keys work...
