### ISSUE TITLE
Japanese language files

### ISSUE THREAD

**Issue by plastikdreams** [algolia/algoliasearch-wordpress#389]
Hello team.

I created Japanese language file for this plugin for Japanese users.
I hope you like them.

Could you teach me what branch do I send pull request?

thanks.

**Comment by plastikdreams** [comment]
I guess send  PR to the master branch is ok .
https://github.com/algolia/algoliasearch-wordpress/pull/381
I'll create PR soon

**Comment by rayrutjes** [comment]
Wow, thanks a lot!

We will review this ASAP!

I'm closing this in favor of your PR #390
