### ISSUE TITLE
[Support] How to perform a custom query

### ISSUE THREAD

**Issue by solepixel** [algolia/algoliasearch-wordpress#394]
I have an existing site that I'm using a custom WP_Query to retrieve posts based on a series of inputs from the user that are passed into a custom meta_query. The retrieval has become sluggish so I'm trying to move over to Algolia. I have setup my index in Algolia and pushed all the custom fields I need to filter into the filter, attaching them to the post object.

My question is how can I use the code from the WordPress plugin to perform a custom facet search? I've read the documentation on searching indexes, but I can't figure out how to connect the dots between a custom application and using the WordPress plugin. I'd like to use the index and the stored credentials in WordPress, but build my own search function to retrieve the Posts I'm looking for. Is that possible?

2nd part: I need to pull the unique facets from Algolia to display on the site front-end. Can that be done as well? For example, I'm storing "city" as a facet in Algolia. If I wanted to create a dropdown list with all the available (distinct) cities that are stored, how can I get such a list?

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.3.0

**Comment by rayrutjes** [comment]
Hi @solepixel , thanks for opening this issue.

I'd gladly give you some guidance to implement your search, and in that regard I would need to better understand how your current data is structured.

1. Are your cities stored under a custom post type? Or are they part of a custom taxonomy?
1. Then you would like to be able to display a search of a give post type, that can be filtered on the cities facet?
1. Could you give me more context about the `cities` dropdown you are thinking of? How about customizing the default instantsearch.js experience shipped with the plugin like explained here: https://community.algolia.com/wordpress/customize-search-page.html

Regarding searching in facet values, this is a brand new feature of the Algolia API which I did not have the time to play with myself yet ;)
I would love to try it out though, could you let me know what would be the purpose of searching for the cities in your case? Please note that the feature is not available at the time of writing this for all our users, so don't expect it to be available right away.

Looking forward to help you further!

**Comment by solepixel** [comment]
1. This is what my index looks like: http://3cd.co/1z1E2A1k3L0a - They are stored using the `algolia_post_{$post_type}_shared_attributes` filter. In WordPress the data is stored as post meta to a custom post type. The facet(s) I'd like to use are not stored as separate custom post types, they are attached to a custom post type via post meta.

2. Yes, but obviously it could be more complicated that just using 1 facet. My search is currently setup to use many facets to filter search results.

3. My site doesn't really use **any** text searching, but works completely with filtering. So I would like for the user to pick from a list of cities to ensure an identical match. In order to generate an accurate list of cities, I'll need to pull all the unique values from the index, currently I'm pulling these values from post meta. Here's a demo of how the search works: http://3cd.co/050f0k1g1j3j - So as you can see, I'm not actually searching by a term or phrase.

I'm not really looking to customize any of the front end or instant searching built into the plugin. I'm trying to figure out how to write my own code to hit the api to get the posts that match the search criteria. I when I say search, I really mean narrowed down results by filters. Please let me know if I need to clarify any further. Thanks for your help!

**Comment by rayrutjes** [comment]
Thanks for sharing the example links, those helped understanding your use case.

Basically you need to add your facets as attributesForFaceting in the settings of your index by using the settings hook explained here: https://community.algolia.com/wordpress/indexing-settings.html

Then, you will have to wait for the new "search In Facets" feature which is exactly what you will need to finish your search experience.

In the end you will have only 1 index containing your search results with associated meta fields, but you'll be able to search in the facets and contextually filter other facets based on your current refinements.

**Comment by solepixel** [comment]
Ok, I think I understand what I need to do to get my results, but my question is how do I connect to Algolia from my theme using the functionality in the Algolia plugin?

**Comment by solepixel** [comment]
The code I've tried looks like:
`
$algolia = Algolia_Plugin::get_instance();
$index = $algolia->get_index( 'wp_posts_cpt' );
$query = $index->search( 'status:Active AND class:1' );
`

But that code doesn't work. `get_index` returns null.

**Comment by rayrutjes** [comment]
@solepixel could you send a mail to support+wordpress@algolia.com so that we can better help you achieving your goal?

Also, I still think that you will need to wait for the 'search un facets' feature to be able to achieve what you want.

And just to clarify, in the above snippet, you don't need to specify the index prefix when using the plugin's `get_index` method.

If you want to directly deal with the client you could also do:

```php
<?php
$algolia = Algolia_Plugin::get_instance();
$index = $algolia->get_api()->get_client()->initIndex( 'wp_posts_cpt' );
/*Etc*/
```

To be able to filter on facets from the backend, please checkout: https://www.algolia.com/doc/api-client/php/search#search-parameters

You have to use the second parameter of the `search` method and pass the facets there.

I'm closing this issue for now and I'm waiting for your support mail to continue this discussion which is more related to the PHP Client than the Algolia WordPress plugin ;)
