### ISSUE TITLE
[Algolia Search plugin for WordPress Installation] Foodie Pro Theme Conflict

### ISSUE THREAD

**Issue by dfhemenway** [algolia/algoliasearch-wordpress#418]
### What did you expect to happen?
I have a WordPress site running the Foodie Pro theme from StudioPress, running on their Genesis Framework. I installed your search function and it works pretty well. I used the "background" setting for how it works with my WordPress installation. The display is completely fine on a Windows desktop in a variety of browsers (Chrome, IE, MS Edge, Safari, and Firefox) at full width. 

### What happened instead?

Where I've seen a problem is in responsive/mobile mode. On my phone (iPhone running Safari and Chrome browsers), or on a desktop browser with the width made very narrow, the mobile menu "hamburger" icon disappears on the home page, but displays on all the other pages. 

### How can we reproduce this behavior?

Just go to my site and play with the home page vs. the subsidiary pages on a narrowed desktop browser or phone browser: http://food-and-drink.somaryland.com.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.4.1

**Comment by rayrutjes** [comment]
Hi @dfhemenway ,

Thanks for submitting this.

Do you mind adding some screenshots, not sure what to look for.

Also, is this issue related to the Algolia plugin?

**Comment by dfhemenway** [comment]
Hi,

It is related to the Algolia plugin, as the problem only started after the
plugin was installed. If I deactivate the plugin, the problem goes away.

I've got a dual-screen setup, so the screenshots can be awkward to copy and
paste here, but I'll make a Word document with them to attach; that way,
you should be able to see them clearly.

Don
[algolial menu problem screenshots.docx](https://github.com/algolia/algoliasearch-wordpress/files/596112/algolial.menu.problem.screenshots.docx)

**Comment by rayrutjes** [comment]
I suppose you pasted the image in your Word doc, you can also paste it directly in here ;)

**Comment by dfhemenway** [comment]
You suppose correctly. Are you trying to say you have a problem with the
Word file?

**Comment by rayrutjes** [comment]
Heuh, yes because I got now way to easily open it on my laptop ;)

But also because if you paste it directly in the issue it makes it easier for everyone to see it and contribute.

**Comment by dfhemenway** [comment]
I tried responding directly to this email address yesterday and it bounced,
so I went to Github and put my reply there. I wasn't sure about pasting
options, so had put everything in a Word document. I'll try and copy those
items to this email and sending it again:

*Algolial Search, menu problem screenshots*



Normal, full-width page with menu (Home, About Us, Articles, etc.) in the
yellow band across the top:






[image: Inline image 1]



Narrow page, as a phone will see it, with menu not displayed on home page.
It should be in the blank white area between the header image and the title
“Recent Articles”:


[image: Inline image 3]





Narrow interior page, showing the 1) hamburger icon for menu, and then 2)
with the menu open:



[image: Inline image 4] [image: Inline image 5]





And, finally, here’s what the home page looks like with the Algolia plugin
deactivated. The hamburger menu icon reappears:


[image: Inline image 6]

Don

**Comment by rayrutjes** [comment]
Hey Don,

Sorry to insist here but we still haven't access to the screenshots.

Speak to you soon!

**Comment by dfhemenway** [comment]
I pasted the screenshots into the email I sent you Thursday, and which I
copied these other 2 people on today. I also sent them to you in a Word
document before that. If you want me to fax or snail mail them to you, I
can do that, too. I can put them into a PDF and send it. I can make copies
of them and put them onto pages on one of my websites and send you a link.
You want me to share my screen with you in a Google Hangout, I can do that,
too.

Why haven't you specified the best way to send something? Why didn't you
tell me you hadn't received the screenshots again? Or maybe you never got
my email from Thursday? I'm not a mind reader, sorry to say. Your
colleagues are offering to help and I've asked for help and sent
screenshots 3 times now. I'm frustrated -- what more/else can I do to get a
resolution?

On Mon, Nov 21, 2016 at 8:40 PM Raymond Rutjes <notifications@github.com>
wrote:

Hey Don,

Sorry to insist here but we still haven't access to the screenshots.

Speak to you soon!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/algolia/algoliasearch-wordpress/issues/418#issuecomment-262123002>,
or mute the thread

**Comment by rayrutjes** [comment]
Hi @dfhemenway ,

I just found some time to take a closer look at your theme.

It looks like the burger icon gets displayed with JavaScript.

My guess is that there is some kind of error going on when Algolia is enabled.

Could you re-enable it so that I can check on the errors?
Otherwise could you report the JS errors you have in your console?

Thanks in advance

**Comment by dfhemenway** [comment]
Hi,

I have re-enabled it. Here is what I found in the console:

JQMIGRATE: Migrate is installed, version 1.4.1load-scripts.php:9:542
JQMIGRATE: Migrate is installed, version 1.4.1load-scripts.php:9:542
JQMIGRATE: Migrate is installed, version 1.4.1jquery-migrate.min.js:2:542
JQMIGRATE: Migrate is installed, version 1.4.1jquery-migrate.min.js:2:542
TypeError: autocomplete.sources is undefined
[Learn More]food-and-drink.somaryland.com:488:5
ReferenceError: ytcfg is not defined
[Learn More]1WOLz7VEKfw:10:22
‘mozHidden’ and ‘mozVisibilityState’ are deprecated.  Please use the
unprefixed ‘hidden’ and ‘visibilityState’
instead.www-embed-player.js:653:291

Don

**Comment by dfhemenway** [comment]
By the way, I'm still running Algolia version 1.4.1, but there is a notice
in the WP dashboard that version 1.5.0 is available.

**Comment by rayrutjes** [comment]
Can you tell if your theme includes a call to `wp_footer()` ?
I think that it might be the issue.

**Comment by dfhemenway** [comment]
I don't know if it calls for that. Frankly, I'm not sure where to look for
it. But I will pass that question back to the tech-support person at the
Theme shop.

I'm using a child theme, so I suppose it could also be in the original
framework. The theme is called Foodie Pro, and it works within the Genesis
Framework from StudioPress.com.

Don

**Comment by rayrutjes** [comment]
Ok, thanks a lot for your patience. I hope we get some insight from the Theme author.

**Comment by dfhemenway** [comment]
Hi,

Unfortunately, I've not heard back from the Theme's tech support here as of
4:12 PM Eastern Standard Time in the U.S. I'm not sure where you are, but
your IO domain would indicate you're probably outside the U.S. Given that,
you may not know that tomorrow is a national holiday here, and many
businesses will be closed from now through Sunday, so the odds are I won't
hear anything until next Monday. If I hear something before then, though,
I'll be sure to pass it along.

Don

**Comment by dfhemenway** [comment]
I finally heard back from the theme developer. Here is what she wrote:

"Genesis themes use a different set of hooks. Here's some more information
on that: http://wpsites.net/web-design/hooks-in-custom-functions/"

**Comment by rayrutjes** [comment]
Interesting @dfhemenway 

So if I understand it correctly, they might not be using the standard wp_footer hook but their custom one.

Could you send me a copy of your theme folder as an archive at support@algolia.com by mentioning my handle @rayrutjes? That way I'm able to confirm the statement and eventually let you know what you could adapt to make it work.

Sorry for the inconvenience here, not sure yet if the plugin is supposed to support this kind of use case.

**Comment by dfhemenway** [comment]
Sorry, but I'm not comfortable sending you a copy of the Theme, given I
paid for a license for it and it is their Intellectual Property, not mine.
I'm ok with given you Admin Access to my site, and even FTP access, if
those types of things help.

**Comment by rayrutjes** [comment]
I don't think they will complain if we help them doing support on their theme ;)
BTW we won't put it to production, so it won't be an issue ;)

Without accessing the theme files, I'm afraid I won't be much of a help :/

**Comment by dfhemenway** [comment]
Nevermind. Your help is no longer needed, as the function is working ok
now. I think it may be due to changes made by tech-support from WP Google
Maps. Their plugin stopped working when yours was installed. I gave them
Admin access and they went into it and got it working again. They said:
"It appears the developers overlooked a few runtime checks which are
causing conflicts. I have resolved this for you and it should now work as
intended."
Of course, when/if you or they make changes, things may break again. I'll
just have to keep an eye on it.

**Comment by rayrutjes** [comment]
Thanks for the feedback @dfhemenway , Do you mind posting the missing "runtime checks" here so that other users can benefit from it?

Best

**Comment by dfhemenway** [comment]
I wouldn't mind but I don't know what to post. I told you what they told
me.

**Comment by rayrutjes** [comment]
Is there any chance you ask them what they changed to make it work?

**Comment by dfhemenway** [comment]
I'll ask.

**Comment by dfhemenway** [comment]
Raymond,

Here's what I got back from the folks at WP Google Maps:

Hi Don,

Only a pleasure, so glad to hear this helped!

I am happy to provide you with the checks/changes I made.

As mentioned earlier there was a 'hits' is undefined error showing up in
the console. This was due to the function they are trying to call (within
JavaScript) not being available/ready.

I resolved this by wrapping the following:

sources.push({
   //Relevant initialization code here
});


In a check as seen here:


if(typeof autocomplete === &#039;undefined&#039; &amp;&amp;  typeof
autocomplete.sources !== &#039;undefined&#039; &amp;&amp; typeof
autocomplete.sources.hits !== &#039;undefined&#039;){
  sources.push({
     //Relevant initialization code here
  });
}


This prevents the code from running in the event that the function is not
defined. This is good practice within JavaScript to prevent conflicts such
as the one we had seen earlier.

Additionally, to prevent any further conflict (in the event that 'hits' is
undefined) I also wrapped the segment of code seen just below the above
mentioned code:

jQuery(&quot;input[name=&#039;s&#039;]:not(&#039;.no-
autocomplete&#039;)&quot;).each(function(i) {
   //Relevant runtime code here
});


With a simple check as seen below:

if(typeof autocomplete === &#039;function&#039;){
  jQuery(&quot;input[name=&#039;s&#039;]:not(&#039;.no-
autocomplete&#039;)&quot;).each(function(i) {
    //Relevant runtime code here
  });
}


Although this will prevent the code from running if autocomplete is not a
function, this should still be done to prevent any conflicts.

The plugin developer needs to simply ensure that the variable/functions are
defined prior to them being used and the functionality will continue as
expected.

I hope this helps?

**Comment by rayrutjes** [comment]
Thanks @dfhemenway for getting this info back to us.
We are going to make sure we add the checks in the upcoming release.

**Comment by dfhemenway** [comment]
You are very welcome. I'm glad it will be of help.

**Comment by rayrutjes** [comment]
This should be fixed in #465 
Thanks again @dfhemenway

**Comment by dfhemenway** [comment]
I stopped using Algolia weeks ago. Please take me off your email list.
