### ISSUE TITLE
Algolia for Wordpress - How do I change the index to query?

### ISSUE THREAD

**Issue by jmkulakowski** [algolia/algoliasearch-wordpress#422]
### What did you expect to happen?
I've duplicated instantsearch.php and I've made some changes to the facets.  Now I'm trying to setup different results in the search for users with various WP Roles - i.e admin, author, editor, etc. 

My base index is searchable_posts and I've created a replica entitled americas_only. I've also set up a facet filter so that the replica index only shows certain results (from the region, Americas).  Now, I'm trying to query the replica index in instantsearch.php template and I can't seem to get it to work.  This is what I have right now and it's working to query the searchable posts:

`<script type="text/javascript">
	jQuery(function() {
		if(jQuery('#algolia-search-box').length > 0) {

			if (algolia.indices.searchable_posts === undefined && jQuery('.admin-bar').length > 0) {
				alert('It looks like you haven\'t indexed the searchable posts index. Please head to the Indexing page of the Algolia Search plugin and index it.');
			}

			/* Instantiate instantsearch.js */
			var search = instantsearch({
				appId: algolia.application_id,
				apiKey: algolia.search_api_key,
				indexName: algolia.indices.posts_submissions.name,
				urlSync: {
					mapping: {'q': 's'},
					trackedParameters: ['query']
				},
				searchParameters: {
					facetingAfterDistinct: true
				},
				searchFunction: function(helper) {
					/* helper does a setPage(0) on almost every method call */
					/* see https://github.com/algolia/algoliasearch-helper-js/blob/7d9917135d4192bfbba1827fd9fbcfef61b8dd69/src/algoliasearch.helper.js#L645 */
					/* and https://github.com/algolia/algoliasearch-helper-js/issues/121 */
					var savedPage = helper.state.page;
					if (search.helper.state.query === '') {
						search.helper.setQueryParameter('distinct', false);
						search.helper.setQueryParameter('filters', 'record_index=0');
					} else {
						search.helper.setQueryParameter('distinct', true);
						search.helper.setQueryParameter('filters', '');
					}
					search.helper.setPage(savedPage);
					helper.search();
				}
			});

			/* Search box widget */
			search.addWidget(
				instantsearch.widgets.searchBox({
					container: '#algolia-search-box',
					placeholder: 'Search for...',
					wrapInput: false,
					poweredBy: algolia.powered_by_disabled
				})
			);

			/* Stats widget */
			search.addWidget(
				instantsearch.widgets.stats({
					container: '#algolia-stats'
				})
			);

			/* Hits widget */
			search.addWidget(
				instantsearch.widgets.hits({
					container: '#algolia-hits',
					hitsPerPage: 10,
					templates: {
						empty: 'No results were found for "<strong>{{query}}</strong>".',
						item: wp.template('instantsearch-hit')
					},
				})
			);

			/* Pagination widget */
			search.addWidget(
				instantsearch.widgets.pagination({
					container: '#algolia-pagination'
				})
			);

			/* Region refinement widget */
			search.addWidget(
				instantsearch.widgets.menu({
					container: '#facet-org-region',
					attributeName: 'organisation_region',
					sortBy: ['isRefined:desc', 'count:desc', 'name:asc'],
					limit: 10,
					templates: {
						header: '<h3 class="widgettitle">Region</h3>'
					}
				})
			);

			/* Start */
			search.start();

			jQuery('#algolia-search-box input').attr('type', 'search').select();
		}
	});
</script>`

I thought I'd be able to change the submissions index to my new slave like so, but it's not working:
`var search = instantsearch({
	appId: algolia.application_id,
	apiKey: algolia.search_api_key,
	indexName: algolia.indices.americas_only,
	urlSync: {
		mapping: {'q': 's'},
		trackedParameters: ['query']
	},`

### What happened instead?
I'm receiving a console error - "Cannot read property 'name' of undefined"

### How can we reproduce this behavior?
It should be easy to reproduce.  I simply want to change the queried index using the base WP template that comes with the Algolia WP Plugin.

Can you provide a link to a page which shows this issue?
Not at the moment, because the information is private.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.3.0

**Comment by rayrutjes** [comment]
Hi @jmkulakowski 

That is an interesting use case you have there!

Please note that Replicas might not be the correct feature to leverage here.
Indeed replicas are best used when you are dealing with the same records but you only want to change the ranking. It is ideal for sorting on a given attribute like explained here: https://community.algolia.com/wordpress/replicas.html

In your case, you will probably need to create different indices scoped to the records you want to make accessible.

Or you could also use filters to narrow down the results.

Does your implementation imply some security considerations or is it just a UX matter?

Looking forward to help you more,

**Comment by jmkulakowski** [comment]
@rayrutjes Thanks for your help!  Indeed, I'm not sure replicas would be the best approach.  Actually, I was able to set up a workaround for now by adding a WP hook that adds the user role slug to the body of the document.  Then, based on the current user, I wrote a script to only show results for that user:

	/** 
	 * If user has WP role "americas", only print results from
	 * Americas and the Caribbean
	 */
	if( jQuery('body').hasClass('americas') && orgRegion == 'Americas and the Caribbean' ) { #>

		<article itemtype="http://schema.org/Article">

			<div class="ais-hits--content">
				<h3 itemprop="name headline"><a href="{{ data.permalink }}" title="{{ data.post_title }}" itemprop="url">{{{ data._highlightResult.post_title.value }}}</a></h3>
				<div class="ais-hits--tags">
					<# for (var index in data.taxonomies.post_tag) { #>
					<span class="ais-hits--tag">{{{ data._highlightResult.taxonomies.post_tag[index].value }}}</span>
					<# } #>
				</div>
				<div class="excerpt">
					<p>
						{{{ data._snippetResult.aim_of_organisations_work.value }}}...
					</p>
					<p class="text-small org-region">{{{ data._snippetResult.organisation_region.value }}}</p>
				</div>
			</div>
			<div class="ais-clearfix"></div>
		</article>	
	}

This is definitely not the most elegant solution, but its working.  The only issue I have now is that I can't seem to target the facets for regions, so all of the regions are showing up.  Also, I've had to extend the search results to hundreds to make sure that some of the posts in each particular region show up because I'm still querying the full index.

@rayrutjes To answer your question: Yes!  There is a security issue here.  I'm trying to make sure that users have limited access to certain posts within their regions.  They should not be able to see or edit posts outside of the region they've been assigned.  

Thanks again for your help.  any advice would certainly be welcomed. :)

**Comment by rayrutjes** [comment]
Regarding security best practices, please find an extended guide here: https://www.algolia.com/doc/guides/security/best-security-practices/#guides

Regarding the features your are trying to implement, unfortunately it is out of scope of the current plugin.
