### ISSUE TITLE
Add filter to customize records and settings

### ISSUE THREAD

**Issue by deepankarpathak** [algolia/algoliasearch-wordpress#43]
We can only add attributes in algolia, is there any way by which we can have custom attribute pulled into system for indexing and searching?

**Comment by maxiloc** [comment]
For now you need to modify the extension if the attribute is not stored in the meta table. But I am planning to add filters to handle it from the wordpress theme.

**Comment by deepankarpathak** [comment]
Any expected date for this enhancement in Algolia?

**Comment by maxiloc** [comment]
Should be available for the 1.0 release by the end of the week

**Comment by KogtaSaloni** [comment]
Will it also include SEO keyword description(YOAST)? So that we can directly use those keywords with Algolia.

**Comment by maxiloc** [comment]
@KogtaSaloni Yes you will be able to add every attributes you want

**Comment by deepankarpathak** [comment]
Made the suggested changes still not working.

**Comment by maxiloc** [comment]
@deepankarpathak You should update the plugin entirely not just a commit (Be careful, we are still on the develop branch). After that you can check https://github.com/algolia/algoliasearch-wordpress/tree/develop#add-some-attributes-to-a-record
