### ISSUE TITLE
Add a way to exclude records from being indexed

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-wordpress#44]

**Comment by deepankarpathak** [comment]
@maxiloc - Any update on this?

**Comment by maxiloc** [comment]
Not yet

**Comment by rayrutjes** [comment]
Hi @deepankarpathak, we are actively working on a new release so allow me to dig up this issue.

Could you maybe tell us a bit more about your use case?

In the new upcoming release you will be able to define your own conditions by adding a WordPress filter. Would that solve your issue?

**Comment by rentageekmom** [comment]
I can contribute my own thoughts here, if it helps. I was just searching for a way to do the same thing; we have pages and posts on a site that we don't necessarily want users to find through our site search. Ideally, we'd be able to exclude those (for example, older content, certain products, or non-navigable links used for other campaigns or social media)

**Comment by rayrutjes** [comment]
Thank you for your feedback @rentageekmom. We will definitely try to integrate this feature in the future release!

**Comment by rayrutjes** [comment]
Hi @rentageekmom, excluding items from the indexing process is now do-able in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

Here you have an example about excluding a specific item from the index: https://community.algolia.com/wordpress/indexing-flow.html#indexing-decision

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
