### ISSUE TITLE
See if there is way around using wp_footer

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#443]
Some themes do not use the `wp_footer` function.
We currently rely on that for injecting templates and other things.

We should probably try to find an alternative to not break themes that do not use `wp_footer`.

At least we should add it to the future system status  page #310

**Comment by royduin** [comment]
I've experienced the same with Roots Sage: https://github.com/roots/sage, so I've copied the `instantsearch.php` file to `algolia/instantsearch.php` in my theme and removed the `get_header()` and `get_footer()` functions.

**Comment by rayrutjes** [comment]
Currently we inject the "algolia" variable holding all the config in the footer. We also inject autocomplete templates in the footer. We could probably try to make thos injected in the head somehow to resolve the issue.

**Comment by royduin** [comment]
Most themes are using the `get_footer()` function, just like Roots Sage: https://github.com/roots/sage/blob/953a8ab5d63b5f484da5b6fbef155aa22bc2effa/templates/layouts/base.php#L29, but not in individual templates. They've created a wrapper which is used by all the templates.

**Comment by rayrutjes** [comment]
I need to test putting all the code in the header again. Or find a way to detect if the footer function is there and otherwise render in the header.

Not sure why we decided to put some info there, but I'm pretty sure we had our reasons.

**Comment by rayrutjes** [comment]
Maybe we also used this thinking it resolves the autocomplete library conflicts with other libraries like jquery ui autocomplete and google map autocomplete.

Maybe it is also a good opportunity to fix those conflicts.

**Comment by rayrutjes** [comment]
Given that including a call to `wp_footer` is part of the [theme best practices](https://codex.wordpress.org/Theme_Development#Footer_.28footer.php.29) we will not try to work around this.
