### ISSUE TITLE
Filters are Failing

### ISSUE THREAD

**Issue by jimbo11883** [algolia/algoliasearch-wordpress#446]
### What did you expect to happen?
The filter would return the post.

### What happened instead?
Missing argument 2 for cj_should_index_post.

### How can we reproduce this behavior?
add_filter('algolia_should_index_post', 'cj_should_index_post');
add_filter('algolia_should_index_searchable_post', 'cj_should_index_post');
function cj_should_index_post($should_index, $post) {
}

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 0.2.8

**Comment by rayrutjes** [comment]
Hi @jimbo11883 ,

When you require more than 1 parameter, you need to specify it explicitly:

```
add_filter('algolia_should_index_post', 'cj_should_index_post', 10, 2);
add_filter('algolia_should_index_searchable_post', 'cj_should_index_post', 10, 2);
```

Now yous should correctly get the second parameter.

**Comment by jimbo11883** [comment]
Thanks Ray! I feel like such an idiot...
