### ISSUE TITLE
Feature request: choose which refinement widgets should be displayed

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-wordpress#448]
Currently there are four refinement widgets on the instantsearch page:

- Post Type
- Categories
- Tags
- Authors

It would be nice if these can be enabled/disabled from the configuration page in the Wordpress admin.

**Comment by rayrutjes** [comment]
Yes, you are right.

We are afraid this would add complexity for customizing the file.

We are not sure where to go about this and are still receiving feedback.

Enabling / Disabling those widgets is rather easy currently, but of course limite to users having access to the filesystem.

Let me know your thought.

**Comment by royduin** [comment]
I've copied the `instantsearch.php` to my theme, removed the widgets I don't need and that's working great. But there are a lot of Wordpress users who can't code, they just install a plugin and if it's not working they'll search for a alternative plugin. For those users I think this is helpful.

For me as developer: the less changes in the `instantsearch.php` the better because everytime there is a update of the plugin I need to compare my `instantsearch.php` with the latest version and see if it's still compatible.

**Comment by rayrutjes** [comment]
Yes you make some points there for sure.
Making the plugin simple for both developers and non technical users is a big challenge.

I will definitely challenge the idea, let me come back to this in a bit.

Also as we are working on the WooCommerce integration, we already have some topics that would need to be addressed in this plugin.

**Comment by rayrutjes** [comment]
It appears that most users change other things than just addition and removal of widgets.
For now then can do so by overriding the template files.
I'm closing this for now as it is not part of the roadmap.

Feel free to submit a PR though after we released v2 in a few days. Codebase and indexing process will be simplified.
