### ISSUE TITLE
Remove Algolia Powered By with true?

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-wordpress#449]
It's currently possible to remove the Algolia Powered By message with: `define('ALGOLIA_POWERED_BY', true);`, that's a little bit weird right? Should we rename this (to `REMOVE_ALGOLIA_POWERED_BY` for example) or make it configurable from the admin? There is already some code for that: https://github.com/algolia/algoliasearch-wordpress/blob/f642915bb35372aff509c6219da5b0ea95677696/includes/class-algolia-settings.php#L250-L263

**Comment by rayrutjes** [comment]
This has been discussed here #333 
As we will cleanup the admin UX after the WooCommerce plugin release, we might want to consider this again.

**Comment by royduin** [comment]
I came across that issue but it was closed and didn't answer my questions. Keep this issue open for discussion?

**Comment by rayrutjes** [comment]
Yes @royduin lets leave it open, I'll deal with it when we re-brand the admin.
Thanks ❤️ !
