### ISSUE TITLE
One of my indexes aren't showing results in Autocomplete, but show in native search

### ISSUE THREAD

**Issue by jimbo11883** [algolia/algoliasearch-wordpress#450]
### What did you expect to happen?
Seeing results in autocomplete.

### What happened instead?
With the newest version of the WP plugin, we see that the 'plants' index isn't showing results. 

### How can we reproduce this behavior?
Go to our site, click the search magnification icon in the header. Type in 'aloe' and you should see multiple results for "Plants" but we no longer see them.

### Can you provide a link to a page which shows this issue?
http://cactusjungle.com/

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 0.2.8

**Comment by jimbo11883** [comment]
I also get this javascript error:

VM4311:23 Uncaught TypeError: Cannot read property 'matchedWords' of undefined(…)
(anonymous function) @ VM4311:23
c @ underscore.min.js?x34027:5
(anonymous function) @ wp-util.min.js?x34027:1
a @ autocomplete.min.js?x34027:7
y.map @ autocomplete.min.js?x34027:6
d @ autocomplete.min.js?x34027:7
_render @ autocomplete.min.js?x34027:7
b @ autocomplete.min.js?x34027:7
(anonymous function) @ algolia-public-autocomplete.js?x34027:56
(anonymous function) @ algoliasearch.jquery.min.js?x34027:2

**Comment by rayrutjes** [comment]
Hey @jimbo11883 !

Thanks for reporting this, it looks like you pushed custom attributes, and you also removed the default 'title1-6' fields.

In our default logic we check those fields to display the most relevant one. In your case the fields do not exist as your remove the fields for the attributes from indexing.

Is there a specific reason for which you decided to remove the title1-6 fields?

We should make sure the template doesn't break, I will flag this as bug and make sure we address it.

**Comment by rayrutjes** [comment]
For now you can fix it manually by making sure value is not undefined here: https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/autocomplete.php#L22

And here: 
https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/autocomplete.php#L25

Let me know if that works!

**Comment by jimbo11883** [comment]
I didn't know what the titles fields were used for, but they always seemed
to be blank. So I thought they were not needed. I'll edit my code again to
put them back in.

**Comment by rayrutjes** [comment]
We split the posts according to the DOM of the content. 
The we requesting results, we only ask for the most relevant record per post, this is possible thanks to the distinct feature being enabled on the index.

This strategy ensures optimal relevancy ;)

I will still make sure the fields are present before trying to display them.

**Comment by jimbo11883** [comment]
We have Types custom fields that aren't in the_content. How can we get them to display in the search results?

**Comment by rayrutjes** [comment]
You can add them to the `autocomplete.php` file,

Could you give some code so that I can give you clearer indications? Not sure I answered your question here.

**Comment by jimbo11883** [comment]
I found algolia-autocomplete-post-suggestion.php, in the plugins partials folder. Can I copy this to my theme and make changes? What directory structure do I need in my theme?

**Comment by rayrutjes** [comment]
You cant only override the full files:
- autocomplete.php
- instantsearch.php

You have to copy paste those files in a folder named `algolia` in your active theme
Then they should be loaded instead of the plugin's ones.

We will improve this part in the future. For now this is the way to go.

**Comment by 2aces** [comment]
Just a quick (and polite) note: why not keep this as an open issue as it is not really resolved? It may help people looking only on open issue filter (I almost did that), btw.

Thanks for the info/workarounds.
