### ISSUE TITLE
Conflict with WPML

### ISSUE THREAD

**Issue by insanetisane** [algolia/algoliasearch-wordpress#454]
### What did you expect to happen?
When I save a translated post, it saves properly.

### What happened instead?
When I save a translated post, the translation data is not saved in the database. The pages are disconnected (they no longer relate as one being a translation of the other)

### How can we reproduce this behavior?
Create a translation of a page, then try to edit it.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.5.0
* WPML version: 3.6.1

This may be a WPML issue (as they recently updated) but I wanted to post this here as well just in case. Any help would be great.

Thanks!

**Comment by rayrutjes** [comment]
Thanks a lot @insanetisane for submitting this here,

We will investigate this right now as this looks similar to the Publicize feature from Jetpack conflict.

Do you mind sending me over the version of WPML plugin you are using so that we can resolve the conflict? please send it to support+wordpress@agolia.com

**Comment by insanetisane** [comment]
Hey Raymond, Thanks for looking into this.

WPML version: 3.6.1

Also here is an error showing up in the logs: 

PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'No translation entry found for query: s:42:" element_id = %d AND element_type LIKE %s ";a:2:{i:0;i:32546;i:1;s:18:"post_algolia_task%";}' in /nas/content/live/abtrogers/wp-content/plugins/wpml-translation-management/classes/records/class-wpml-tm-icl-translations.php:183\nStack trace:\n#0 /nas/content/live/abtrogers/wp-content/plugins/wpml-translation-management/classes/records/class-wpml-tm-icl-translations.php(60): WPML_TM_ICL_Translations->select_translation_id(' element_id = %...', Array)\n#1 /nas/content/live/abtrogers/wp-content/plugins/wpml-translation-management/classes/records/class-wpml-tm-icl-translations.php(41): WPML_TM_ICL_Translations->build_from_element_id(Array)\n#2 /nas/content/live/abtrogers/wp-content/plugins/wpml-translation-management/classes/records/class-wpml-tm-records.php(137): WPML_TM_ICL_Translations->__construct(Object(WPML_TM_Records), Array, 'id_type_prefix')\n#3 /nas/content/live/abtrogers/wp-content/plugins/wpml-translation in /nas/content/live/abtrogers/wp-content/plugins/wpml-translation-management/classes/records/class-wpml-tm-icl-translations.php on line 183, referer: http://beta.about.rogers.com/wp-admin/post.php?post=21029&action=edit&lang=fr

**Comment by rayrutjes** [comment]
Hey @insanetisane , could you check if this still happens with the latest version 3.6.2?

It looks like there are some fixes that might be related to this issue: https://wpml.org/2016/12/wpml-3-6-2-stability-compatibility-improvements/

I'm closing this, please re-open if 3.6.2 doesn't fix the issue and I'll investigate more in depth!

Thanks a lot for reporting this in the first place ❤️

**Comment by insanetisane** [comment]
Hey Ray,
We updated all of our WPML plugins when they were released and unfortunately this issue still persists. I was hoping it would be resolved too 😛

**Comment by rayrutjes** [comment]
Then I'm re-opening. I'll need to test it. 
The weird thing being that a lot of users do not have the issue, so I'm wondering if it's related to the latests versions of the plugin or if it is a conflict with something else.

Thanks you for your patience.

**Comment by insanetisane** [comment]
That is weird… I’ll see if I can do more testing on our end as well. Thanks for your help!

**Comment by insanetisane** [comment]
There seems to be an issue now on the same site. Algolia has stopped logging all category, tag, and custom taxonomy data just for our french custom post types.

This was working up until recently. Neither algolia nor WPML was update between when it was working and now.

Any ideas?

**Comment by rayrutjes** [comment]
@insanetisane after investigation, I confirm that the `terms` are only being fetched correctly for the default language.

I tried patching the code with the techniques found here, with no luck: https://wpml.org/forums/topic/get-all-terms-of-all-languages-outside-loop/

The last comment of that page si interesting is is exactly what we are running into as well.

The objective? Being able to load the terms of a post that is in another language.

For now any thing we tried failed, if anyone has some insight, please do share ;)

**Comment by rayrutjes** [comment]
This also seems to be somehow related: https://wpml.org/forums/topic/remove-get_terms-filters/

In our code, here is what doesn't work as expected: https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-searchable-posts-index.php#L197

**Comment by insanetisane** [comment]
I'm taking a look at the code and the get_post_shared_attributes function works out of the context of the plugin. I copied it, pasted in functions.php, renamed the function and passed it a post. I get the french categories and tags on the english pages. Could it be something else?

**Comment by insanetisane** [comment]
I've manage to patch a fix:
```
			$terms = get_the_terms( $post->ID, $taxonomy->name );

			global $sitepress;
			// // remove WPML term filters
			remove_filter('get_terms_args', array($sitepress, 'get_terms_args_filter'));
			remove_filter('terms_clauses', array($sitepress,'terms_clauses'));
			$terms_objects_test = wp_get_object_terms( $post->ID, $taxonomy->name );			 
			// // restore WPML term filters
			add_filter('terms_clauses', array($sitepress,'terms_clauses'));
			add_filter('get_terms_args', array($sitepress, 'get_terms_args_filter'));

			if (!$terms) {
				$terms = $terms_objects_test;
			}
```

This removes some WPML filters that are getting in the way and checks for terms with the filters removed. Seems to work so far!

**Comment by rayrutjes** [comment]
I'd love to add this to the codebase in our compatibility class.

Any chance you could do a PR to see where exactly you did insert this piece of code, because I tried similar implementations without much success.

**Comment by insanetisane** [comment]
https://github.com/algolia/algoliasearch-wordpress/pull/506

This is exactly how I did the fix on for our website. This is just done on the searchable posts because that's all we needed.

Hope that helps!
