### ISSUE TITLE
Change index to posts_attachments

### ISSUE THREAD

**Issue by peterchen1999** [algolia/algoliasearch-wordpress#464]
### What did you expect to happen?
After changing the index by changing this block:

var search = instantsearch({
appId: algolia.application_id,
apiKey: algolia.search_api_key,
indexName: algolia.indices.posts_attachment.name,

I was changing the index at which the search box is polling from. Expected behavior is to show the media thumbnails.

### What happened instead?
It seems to be "working" but did not show any results. Only evidence it is working is the number of results found matches the number of records in the posts_attachment index. 

I'm trying to implement a sort of "search for a resource" option, so people can start typing, find their resource file, click it, and it will download. In this case, all resources are graphics.

### How can we reproduce this behavior?
Change indexName to point to the posts_attachment index.

Can you provide a link to a page which shows this issue?
http://resources.pnwkeyclub.org/graphics/

### Technical info
* WordPress version: latest
* Algolia Search plugin version: latest

**Comment by rayrutjes** [comment]
Hi @peterchen1999 ,

By analyzing the console errors on your example implementation, it appears to me that the image urls are not correctly generated for the posts_attachment index.

In the answer you get back from Algolia, there is a field you might use to reconstruct the urls:
```
"metadata": {
						"sizes": {
							"post-thumbnail": {
								"file": "Builders-Club-Wordmark-Color-1200x390.png"
							}
						}
					},
```

You should take a look at how to customize the search page experience here: https://community.algolia.com/wordpress/customize-search-page.html

And try to replace this section: https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/instantsearch.php#L22
with your own implementation.

Let me know if you manage to get it up and running.

**Comment by peterchen1999** [comment]
Hey @rayrutjes,

I changed the referral URL to that of post-thumbnail but it still doesn't seem to want to work. Do you have any thoughts as to what might be going wrong? I'm unsure if it's even going into the L22 if statement.

**Comment by rayrutjes** [comment]
@peterchen1999 well I consider this as a bug, I expected the thumbnail field to be provided during indexing. Truth is, so far we haven't had any feedback on this.

I will need to spend some time figuring out what goes wrong during the thumbnail generation.
