### ISSUE TITLE
Toolset plugin conflicting with Algoliasearch-wordpress

### ISSUE THREAD

**Issue by Ben764** [algolia/algoliasearch-wordpress#466]
### What did you expect to happen?
Algoliasearch-wordpress is setup do index posts, pages, and a custom post type. 

### What happened instead?
Algolia didn't complete indexing. In the Algolia backend I only found a searchable_posts_tmp index.
### How can we reproduce this behavior?
I only find this behavior when Toolset plugins (Types/Views) are installed. I tested the same data on a installation without the Toolset plugins, indexing completed.  Disabling Toolset plugins, however, doesn't prevent this plugin conflict.

Can you provide a link to a page which shows this issue?
No, dev machines are not publicly available.
### Technical info
* WordPress version: 4.7
* Algolia Search plugin version: 1.6.0

**Comment by rayrutjes** [comment]
Hi @Ben764 thanks for reporting this, I will look into it.
Looks like some kind of conflict with the `Toolset plugins (Types/Views) ` plugin.

**Comment by alisynthesis** [comment]
@rayrutjes - Any progress on this one? We'd love to use this for loads of client sites, but the sites often use Types/Views as well.

**Comment by rayrutjes** [comment]
@alisynthesis we are working on changing the way we index and send records to Algolia.
No ETA, but the moment we release the new re-indexing, we should have way better compatibility with third party plugins.

Please bear with us.

**Comment by alisynthesis** [comment]
@rayrutjes awesome, thanks for the update. 👍
