### ISSUE TITLE
Wordpress Search is not replaced / Autocomplete is not working

### ISSUE THREAD

**Issue by filontheroad** [algolia/algoliasearch-wordpress#468]
### What did you expect to happen?

I followed the install instructions for the plugin step by step and I expect the plugin to replace the standard search function of Wordpress as announced.

### What happened instead?
The Search is not replaced and does not even work anymore after activating the plugin. Also it seems to interfere with the Plugin "All in One Security & Firewall" as I had to deactivate it to get the page indexed. As soon as I turn it on i get several errors "wp_remote_post() failed, indexing won't work." Which result in the index not being updated. 

### How can we reproduce this behavior?

Can you provide a link to a page which shows this issue?
https://wissen-hund.de

### Technical info
* WordPress version: 4.7
* Algolia Search plugin version: actual Version 1.6

**Comment by filontheroad** [comment]
Hello Raymond,

thanks for your quick reply.

Well there are a few error messages showing up as you can see in the
attached screenshot:



You need any of the detailed data?

Best regards,
Fil

**Comment by filontheroad** [comment]
P.S. Also the site runs on https

Raymond Rutjes schrieb:

**Comment by rayrutjes** [comment]
@filontheroad I can't see the screenshots, can you paste theme directly on the issue maybe?

**Comment by filontheroad** [comment]
![bildschirmfoto 2016-12-28 um 13 17 26](https://cloud.githubusercontent.com/assets/4562487/21522117/2fe963fc-cd03-11e6-9386-c4aa49a290e0.png)
This is the overview

**Comment by rayrutjes** [comment]
Could you give us the details of the task 12135?

**Comment by filontheroad** [comment]
I can send you the log as attached file hereby.
[log12135.txt](https://github.com/algolia/algoliasearch-wordpress/files/675571/log12135.txt)

**Comment by filontheroad** [comment]
@rayrutjes Did you get the log file? Any solution you recommend?

**Comment by rayrutjes** [comment]
Sorry about the delay here @filontheroad ,

Did you manage to get it running?

Where did you send the file?

**Comment by filontheroad** [comment]
Hello,

I had posted it on the thread here. Since I haven´t heard back from you
I deleted it again. No it is stil not running as it should.

Raymond Rutjes schrieb:

**Comment by rayrutjes** [comment]
i'm sorry to hear that. It looks like though that there is nothing attached to your last answer. Do you mind attaching it directly to the GH issue?

**Comment by filontheroad** [comment]
Here it is 
[log.txt](https://github.com/algolia/algoliasearch-wordpress/files/709117/log.txt)

**Comment by rayrutjes** [comment]
@filontheroad it looks like the logs you sent me were about the search not being able to access a given index. Could you please send me the logs of a task of type "An error occured while handling..."? Please send those logs to support+wordpress@algolia.com

Thanks for your patience.

**Comment by filontheroad** [comment]
@rayrutjes Okay send

**Comment by rayrutjes** [comment]
@filontheroad I'll close this one for the time being. Please share your solution here or feel free to ping me again if you have more context about the issue.
