### ISSUE TITLE
Results strip final child category from URL

### ISSUE THREAD

**Issue by tedcarstensen** [algolia/algoliasearch-wordpress#477]
### What did you expect to happen?

Our site combines parent and child categories to build urls. For example, a single episode of a single podcast has a url like this - https://www.heavybit.com/library/podcasts/practical-product/ep-7-digital-dev-at-blue-bottle-coffee/

Library, Podcasts, and Practical Product are all categories.

When using default Wordpress search, the URLs returned reflect all parent and child categories in the correct order, and the content loads correctly.

### What happened instead?

When using Algolia powered search, the content is returned correctly and loads fine, but the final category is stripped from the slug. ie. https://www.heavybit.com/library/podcasts/practical-product/ep-7-digital-dev-at-blue-bottle-coffee/ becomes https://www.heavybit.com/library/podcasts/ep-7-digital-dev-at-blue-bottle-coffee/

The content still loads because the post is technically a child of the remaining categories, but this is very undesirable behavior.

### How can we reproduce this behavior?

http://dev-heavybit.pantheonsite.io/

### Technical info
* WordPress version: 4.7
* Algolia Search plugin version: 1.6.0

**Comment by rayrutjes** [comment]
Hi @tedcarstensen , thanks a lot for spotting this.
I think this might be what we call a bug!

Here are the 2 lines that needs to be modified:
- https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-searchable-posts-index.php#L188
- https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-posts-index.php#L180

I believe we need to replace `get_permalink` with `get_post_permalink`.

I'll try to push a PR today.

If you want you could hotfix this in your code and let me know if that resolves it.
You will need to trigger a full re-index once it's done!

I appreciate you took the time to report the issue!

**Comment by rayrutjes** [comment]
@tedcarstensen I just investigated but didn't manage to re-produce this one.

Can you tell me for http://dev-heavybit.pantheonsite.io/library/podcasts/data-science-storytime/ep-3-the-future-of-data/:
- What categories are associated to this post? (screenshot of the post in edit mode with visible categories on the right appreciated)
- What is the configuration of your permalinks (screenshot of the `Settings -> Permalinks` ppareciated)
- Do you use any kind of plugin related to URL re-writing like `WP Category Permalink`?

Thanks for your help on this.

**Comment by rayrutjes** [comment]
@tedcarstensen do you think you could take a quick look into this anytime soon?

**Comment by tedcarstensen** [comment]
@rayrutjes Damn, apologies Ray, my notification settings weren't set up correctly.

### What categories are associated with this post?

This post - http://dev-heavybit.pantheonsite.io/library/podcasts/data-science-storytime/ep-3-the-future-of-data/ -  has three categories: Library, Podcasts, Data Science Storytime

![post-categories](https://cloud.githubusercontent.com/assets/1002132/21951939/89c637b0-d9c4-11e6-89cc-56796bd2ff48.png)

### What is the configuration of your permalinks?

/%category%/%postname%/

![permalinks](https://cloud.githubusercontent.com/assets/1002132/21951947/a6e493aa-d9c4-11e6-8e43-b1dd3415e9c1.png)

### Do you use any kind of plugin related to URL re-writing like WP Category Permalink?

We don't use the WP Category Permalink plugin. But we do use Yoast SEO which is where these 'Primary' and 'Make Primary' options come from.

![post-categories](https://cloud.githubusercontent.com/assets/1002132/21952024/61acee52-d9c6-11e6-8760-4c9737a754d0.png)

**Comment by rayrutjes** [comment]
Good news @tedcarstensen , the YOAST plugin is so well designed that this was an easy fix.
We even decided to integrate it out of the box given the popularity of the plugin.

This will be available in version 1.7.0, if you want to use it straight away, apply the patch from here: #485 

Thanks for your help on this!
