### ISSUE TITLE
Search Results page not showing all posts

### ISSUE THREAD

**Issue by kakashigr** [algolia/algoliasearch-wordpress#487]
We are using a custom pre_get_posts filter for our search results which 
changes the posts_per_page to 12 instead of the default 6 we have configured on wordpress:
```php
<?php
// Exclude blog posts from search_items
function search_filter_bp($query) {
    if ( !is_admin() and !is_feed() ) {
      if ($query->is_search && $query->is_main_query()) {
		 // $query->set('post_type', array('post'));
		  $query->set('posts_per_page', 12);
      }
    }

    return $query;
    
}
add_filter('pre_get_posts', 'search_filter_bp');
?>
```

We noticed that this filter doesn't work with algolia plugin installed and activated, 
which means the plugin is also hooking there overwriting us.

We also use these two filters specific to algolia:
```php

<?php
// Filter out some categories from the autocomplete search suggestions
add_filter('algolia_should_index_term', 'custom_should_index_term', 10, 2);
function custom_should_index_term( $should_index, WP_Term $term ) {
    $exluded = get_option('gf_exclude_cats');
    $exluded = str_replace(" ", "", $exluded);
    $categories_to_exclude = explode(",",$exluded);

    if ( false === $should_index ) {
        return $should_index;
    }

    if ( in_array($term->term_id, $categories_to_exclude ) ) {
        return false;
    }

    return $should_index;
}
// Exclude all other post_types from search, keep only 'post'
add_filter('algolia_should_index_post', 'custom_should_index_post', 10, 2);
add_filter('algolia_should_index_searchable_post', 'custom_should_index_post', 10, 2);
function custom_should_index_post( $should_index, WP_Post $post ) {

    if ( false === $should_index ) {
        return $should_index;
    }

    if ( $post->post_type !== 'post' ) {
        return  false;
    }

    return $should_index;
}
?>
```
When the plugin is active we also have the following bug:
http://thegadgetflow.com/page/8/?s=Notebooks

Instead of showing 6 per page, it show 5 only on this page. When we deactivate 
the plugin, both our custom search pre_get_posts works and we have 12/page and 
page 8 has 12/page not 11/page. 

We are using the latest version of Wordpress and algolia plugin

**Comment by rayrutjes** [comment]
Hi @kakashigr , we indeed override the described hooks. I will need to dig into this a bit further to give you clear guidelines.

Do you mind formatting the code above in the meantime?

**Comment by rayrutjes** [comment]
@kakashigr so we are using `get_option('posts_per_page')` to determine the number of posts per page, see: https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/class-algolia-search.php#L66

You could use the [option_posts_per_page hook](https://developer.wordpress.org/reference/hooks/option_option/) and return the number you want given the context.

I hope that helps. Sorry about the delay. Feel free to follow up here.
