### ISSUE TITLE
Remove empty arrays from Algolia records

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#493]

**Comment by ronizamir** [comment]
Hi - can you share when it suppose to be fixed?

**Comment by rayrutjes** [comment]
Hi @ronizamir , until the fix is implemented in an official release, you can try to add the following snippet to your functions.php file of your theme: https://gist.github.com/rayrutjes/a3d7e243d663e410a4d33cd6c06a9f0b

Let me know if that works for you,
