### ISSUE TITLE
Reindex when term name changes

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#496]
### What did you expect to happen?

All posts connected to a taxonomy term are automatically reindexed when that term's name is changed.

### What happened instead?

No reindexing.

### How can we reproduce this behavior?

Create a term, connect a post to that term, edit the term's name.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.7.1
* Algolia Search plugin version: 1.5.0

**Comment by rayrutjes** [comment]
Hi @ethansmith ,

You are right, we currently do not plan to support this and recommend you do a full re-index after such changes.

**Comment by rayrutjes** [comment]
I'm closing this for now, if you think you have a pragmatic and simple way to resolve this, I'd gladly take  look!
