### ISSUE TITLE
Index position not taken into account?

### ISSUE THREAD

**Issue by Spone** [algolia/algoliasearch-wordpress#497]
### What did you expect to happen?

In autocomplete, I want to reorder my indices based on their `position` value.

I'm adding specific indices (coming from outside Wordpress) to my autocomplete results, this way:

```php
// Customize config (in functions.php)
function my_algolia_config( array $config ) {
  // Add other indices
  $config['autocomplete']['sources'][] = [
    'index_id' => 'taxons',
    'index_name' => 'Taxons_dev',
    'label' => 'Taxons',
    'position' => 90,
    'max_suggestions' => 3,
    'tmpl_suggestion' => 'autocomplete-taxon-suggestion',
    'enabled' => true
  ];
  return $config;
}
add_filter( 'algolia_config', 'my_algolia_config' );
```

### What happened instead?

The added indices are shown at the end of the autocomplete dropdown menu. It's like `position` is not taken into account.

### How can we reproduce this behavior?

see above

### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version: 1.7.0

**Comment by Spone** [comment]
I managed to make it work by re-sorting the array in my filter:

```php
// Customize config (in functions.php)
function my_algolia_config( array $config ) {
  // Add other indices
  $config['autocomplete']['sources'][] = [
    'index_id' => 'taxons',
    'index_name' => 'Taxons_dev',
    'label' => 'Taxons',
    'position' => 90,
    'max_suggestions' => 3,
    'tmpl_suggestion' => 'autocomplete-taxon-suggestion',
    'enabled' => true
  ];
  
  // Sort the sources based on their position
  usort($config['autocomplete']['sources'], function($a, $b) {
    return $a['position'] <=> $b['position'];
  });
  
  return $config;
}
add_filter( 'algolia_config', 'my_algolia_config' );
```

Is it the recommended way to do it?

**Comment by rayrutjes** [comment]
Hi @Spone ,

You can use the `algolia_autocomplete_config` instead which will ensure the sources are sorted according to the `position` value: https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/class-algolia-autocomplete-config.php#L122

I hope that helps, thanks for reaching out ;)

**Comment by Spone** [comment]
Thanks @rayrutjes 

So here is the final snippet:

```php
// Customize autocomplete config (in functions.php)
function my_algolia_autocomplete_config( array $config ) {
  // Add other indices
  $config[] = [
    'index_id' => 'taxons',
    'index_name' => 'Taxons_dev',
    'label' => 'Taxons',
    'position' => 90,
    'max_suggestions' => 3,
    'tmpl_suggestion' => 'autocomplete-taxon-suggestion',
    'enabled' => true
  ];
  return $config;
}
add_filter( 'algolia_autocomplete_config', 'my_algolia_autocomplete_config' );
```

**Comment by rayrutjes** [comment]
Thanks for sharing that @Spone 👍
