### ISSUE TITLE
How to create a "composite" index (Pages + Custom Post Types)

### ISSUE THREAD

**Issue by Spone** [algolia/algoliasearch-wordpress#499]
Hello,

I'd like to create an index which would contain my Pages and a few Custom Post Types (whose content is similar to Pages). How can I set this up?

Thanks in advance.

**Comment by rayrutjes** [comment]
It depends on what you currently use. If you are already using the "searchable posts" index for an other purpose, you could try duplicating the class and fine tune it: https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/indices/class-algolia-searchable-posts-index.php

You will need to register it with the filter `algolia_indices` see https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/class-algolia-plugin.php#L294

If you are not using the searchable posts index yet, you can use the `algolia_should_index_searchable_post ` filter to only index the post of the types you want.

Let me know if that helps.

**Comment by Spone** [comment]
Thanks @rayrutjes I managed to use the "searchable posts" index with very few customization. I changed its label for autocomplete using the `algolia_autocomplete_config` filter.
