### ISSUE TITLE
Programmatically created/altered products are not indexed

### ISSUE THREAD

**Issue by SolidDev** [algolia/algoliasearch-wordpress#503]
In creating sample products for my WC instance, I used PHP to create a products for each category. I expected to see all the new products that were showing up in my WP admin, to show up in my Algolia Dashboard Index.

I soon realized that Algolia was not indexing my new products until I clicked the Publish button from the edit product page within WP. As I have hundreds of test products and will have thousands of products in production, this is a less than optimal way of updating my indexes when making changes to products programmatically.

You can test this on your own by using my 'Create a Product for Each Category' template:
`/* Template Name: Product Generator Template */

$taxonomy     = 'product_cat';
$orderby      = 'name';  
$show_count   = 0;      // 1 for yes, 0 for no
$pad_counts   = 0;      // 1 for yes, 0 for no
$hierarchical = 1;      // 1 for yes, 0 for no  
$title        = '';  
$empty        = 0;

$args = array(
     'taxonomy'     => $taxonomy,
     'orderby'      => $orderby,
     'show_count'   => $show_count,
     'pad_counts'   => $pad_counts,
     'hierarchical' => $hierarchical,
     'title_li'     => $title,
     'hide_empty'   => $empty
);
$c = get_categories( $args );
$i = 0;
foreach ($c as $a) :
	if (!$a->parent)
		continue;
	$post_id = wp_insert_post( array(
		'post_title' => 'Product ' . $a->cat_ID,
		'post_content' => '',
		'post_status' => 'publish',
		'post_type' => 'product',
	) );
	wp_set_object_terms( $post_id, 'simple', 'product_type' );
	update_post_meta( $post_id, '_stock_status', 'instock');
	update_post_meta( $post_id, 'total_sales', '0' );
	update_post_meta( $post_id, '_downloadable', 'no' );
	update_post_meta( $post_id, '_virtual', 'yes' );
	update_post_meta( $post_id, '_regular_price', '' );
	update_post_meta( $post_id, '_sale_price', '' );
	update_post_meta( $post_id, '_purchase_note', '' );
	update_post_meta( $post_id, '_featured', 'no' );
	update_post_meta( $post_id, '_weight', '' );
	update_post_meta( $post_id, '_length', '' );
	update_post_meta( $post_id, '_width', '' );
	update_post_meta( $post_id, '_height', '' );
	update_post_meta( $post_id, '_sku', '' );
	update_post_meta( $post_id, '_product_attributes', array() );
	update_post_meta( $post_id, '_sale_price_dates_from', '' );
	update_post_meta( $post_id, '_sale_price_dates_to', '' );
	update_post_meta( $post_id, '_price', '' );
	update_post_meta( $post_id, '_sold_individually', '' );
	update_post_meta( $post_id, '_manage_stock', 'no' );
	update_post_meta( $post_id, '_backorders', 'no' );
	update_post_meta( $post_id, '_stock', '' );
	wp_set_object_terms( $post_id, array($a->parent, $a->cat_ID), 'product_cat' );
	echo 'Created product ' . $a->cat_ID . ' Product...<br>';
endforeach;`

Assign this template to a page and visit it, now all of your products have been created.

Next, try indexing these products and then visit your Algolia Dashboard to confirm that no products have been indexed.

Lastly, in the WP admin, edit a product, change nothing, click 'Publish', visit your Algolia Dashboard to see this product has been indexed.

WP 4.7.2
Search by Algolia 1.7.0
Algolia Search for WooCommerce 0.7.0

**Comment by SolidDev** [comment]
Perhaps a better question here would be which wp action does this plugin hook into to index updated posts? I could be sure to trigger that when creating my test products.

**Comment by rayrutjes** [comment]
Hi @SolidDev you can see all the hooks here: https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/watchers/class-algolia-post-changes-watcher.php

Not sure why the save hook isn't triggered in your case, it is in most cases even with plugins that generate a lot of entries programatically.

Could it be that your import script is running to early in the wordpress process and that our plugin didn't have a chance to register hooks yet?

**Comment by SolidDev** [comment]
@rayrutjes Thanks for the response and link. I will look into it. 

I don't think that my code (located in a template file) is running before any loaded plugins. WP loads all plugins before `do_action('init')` and before any theme files are loaded.

I'll let you know if I can find the cause here.

**Comment by rayrutjes** [comment]
> I'll let you know if I can find the cause here.

Please do! I would gladly merge a PR

Thanks a bunch for reporting this in the first place.

**Comment by SolidDev** [comment]
@rayrutjes 

I've followed your code to it's end and can see no point where is errors or halts or interprets my programmatic `wp_insert_post()` differently from a WP Admin Edit Post Page Publish. 

So you are using the action hook `save_post` which is being triggered by my `wp_insert_post()` code. I've used `echo` + `die()` as breakpoints in the Algolia plugin code to follow the execution. The `sync_item` is added to the queue and then the `algolia_task` post is created. No errors, no log entries other that the expected `sync_item` which looks good to me (`Array ( [index_id] => posts_product, [post_id] => 13861, [post_type] => product )`).

I still see no products in my posts_product index until I manually publish the post from the admin area. So are you able to recreate this bug or successfully add a product programmatically or is this behavior unique to my setup?

**Comment by rayrutjes** [comment]
On my end products are properly pushed to the index. Could it be that the queue isn't processed but that the tasks are yet correctly queued?

**Comment by SolidDev** [comment]
@rayrutjes 

I thought that might be the case when I posted [this issue] (https://github.com/algolia/algoliasearch-wordpress/issues/505). But sadly, I have sat through clicking process queue until 0 tasks were pending. After that, no products were indexed in the Algolia dashboard. 

I may try tearing it all down and starting from scratch since there is obviously something that we're overlooking here and you were able to use the product generator code to create/update the index. 

Please confirm that's the case, that you have used the product generator code above and it's updating the index properly.

**Comment by pascalroget** [comment]
Check your PHP error log.

**Comment by SolidDev** [comment]
There are no PHP errors being logged by the plugin. I'm not sure how to proceed with troubleshooting.

**Comment by pascalroget** [comment]
Have you tried running the queue manually via WP-CLI?

**Comment by SolidDev** [comment]
@rayrutjes 

I've tried activating only the parent theme and then creating the products programmatically again with no luck of them indexing themselves. The Process Queue does run all the way through now without interruption and the Algolia log, as well as the WP log and server's PHP log all show 0 errors or warnings. 

Below is the code used to generate products. I've created a `template-product-generator.php` with the following code and inserted it into the template file. I then assigned the template to a new page and loaded it up in a browser. The code creates 1 product for the first 12 product categories it finds. The products show up fine on the frontend catalog and in the backend. However, the Algolia index is not updated with any new products unless I manually edit a product via the WP admin and click 'Update'.

The code uses `wp_insert_post()`, `update_post_meta()` and `wp_update_post()`. All of which I beleive trigger Algolia to add the item to the queue.

According to [WP Codex - Plugin API/Action Reference/save post](https://codex.wordpress.org/Plugin_API/Action_Reference/save_post), the `save_post` is an action triggered whenever a post or page is created or updated. One of Algolia's watcher script (`includes/watchers/class-algolia-post-changes-watcher.php`) monitors that action as well as updated_post_meta` and `updated_post_meta`, all of which are triggered by the code below.

I'm still unsure why Algolia is not syncing these records. 

`<?php
/* Template Name: Product Generator Template */

$taxonomy = 'product_cat';
$orderby = 'name';  
$show_count = 0;
$pad_counts = 0;
$hierarchical = 1;
$title = '';  
$empty = 0;

$args = array(
     'taxonomy' => $taxonomy,
     'orderby' => $orderby,
     'show_count' => $show_count,
     'pad_counts' => $pad_counts,
     'hierarchical' => $hierarchical,
     'title_li' => $title,
     'hide_empty' => $empty
);
$c = get_categories( $args );
$i = 0;
foreach ($c as $a) :
	if ($i > 10)
		break;
	if (!$a->parent)
		continue;
	$post_id = wp_insert_post( array(
		'post_title' => 'Product ' . $a->cat_ID,
		'post_content' => '.',
		'post_status' => 'publish',
		'post_type' => 'product',
	), true );
	wp_set_object_terms( $post_id, 'simple', 'product_type' );
	update_post_meta( $post_id, '_stock_status', 'instock');
	update_post_meta( $post_id, 'total_sales', '0' );
	update_post_meta( $post_id, '_downloadable', 'no' );
	update_post_meta( $post_id, '_virtual', 'yes' );
	update_post_meta( $post_id, '_regular_price', '1' );
	update_post_meta( $post_id, '_sale_price', '1' );
	update_post_meta( $post_id, '_featured', 'no' );
	update_post_meta( $post_id, '_product_attributes', array() );
	update_post_meta( $post_id, '_price', '1' );
	update_post_meta( $post_id, '_manage_stock', 'no' );
	update_post_meta( $post_id, '_backorders', 'no' );
	update_post_meta( $post_id, '_stock', '0' );
	wp_set_object_terms( $post_id, array($a->parent, $a->cat_ID), 'product_cat' );
	wp_publish_post( $post_id );
	$post = get_post($post_id);
	wp_update_post($post);
	echo 'Created product ' . $a->cat_ID . ' Product...<br>';
	$i++;
endforeach;`

**Comment by SolidDev** [comment]
I've found the solution here. There is nothing wrong with the Algolia for WC plugin. The problem was in my product generator code. 

Add to the `$post_id` declaration: `'post_author' => get_current_user_id(),` and `update_post_meta( $post_id, '_sku', '' );` and `update_post_meta( $post_id, '_visibility', 'visible' );`. After adding those 3 lines, The code now generates products that are both visible on the frontend of my side and indexed within Algolia. 

Below is the complete product generator code. This code will generate one product for each of the _bottom-most_ categories.

`
<?php
/* Template Name: Product Generator Template */

$taxonomy     = 'product_cat';
$orderby      = 'name';  
$show_count   = 0;
$pad_counts   = 0;
$hierarchical = 1;  
$title        = '';  
$empty        = 0;

$args = array(
     'taxonomy'     => $taxonomy,
     'orderby'      => $orderby,
     'show_count'   => $show_count,
     'pad_counts'   => $pad_counts,
     'hierarchical' => $hierarchical,
     'title_li'     => $title,
     'hide_empty'   => $empty
);
$c = get_categories( $args );
$i = 0;
foreach ($c as $a) :
	if ($i > 10)
		break;
	if (!$a->parent)
		continue;
	$post_id = wp_insert_post( array(
		'post_author' => get_current_user_id(),
		'post_title' => 'Product ' . $a->cat_ID,
		'post_content' => '.',
		'post_status' => 'publish',
		'post_type' => 'product',
	), true );
	wp_set_object_terms( $post_id, 'simple', 'product_type' );
	update_post_meta( $post_id, '_stock_status', 'instock');
	update_post_meta( $post_id, 'total_sales', '0' );
	update_post_meta( $post_id, '_downloadable', 'no' );
	update_post_meta( $post_id, '_virtual', 'no' );
	update_post_meta( $post_id, '_sku', '' );
	update_post_meta( $post_id, '_visibility', 'visible' );
	update_post_meta( $post_id, '_regular_price', '1' );
	update_post_meta( $post_id, '_sale_price', '1' );
	update_post_meta( $post_id, '_featured', 'no' );
	update_post_meta( $post_id, '_product_attributes', array() );
	update_post_meta( $post_id, '_price', '1' );
	update_post_meta( $post_id, '_manage_stock', 'no' );
	update_post_meta( $post_id, '_backorders', 'no' );
	update_post_meta( $post_id, '_stock', '0' );
	wp_set_object_terms( $post_id, array($a->parent, $a->cat_ID), 'product_cat' );
	wp_publish_post( $post_id );
	$post = get_post($post_id);
	wp_update_post($post);
	echo 'Created product ' . $a->cat_ID . ' Product...<br>';
	$i++;
endforeach;
`
