### ISSUE TITLE
New Install in Wordpress not getting past _tmp index

### ISSUE THREAD

**Issue by RonnieTanner** [algolia/algoliasearch-wordpress#504]
###What did you expect to happen

The indexes to create and the default search to be replaced by Algolia search

### What happened instead?

Index never got past creation of _tmp file.

### How can we reproduce this behavior?

I'm not sure.

Can you provide a link to a page which shows this issue?

http://www.thepathoftruth.com/newsite/

### Technical info
* WordPress version:4.7.1
* Algolia Search plugin version:Latest as of today

**Comment by rayrutjes** [comment]
Hi @RonnieTanner 

Could you provide us with PHP logs? If _tmp indices are not moved to the final destination in probably means a PHP error stopped the processing of the queue.

https://community.algolia.com/wordpress/logs.html

**Comment by RonnieTanner** [comment]
Hi there, I deactivated the plugin, reactivated it and started a new index process and here is what showed up in the log:

PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 5504996 bytes) in /usr/www/users/rtanner2/thepathoftruth.com/newsite/wp-content/plugins/search-by-algolia-instant-relevant-results/includes/libraries/algoliasearch-client-php/src/AlgoliaSearch/Json.php on line 12

I'm on a dedicated server with 16GB of Ram so I'd think I could bump something up if needed?

**Comment by RonnieTanner** [comment]
I was able to increase my memory allowance in wp-config:

ini_set('memory_limit', '500M');

That did the trick and it's now working. 

thanks for the tip on the logs.

Ronnie

**Comment by rayrutjes** [comment]
Glad to hear you worked it out!
