### ISSUE TITLE
Indexing Queue Status Idle & No Errors

### ISSUE THREAD

**Issue by SolidDev** [algolia/algoliasearch-wordpress#505]
While troubleshooting [this post](https://github.com/algolia/algoliasearch-wordpress/issues/503) I noticed that Indexing Queue Status was Idle, yet there were 646 pending tasks.

![screen shot 2017-02-02 at 6 26 02 pm](https://cloud.githubusercontent.com/assets/8572930/22573145/8d2f0ec0-e975-11e6-87c3-c2b8b3741070.png)

I expected there to be some errors in the log, but there were none. 

![screen shot 2017-02-02 at 6 26 10 pm](https://cloud.githubusercontent.com/assets/8572930/22573192/c6f153ac-e975-11e6-9bb8-312b11165ce9.png)

I am unsure how to troubleshoot this.

Note: Clicking the Process Queue button starts up the indexing queue for about a minute and does reduce the number of pending tasks, but soon goes idle again.

WP 4.7.2
Search by Algolia 1.7.0
Algolia Search for WooCommerce 0.7.0

**Comment by rayrutjes** [comment]
@SolidDev do you mind checking if you have PHP Errors? If the queue stops processing at some point, it probably means a PHP process has crashed for some reason.

**Comment by pascalroget** [comment]
Try switching to the default theme, clearing the queue and re-indexing everything.

**Comment by SolidDev** [comment]
@rayrutjes There are no errors in the log file. Actually, it hadn't even existed since the website was fresh. I tested that error logging was working properly using this code, which produced the PHP error log file as expected: `error_log("Testing error logging!", 0);`

Any thoughts on what else might be causing the 'Process Queue' to be going Idle?

**Comment by SolidDev** [comment]
I have removed the child theme and still see the same behavior.

There are no PHP errors being logged related to this behavior.

**Comment by pascalroget** [comment]
Try installing wp-cli http://wp-cli.org/#installing then running the following from your wordpress root directory:
$ wp-cli algolia process_queue

**Comment by SolidDev** [comment]
Unfortunately, this is on shared hosting and we will not have command line access need to install and run this.



On February 7, 2017 at 10:58:04 PM, Pascal Roget (notifications@github.com) wrote:

Try installing wp-cli http://wp-cli.org/#installing then running the following from your wordpress root directory:
$ wp-cli algolia process_queue

**Comment by rayrutjes** [comment]
@SolidDev could you use https://community.algolia.com/wordpress/logs.html#php-logs-with-an-extension to see if you get more errors that way?

**Comment by SolidDev** [comment]
@rayrutjes Thanks for the continued support. In all of my WP dev environments I make sure to set `define( 'WP_DEBUG', true ); define( 'WP_DEBUG_LOG', true );` in the `wp-config.php` file. Unfortunately, these settings have been enabled the whole time. Still no Errors on the Logs page and no PHP errors logged into the server's log file.

**Comment by rayrutjes** [comment]
Hi @SolidDev ,

If it's not a PHP error and nothing is catched by the plugin Logs, then it could be HTTP server droping connexions.

Can you have access to the apache/nginx logs and see if you see something weird there?

I can remeber we had an issue once where the http headers would get too big in the indexing loop, and apache would refuse the requests.

**Comment by SolidDev** [comment]
@rayrutjes I've reached out to the hosting company about access to the Apache logs. This is a shared CloudSites account, so I fear that we will not have sufficient rights to see the logs. Fingers Crossed... 

If all else fails, I'll try another development server.

**Comment by SolidDev** [comment]
@rayrutjes I've moved this WP instance to a new VPS where I have root access. However, the Algolia Queue is working normally and does not switch to Idle while having Pending Tasks. I am sorry to say this issue has resolved itself by simply being on a VPS now instead of regular shared hosting.

**Comment by rayrutjes** [comment]
@SolidDev please note that we are aware of the queuing system being a bit unreliable in certain environments and will change the strategy in the future.
Thanks for having taken the time to discuss your issue here.
