### ISSUE TITLE
How to index BuddyPress groups

### ISSUE THREAD

**Issue by Spone** [algolia/algoliasearch-wordpress#508]
Hello,

I'd like to create an index which would contain my [BuddyPress Groups](https://buddypress.org/about/groups/).

The `bp_group` custom type doesn't show up in on the **Indexing** page.

How can I set this up?

Thanks in advance.

**Comment by Spone** [comment]
I managed to index the groups using by creating a new Class :

```php
final class Algolia_Groups_Index extends Algolia_Index
{
	/**
	 * @var string
	 */
	protected $contains_only = 'bp_groups';

	/**
	 * @return string The name displayed in the admin UI.
	 */
	public function get_admin_name()
	{
		return __( 'Groups', 'buddypress' );
	}

	/**
	 * @param $item
	 *
	 * @return bool
	 */
	protected function should_index( $item )
	{
		// get_items() already filters hidden groups
		$should_index = true;

		// compatibility with bp-moderate-group-creation plugin
		$published_state = groups_get_groupmeta($item->id, 'published');
		$should_index = ($published_state !== "0");

		return (bool) apply_filters( 'algolia_should_index_group', $should_index, $item );
	}

	/**
	 * @param $item
	 *
	 * @return array
	 */
	protected function get_records( $item )
	{
		$record = array();
		$this->get_logger()->log_operation( sprintf( 'get_records %s', '' ), $item );
		$record['objectID'] = $item->id;
		$record['name'] = $item->name;
		$record['description'] = $item->description;
		$record['permalink'] = bp_get_group_permalink( $item );
		$record['image'] = bp_core_fetch_avatar( [
			'item_id' => $item->id,
			'object' => 'group',
			'html' => false
		] );

		$record = (array) apply_filters( 'algolia_group_record', $record, $item );

		return array( $record );
	}

	/**
	 * @return int
	 */
	protected function get_re_index_items_count()
	{
		$results = $this->query_non_hidden_groups();

		return (int) $results['total'];
	}

	/**
	 * @return array
	 */
	protected function get_settings()
	{
		$settings = array(
			'attributesToIndex' => array(
				'name',
				'description',
			),
			'customRanking' => array(
				'asc(name)',
			),
			'attributesToSnippet' => array(
				'description:10',
			),
			'snippetEllipsisText' => '…',
		);

		return (array) apply_filters( 'algolia_groups_index_settings', $settings );
	}

	/**
	 * @return array
	 */
	protected function get_synonyms()
	{
		return (array) apply_filters( 'algolia_groups_index_synonyms', array() );
	}

	/**
	 * @return string
	 */
	public function get_id()
	{
		return 'groups';
	}


	/**
	 * @param int $page
	 * @param int $batch_size
	 *
	 * @return array
	 */
	protected function get_items( $page, $batch_size )
	{
		$results = $this->query_non_hidden_groups($page, $batch_size);

		// We use prior to 4.5 syntax for BC purposes, no `paged` arg.
		return $results['groups'];
	}

	/**
	 * Returns all BP groups having a status different from "hidden"
	 *
	 * @param int $page page
	 * @param int $batch_size
	 * @return array
	 */
	protected function query_non_hidden_groups($page=null, $batch_size=null)
	{
		$args = array(
			'order'			=> 'ASC',
			'orderby'		=> 'name',
			'page'			=> $page,
			'per_page'		=> $batch_size,
			'type'			=> 'alphabetical',
			'show_hidden'	=> false
		);
		$results = BP_Groups_Group::get($args);

		return $results;
	}

	/**
	 * A performing function that return true if the item can potentially
	 * be subject for indexation or not. This will be used to determine if a task can be queued
	 * for this index. As this function will be called synchronously during other operations,
	 * it has to be as lightweight as possible. No db calls or huge loops.
	 *
	 * @param mixed $task_data
	 *
	 * @return bool
	 */
	public function supports($task_data)
	{
		return true;
	}

	/**
	 * @param Algolia_Task $task
	 *
	 * @return mixed
	 */
	protected function extract_item( Algolia_Task $task )
	{
		$data = $task->get_data();
		if ( ! isset( $data['group_id'] ) ) {
			return;
		}

		$group = groups_get_group( $data['group_id'] );

		return ! $group ? null : $group ;
	}

	public function get_default_autocomplete_config() {
		$config = array(
			'position'        => 30,
			'max_suggestions' => 3,
			'tmpl_suggestion' => 'autocomplete-group-suggestion',
		);

		return array_merge( parent::get_default_autocomplete_config(), $config );
	}

	/**
	 * @param Algolia_Task $task
	 */
	public function delete_item( Algolia_Task $task ) {
		$data = $task->get_data();
		if ( ! isset( $data['group_id'] ) || ! is_int( $data['group_id'] ) ) {
			return;
		}

		$index = $this->get_index();
		$index->deleteObject( $data['group_id'] );
		$this->get_logger()->log_operation( sprintf( '[1] Deleted 1 record from index %s', $index->indexName ) );
	}
}
```

And then adding it to my indices (in `functions.php`)

```
// Customize indices
function my_algolia_indices( array $indices ) {
	$indices[] = new Algolia_Groups_Index();
	return $indices;
}
add_filter( 'algolia_indices', 'my_algolia_indices' );
```

Is this the correct approach?

**Comment by rayrutjes** [comment]
For now this the correct approach, well done!
I'm currently working on a way to make this simpler.

The Index class is currently a bit complex and doesn't facilitate extensibility.

Also, the indexing mechanism can be a bit slow depending on the amount of data you have on your website.

I have a few questions for you to better understand your needs:
- What kind of search experiences are you building?
- Do you do custom autocomplete, instantsearch implementations?
- Was it hard to understand the current indexing logic?
- Do you have any other things you think we should improve?
- Do you feel like the plugin is overkill when you know what you actually want to build?

Thanks!

**Comment by Spone** [comment]
Thanks for the feedback. Here are my replies:

> What kind of search experiences are you building?

I'm working on the search for a content website, with a tailor-made theme, which contains News, Events, BuddyPress Groups, a few custom post types (that will all be in a single "composite" Index, along with Pages). It also performs search on 2 indices that are indexed by external sources.

> Do you do custom autocomplete, instantsearch implementations?

I use autocomplete but I had to copy and customize the current Algolia plugin integration to better fit my needs. I'm still weighting pros and cons for instantsearch. I'd like at least some of my search to work when JS is disabled, if possible, so I'll need to implement search and share templates on the front-end and back-end side (using batch requests to search multiple indexes).

> Was it hard to understand the current indexing logic?

Quite a bit, especially because I didn't find any documentation explaining the methods of the `Algolia_Index` class, and there are very few comments in the plugin code.

Also, at first, I was pretty confused by the "Searchable posts" index and didn't know what to do with it. I finally used it as a composite Index for my Custom Post Types + my Pages, but I still find the name confusing when you go to the back-office.

> Do you have any other things you think we should improve?

Yes! I think the plugin should provide an easy way to add external indices (already existing on the Algolia account) to the autocomplete search, and to save the configuration for the current environment (see `TODO` below)

I'd also like to be able to override the "public name" of each Index, that will be displayed to the users. For instance I did not find an easy way to replace "Searchable posts" (what I did below kind of works, but the checkbox for "Searchable posts" in the Autocomplete admin page always stays unchecked.

Here is how I did it:
```php
// Customize autocomplete config
function my_algolia_autocomplete_config( array $config ) {
	// Override some parameters in existing indices
	foreach ($config as $i => $index) :
		if ( 'searchable_posts' === $index['index_id'] ) {
			$config[$i]['index_id'] = 'pages';
			$config[$i]['label'] = __('Pages', 'mysite');
			$config[$i]['position'] = 60;
		}
	endforeach;

	// Add other indices
	$config[] = [
		'index_id' => 'external_index_2',
		'index_name' => 'External2_dev', // TODO: depends on environment
		'label' => __('External index 1', 'mysite'),
		'position' => 10,
		'max_suggestions' => 5,
		'tmpl_suggestion' => 'autocomplete-external-suggestion',
		'enabled' => true,
		'default_facet_filters' => [ 'facet:value' ]
	];
	$config[] = [
		'index_id' => 'external_index_1',
		'index_name' => 'External1_dev', // TODO: depends on environment
		'label' => __('External index 2', 'mysite'),
		'position' => 40,
		'max_suggestions' => 5,
		'tmpl_suggestion' => 'autocomplete-external-suggestion',
		'enabled' => true
	];
	return $config;
}
add_filter( 'algolia_autocomplete_config', 'my_algolia_autocomplete_config' );
```

> Do you feel like the plugin is overkill when you know what you actually want to build?

I feel like the plugin works very well when you want an "install, configure and it works" integration. But when you need to develop a complex and very custom integration, you'll have to override a lot of things and eventually you'll end up pretty much using only the indexing features (which are VERY useful).

It can (and I hope it will) be improved, but it's a good starting point for integrating Algolia with Wordpress.

I'll keep posting my use cases (and their solutions when I have them) as issues if it can help others (or maybe you prefer I post somewhere else?)

**Comment by rayrutjes** [comment]
Hi @Spone ,

We are currently moving foward with providing a PHP library that will allow developers to build robust pipelines between WordPress and Algolia. If you are interested in trying that out, I'd gladly give you access to a copy of it.

If so please DM me on [our forum](https://discourse.algolia.com/c/wordpress).

I'm closing this issue as we do not plan to add more features to this plugin given it is already complex enough to customize.
