### ISSUE TITLE
Scheduled posts showing up in search results.

### ISSUE THREAD

**Issue by andizer** [algolia/algoliasearch-wordpress#509]
### What did you expect to happen?
The scheduled post not being visible in the search results

### What happened instead?
The scheduled post is visible in the search results. This also happend in private browsing mode without being logged in.

### How can we reproduce this behavior?
Add a post with a scheduled date in the future. Search for it and it will be visibible. When pressing the result it will guide to a 404 not found page.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version: 1.7.0

**Comment by andizer** [comment]
Is there any news on this issue?

**Comment by rayrutjes** [comment]
Arg, sorry about the delay, I will try to tackle it tomorrow, bumping it up in the todolist.

Thanks for your patience and the friendly ping.

**Comment by rayrutjes** [comment]
Hi @andizer ,

I just tested creating a "future" post and it didn't get indexed.

By default, the post status should be "publish" to be indexed: https://github.com/algolia/algoliasearch-wordpress/blob/develop/includes/indices/class-algolia-posts-index.php#L67

Maybe you tried to override the 'should_index' with a filter? You mind sharing it?

**Comment by andizer** [comment]
I see what happened:

I've scheduled an already published post. This post was already indexed. When searching for it, it was visible in the results. By waiting a couple of minutes the search index was refreshed and it the post isn't visible anymore. 

After seeing this the first time. I've made some posts to reproduce the situation. But I was searching/looking for the post faster than the refresh of the search index was completed.

I think this issue can be closed. Thanks for looking to it. I'm sorry it was my mistake.

**Comment by rayrutjes** [comment]
No problem @andizer , sorry for the delay on our side, definitely not the response time I would like to provide!

Let me know if there if there is anything I can help you with.

FYI we are working on making the indexing simpler, by removing the whole queue mecanism that introduces custom post types and HTTP looping. We will also provide simple WP-CLI commands.

Stay tuned for that.
