### ISSUE TITLE
jquery libraries within bundle.min.js

### ISSUE THREAD

**Issue by crebacz** [algolia/algoliasearch-wordpress#51]
First of all, thank you for this plugin..I'm very excited by what you have put together here.  

Once I activated the plugin, I'm getting an error within chrome dev tools 
Uncaught Error: Syntax error, unrecognized expression: .asset.handle-lib/bundle.min.js.scripts

When I reviewed the bundle, I see that jquery, jquery ui, jquery touch punch are being loaded.  Each of these is included within WP; however, WP uses different versions.  

jQuery
WP (1.11.2) / Bundle (1.11.3)

jQuery UI
WP(1.11.4)/ Bundle(1.10.5)

TouchPunch
WP (0.2.2) / Bundle(0.2.2)

My site already is using jQuery and jQuery UI libraries (which I'm thinking is causing the error), and to avoid potential conflicts with other plugins, I do not want to dequeue those versions.  As such, is there any way to get an extensions bundle.js that does not include those libraries and just add the jquery/jquery ui dependencies within the enqueue scripts function?  

Thanks for any help/guidance you can provide on this.

**Comment by maxiloc** [comment]
@crebacz the bundle has been done in a way that there should not be any incompatibility with already imported jquery plugin. Everything is encapsulated inside the bundle so your issue should not be related to that.

Do you have a website where I can see the error ? Would help me a lot to investigate.

**Comment by crebacz** [comment]
Thanks @maxiloc for the quick response. There was a plugin conflict but I was able to get it fixed. So please feel free to close this issue.

**Comment by maxiloc** [comment]
@crebacz. Ok cool.
Did the error was due to the Algolia plugin ? If yes can you vive me a bit more details so that we can fix it for everyone.

**Comment by crebacz** [comment]
Don't think so. I am using the Member Mouse plugin and I hadn't updated it to the most recent version yet. Doing so fixed the issue. One of the changes in their update was to switch the copy of jquery ui they were using (1.10) to the version included with wordpress.  I had had issues with that earlier version of mm and gravity forms when gravity forms newest version was released.

Since the jquery versions you're using are similar to current wp, I don't think there is an issue yet. But there may end up being conflict issues in the future with other plugins, if one of those wp libraries is moved to a newer version.  With so many plugins out there and you never knowing what people will be using alongside algolia, I think it would be safer to remove the jquery libraries from the extension bundle and instead enqueuing the bundle js with those libraries listed as dependencies. Might save you some ticket headaches in the future. Plus it removes the redundant loading of scripts. 

Hope this helps.

**Comment by maxiloc** [comment]
@crebacz Thanks for your details.
