### ISSUE TITLE
Disable default results

### ISSUE THREAD

**Issue by will83** [algolia/algoliasearch-wordpress#510]
When i go to the search page (http://mydomaine.com/?s), I can see a list of results (probably latest elements saved in the database).

How can I disable this list ?

Thank you

**Comment by rayrutjes** [comment]
Hi @will83 

I'm unsure your issue relates to our plugin, and I currently don't see anything related to Algolia on your website.

The issue you encountered was probably related to the theme you use, and if so you should ask the workaround to the author.

Feel free to re-open this if I missed something or if you have more context.

Cheers,
