### ISSUE TITLE
Search Result Shows 1 Result Found - but no actual result

### ISSUE THREAD

**Issue by Sokos6** [algolia/algoliasearch-wordpress#511]
### What did you expect to happen?
When I search something on the site, I was expecting to see the search page return the result
### What happened instead?
When i searched woocommerce, it takes me to a page that says 1 result found in 1ms....but then no results are listed. When I look at dev tools, it gives this error. 
Uncaught TypeError: Cannot read property 'matchedWords' of undefined
    at eval (eval at m.template (underscore.min.js:5), <anonymous>:37:52)
    at c (underscore.min.js:5)
    at wp-util.min.js:1
    at u (instantsearch-preact.min.js:7)
    at t.value (instantsearch-preact.min.js:7)
    at O (instantsearch-preact.min.js:6)
    at t.render (instantsearch-preact.min.js:6)
    at T (instantsearch-preact.min.js:7)
    at T (instantsearch-preact.min.js:7)
    at N (instantsearch-preact.min.js:7)

### How can we reproduce this behavior?
You can search on anotherlineofcode.org
Can you provide a link to a page which shows this issue?
https://anotherlineofcode.org/?s=woocommerce
### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version:
1.7.0

**Comment by rayrutjes** [comment]
Hi @Sokos6 ,

Did you customize the index settings in the Algolia dashboard?
The default templates rely on the default configuration we push.

If you change the settings manually you also have to adapt the templates.

**Comment by Sokos6** [comment]
I didn't do anything to the settings in the Algolia dashboard. Are you able to take a look at the link I added, or my account and see what's going on? I just want my search results to show up...if not I need to switch back to the default search, or just hook in google search.

**Comment by rayrutjes** [comment]
@Sokos6 without further logging information (PHP + Logs page of the plugin), I'm afraid I won't be able to troubleshoot this further.

From the JS error message, it looks like the default index settings have been altered from the Algolia dashboard.

Could you try deleting all indices, reindex again and try it out?

If it doesn't work, please feel free to re-open this and please provide us with more context.
