### ISSUE TITLE
InstantSearch not showing all product categories, limited to 10

### ISSUE THREAD

**Issue by SolidDev** [algolia/algoliasearch-wordpress#516]
**What did you expect to happen?**
I expected the InstantSearch filter for product categories to list all product categories with products assigned to them. 

**What happened instead?**
Only 10 product categories are listed. I am unsure how these specific 10 are chosen.

**Technical info**
WP 4.7.2
Search by Algolia 1.7.0
Algolia Search for WooCommerce 0.7.0

**Comment by rayrutjes** [comment]
Hi @SolidDev ,

As of today, the plugin you are using does not provide a solution to change this. However, you could edit the `templates/woocommerce-instantsearch.php`, and add the 'limit' attribute:

```js
/* Categories refinement widget */
			search.addWidget(
				instantsearch.widgets.hierarchicalMenu({
					container: '#facet-categories',
					separator: ' > ',
                                        limit: 50, // this is the added line
					sortBy: ['count:desc', 'name:asc'],
					attributes: ['taxonomies_hierarchical.product_cat.lvl0', 'taxonomies_hierarchical.product_cat.lvl1', 'taxonomies_hierarchical.product_cat.lvl2'],
					templates: {
						header: '<h4>' + algolia.woocommerce.i18n.product_categories + '</h4>'
					}
				})
			);
```

I hope that helps!
