### ISSUE TITLE
Indexing not working

### ISSUE THREAD

**Issue by samukuhn** [algolia/algoliasearch-wordpress#519]
### What did you expect to happen?

#My page should be indexed.

### What happened instead?

Nothing. The queue status is 'Idle' and there are 18 pending tasks.	

Can you provide a link to a page which shows this issue?
www.wec-international.de

### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version: 1.7.0 

<img width="450" alt="bildschirmfoto 2017-03-02 um 08 31 40" src="https://cloud.githubusercontent.com/assets/8793212/23497386/1d1286b2-ff23-11e6-8bd9-ba94c6b71f64.png">

**Comment by rayrutjes** [comment]
Hi @samukuhn ,

Can you tell us if you have something on your logs screen? 
Otherwise could you enable and check the PHP errors: https://community.algolia.com/wordpress/logs.html

Thank you.

**Comment by rayrutjes** [comment]
I'm closing this due to some period of inactivity. Feel free to re-open with additional context that would help us troubleshoot the issue.
