### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by crebacz** [algolia/algoliasearch-wordpress#52]
Hello--

The more i've been testing your plugin, the more I'm liking how you have set it all up.  I do have a couple of questions that I'm hoping you can help me answer.  

1.  First, I know that another issue was opened and subsequently closed regarding excerpts.  Your response makes sense; however, I'm having a similar issue because we create custom excerpts for our articles. The critical reason for this involves short codes: for example, if we open an article with a short code (like a video), then the short code syntax is what appears in the excerpt within the search results. I know you mentioned the attributesToSnippet as an option.  How would this work?  Is there a way to connect that attributes function to a post's excerpt that is already saved in the database? 

2. Is there a way to add filters to the search request sent to Algolia?  In our situation, we use a membership plugin to protect content based on post type and category depending on user role.  The facetable section you offer is great, but there are some facets I would not want certain users to ever see.  I'm currently using a pre_get_posts filter for standard WP Query to filter results.  I looked inside the Query Replacer class but didn't see a hook for adding/modifying the query.  Any suggestions on this?  

Thank you for your plugin and your time!

**Comment by maxiloc** [comment]
@crebacz 
1. If you want to use the excerpt you created the best way is too uncomment the line mentionned in the issue #37 => https://github.com/algolia/algoliasearch-wordpress/blob/master/core/WordpressFetcher.php#L218
The excerpt in Wordpress should be a "summary" of the content. So for most the cases it does not make sense to search into the except when you have a good way to search into the content. 
I am gonna re-open #37 and look for a way to handle this in a better way, right now it is not perfect.
2. Yes QueryReplacer is only for backend search, it is here as a fallback of the javascript search. You need to modify the js helper code on the template. For the default js template it is here => https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/default/template.js#L547-L563
You need to add the facet to the search and then add the filter in the performQueries function

We are working on v1.0 and those things should be easier to configure very soon :smile:
