### ISSUE TITLE
Options not reflecting updates in instantsearch

### ISSUE THREAD

**Issue by jmandala** [algolia/algoliasearch-wordpress#520]
### What did you expect to happen?
When plugin options are updated, these new values should be used on the instantsearch functionality on the front end.

### What happened instead?
The first values entered were used.

### How can we reproduce this behavior?
Setup the plugin. Ensure that instant search works. Then change the index prefix. The new indices are created. Now perform a search on the front end. The old index is used!

### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version: 1.7.0

**Comment by rayrutjes** [comment]
Thank you for reporting this. I understand that changing the index prefix isn't reflected in the frontend instantsearch.
Are you using any caching plugin? Instantsearch should use the up to date value of the index.

**Comment by jmandala** [comment]
No caching plugin that I'm aware of. I'll check more closely.

**Comment by rayrutjes** [comment]
Hi @jmandala , I'm closing this for now, being unable to re-produce it.

Please feel free to give more context if the problem persists.
