### ISSUE TITLE
Need to index taxonomies (product categories/brands) when post type (products) updated

### ISSUE THREAD

**Issue by smuddin** [algolia/algoliasearch-wordpress#521]
### What did you expect to happen?
When products were updated, I want the plugin to check products taxonomies and if they were indexed or not. If not indexed, then the plugin need to index those taxonomies.

Current updated version of the plugin does not do that. Which leaves us with an issue, when we
1. Add a taxonomy (product category/brand)
2. Update some product and assign newly added taxonomies to that product
3. Autocomplete does not show that taxonomy. We have to manually update the taxonomy to index.

This is painful, when you have 400+ taxonomies in the store.

Would be nice if the plugin check taxonomies in both ways. That is, if we uncheck a taxonomy when updating a product, the plugin need to check the number of products assigned to that taxonomy. If it's zero then we need to delete that index too.

### How can we reproduce this behavior?
1. Add a taxonomy
2. Update a product with that taxonomy assigned
3. Check autocomplete, if the taxonomy shows up or not.

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 2.6.6

**Comment by rayrutjes** [comment]
Hi @smuddin ,

Unfortunately this is indeed not the current behaviour and would add even more complexity to the current way we index data.

What I would recommend in your case would be to trigger a full re-index from time to time.

You can also trigger this from the server with [WP-CLI](https://community.algolia.com/wordpress/wp-cli.html).

If you feel like doing a PR to add this feature, I'd gladly give it a look.
