### ISSUE TITLE
How to stop from searching the word "Search" when Search box is clicked with no value.

### ISSUE THREAD

**Issue by gregvissing** [algolia/algoliasearch-wordpress#522]
### What did you expect to happen?
When a user clicks the Search box the placeholder goes away with the cursor blinking waiting for something to be typed.

### What happened instead?
A box of results opens up below Search box with the results for the word "Search" on the website. I don't want it to search the word "Search" with no value in search box as shown in the screenshot below.
https://github.com/gregvissing/gregvissing.github.io/blob/master/img/Algolia-search.png

### How can we reproduce this behavior?
Click on the Search box.

Can you provide a link to a page which shows this issue?
http://4aa.82e.myftpupload.com/ask-us/

### Technical info
* WordPress version: 4.7.3
* Algolia Search plugin version: 1.7.0

**Comment by rayrutjes** [comment]
Hi @gregvissing , it looks like the 2 links are not available for now.

I'm closing this for now, feel free to re-open if necessary.
