### ISSUE TITLE
docs: "Categorie" instead of "Category" in screenshot

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-wordpress#525]
### What did you expect to happen?
The singular form of "categories" is "category", and that's what should be written in the screenshot

### What happened instead?
The screenshot displayes "Categorie" instead

### How can we reproduce this behavior?
You can see it on the [website](https://community.algolia.com/wordpress/) (right column of the screenshot):
![image](https://cloud.githubusercontent.com/assets/283419/24038312/27d825c2-0b01-11e7-81ef-12ecc6b69951.png)

**Comment by rayrutjes** [comment]
This is currently reflecting the default singular names provided by WordPress for the post types.
