### ISSUE TITLE
No listIndexes() function

### ISSUE THREAD

**Issue by blackjacques** [algolia/algoliasearch-wordpress#528]
### What did you expect to happen?
I'd like to verify that the index name is valid using PHP:

include_once(WP_PLUGIN_URL . '/algoliasearch-wordpress-master/lib/algolia/algoliasearch.php');
$algolia_client = new \AlgoliaSearch\Client('appid', 'apikey');
$indexes = $algolia_client->listIndexes();  //fails

### What happened instead?
The listIndexes() function fails and causes a 500 server error.

### How can we reproduce this behavior?
Call the function using PHP code.

Can you provide a link to a page which shows this issue?
No

### Technical info
* WordPress version:  4.7.3
* Algolia Search plugin version: 0.1

**Comment by rayrutjes** [comment]
Hi @blackjacques ,

To be able to use the listIndexes function you need to use an Admin API key which you can find on this screen: https://www.algolia.com/api-keys

Can you confirm you used the admin API key?

Could you give us the full stack trace of the error maybe?

PS: you shouldn't not expose your api keys publicly. I've edited your initial request to remove that information.

**Comment by blackjacques** [comment]
Hi Raymond,

That just might be the problem, because I am using the Search-Only API Key.  I’ll try it again with the Admin one.

Interestingly, because I am instantiating the \AlgoliaSearch\Client within the do_feed_rss2 WordPress hook, calling the client->listIndexes() just results in a 500 server error with no output whatsoever.  I have not yet figure out a way to catch such errors.  Too bad there isn’t some kind of error thrown that says “You need to use the Admn API”.

Thanks,

Rob

**Comment by blackjacques** [comment]
Are any errors thrown when you reference an invalid index using PHP code such as:

$algolia_client->initIndex($index_name);

If so, can you provide me with a snippet of the catching part?  Something like:

catch (AlgoliaException $e) {
        echo '{"error": "' . str_replace('"', "", $e->getMessage()) . '"}';
        return;
}

Thanks!

Rob G

**Comment by rayrutjes** [comment]
`initIndex` only creates a new instance of `Index`, it doesn't trigger any API call and should not throw any exception.

Regarding the 500 error, you should enable the logging to check the exact error message: https://community.algolia.com/wordpress/logs.html

Let me know what the error is.

**Comment by blackjacques** [comment]
I think that you are correct that the 500 error is being caused by the client being defined by the Search-Only API Key.
Although using the Admin key instead would provide a way to check if the index is valid, I'm a little reluctant to use it for a query script. 
Is there a way to check that an index name is valid using the Search-Only API Key?  Would the call to the search() function fail in some way when the index is new or would it only return zero rows?

Rob

**Comment by rayrutjes** [comment]
If the index does not exist and your try to `search` on it, it will indeed throw an exception.
You should definitely not use the Admin API key for search operations in the frontend.

**Comment by blackjacques** [comment]
Great!  Should I catch an AlgoliaException or will the Base Exception suffice?

catch (AlgoliaException $e) {
    $products = $index->search(trim($_GET['prod_name']), $algolia_config_settings);
     echo '{"error": "' . str_replace('"', "", $e->getMessage()) . '"}';
 return;
 }

**Comment by rayrutjes** [comment]
Both will work, but the more specific the better.

**Comment by blackjacques** [comment]
Sounds good.

Thanks for all your help!
