### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by Salamander3** [algolia/algoliasearch-wordpress#532]
### What did you expect to happen?
I finished indexing all and went to the plugin settings and selected:
"Use Algolia with Instantsearch.js" Hoping to see search results but instead the page looks broken and no results show.

### What happened instead?
The search page show no results only a magnifying glass icon outside the content area, and this errors on console: 
![untitled](https://cloud.githubusercontent.com/assets/8179611/24413101/bb7ac8c0-13da-11e7-8759-63ce003f162b.jpg)

### How can we reproduce this behavior?
Install algolia on newsmag theme.
https://themeforest.net/item/newsmag-news-magazine-newspaper/9512331

Can you provide a link to a page which shows this issue?
I disabled it can't have it live broken.

### Technical info
* WordPress version: 4.7.3
* Algolia Search plugin version: 1.7.0

**Comment by Salamander3** [comment]
On the FAQ it says it's compatible with any wordpress theme but not with newsmag it seems. You'll have to buy newsmag to test i guess. Not sure if there's interest on making compatible.

**Comment by Salamander3** [comment]
Instant search works, but only on desktop, not on mobile.

**Comment by rayrutjes** [comment]
@Salamander3 can you check if your theme correctly uses the 'wp_footer' in the template somewhere?

**Comment by Salamander3** [comment]
Yes search.php calls:
```
<?php
get_footer();
?>
```

**Comment by rayrutjes** [comment]
No the function is `[wp_footer()](https://codex.wordpress.org/Function_Reference/wp_footer)`.
This method should be present in the theme according to WordPress best practices.

**Comment by Salamander3** [comment]
I don't think newsmag follow best practices. Their theme is a resource hog on busy sites with so many ajax requests saturating mysql. I'll regret buying it. Hopefully i'll be able to get a light good theme that will do things right and work with algolia. Sorry for all the trouble.
