### ISSUE TITLE
Using the search in a single place only.

### ISSUE THREAD

**Issue by rameden** [algolia/algoliasearch-wordpress#534]
I was wondering if there is a way to _not_ use the Algolia search on a search from. We would like to use this in our global search but not in another search we have.

Thanks!

**Comment by rayrutjes** [comment]
Yes, you can do so by implementing a custom template for the autocomplete experience, and then changing the selector for the input.

https://community.algolia.com/wordpress/customize-autocomplete.html#disable-autocomplete-on-certain-search-inputs

I hope that helps.

**Comment by rameden** [comment]
Worked perfect! Thanks!

**Comment by rayrutjes** [comment]
You are very welcome ;)
