### ISSUE TITLE
post_excerpt not displayed in search results

### ISSUE THREAD

**Issue by SRUC** [algolia/algoliasearch-wordpress#538]
I have implemented Search by Algolia on a test install and configured to search across a number of custom post types. Alongside pages and posts, I am indexing custom post types which contain only post_title, post_excerpt plus a post_meta field which is used to store a link to a downloadable file.

I expected that Algolia would display post_excerpt under post_title in search results for these custom posts, however results are showing only post_title. This seems similar to #37 and I am not sure how to resolve.

### Technical info
* WordPress version: 4.7.4
* Algolia Search plugin version: 1.7.0

**Comment by rayrutjes** [comment]
This will be the default behaviour in next major release. Please bear with us.
