### ISSUE TITLE
Error by activating plugin.

### ISSUE THREAD

**Issue by rahuledukart** [algolia/algoliasearch-wordpress#54]
Fatal error: Uncaught exception 'Exception' with message 'AlgoliaSearch requires the CURL PHP extension.' in /var/www/html/edukart/wp-content/plugins/algoliasearch-wordpress-master/lib/algolia/algoliasearch.php:132 Stack trace: #0 /var/www/html/edukart/wp-content/plugins/algoliasearch-wordpress-master/core/AlgoliaHelper.php(16): AlgoliaSearch\Client->__construct('T265CTWUG6', '253ba4ae34e4d2b...') #1 /var/www/html/edukart/wp-content/plugins/algoliasearch-wordpress-master/AlgoliaPlugin.php(21): Algolia\Core\AlgoliaHelper->__construct('T265CTWUG6', '470b300485f3876...', '253ba4ae34e4d2b...') #2 /var/www/html/edukart/wp-content/plugins/algoliasearch-wordpress-master/algolia.php(32): AlgoliaPlugin->__construct() #3 /var/www/html/edukart/wp-admin/plugins.php(151): include('/var/www/html/e...') #4 /var/www/html/edukart/wp-admin/plugins.php(153): plugin_sandbox_scrape('algoliasearch-w...') #5 {main} thrown in /var/www/html/edukart/wp-content/plugins/algoliasearch-wordpress-master/lib/algolia/algoliasearch.php on line 132

**Comment by redox** [comment]
HI @rahuledukart,

> Uncaught exception 'Exception' with message 'AlgoliaSearch requires the CURL PHP extension.

You need to install the CURL PHP extension.

**Comment by rahuledukart** [comment]
I had installed Curl using *apt-get install curl* and *restart my server*
but again i am facing the same error.


--
Rahul

*Thanks & Regards,*
*Rahul Rai*

*Associate Software Developer**Edu*
*Kart.com*
Mob.- +918750383730

**Comment by redox** [comment]
> I had installed Curl using *apt-get install curl* and *restart my server*
> but again i am facing the same error.

You should install the `php5-curl` package like in http://askubuntu.com/questions/9293/how-do-i-install-curl-in-php5

**Comment by adam1920** [comment]
$ sudo apt-get install php-curl
