### ISSUE TITLE
How to additionally filter search results, without screwing up pagination?

### ISSUE THREAD

**Issue by farmerpaul** [algolia/algoliasearch-wordpress#560]
Hey there. I'm fairly new to Algolia and your great plugin, but everything's pretty well documented and I seem to be getting a decent feel for it. This WP site I'm working on is using your service and plugin to index custom post types – courses, lessons, and so on – which are provided by a fork of the Zippy Courses WP plugin. Basically, the site offers online courses to various cohorts of students, and we want students to be able to do a keyword search through the lessons – but only returning lessons that they have access to.

Students who are registered for a given course don't have access to all lessons at once. Each user's permission to access any given lesson (which is a custom post type that we're using Algolia to index) is determined by a function call within the Zippy Courses plugin.

So, if we just use the Algolia search plugin as-is to display relevant search results, it won't do this permission check for each returned post. It just lists them all, whether or not the logged in student should be able to see them. Or rather, it _tries_ to show them all, but some excerpts fail to render properly due to lack of proper permissions for the currently logged in student.

Now, I could just modify the `search.php` template within the theme we're using and do the permission check within the loop, but then we'll end up with some pages showing 9 results, some showing 3, some showing 10, some showing none, etc. I want the results filtered for permissions _before_ this pagination happens.

How might I do this with Algolia?

**Comment by farmerpaul** [comment]
I've been trying to think of a way to do this… some thoughts:

1. If possible with Zippy Courses (not sure if even is, though), generate a list of the post IDs of the custom post types (lessons, etc.) that the current student has access to, then hook into Algolia's search parameters so that it additionally filters by post ID – restricting results to only those post IDs provided. Although, it doesn't seem like Algolia even has an `IN` operator, so I'd probably have to send a bulky query involving lots of `OR` clauses.
2. If that's not possible, then just get Algolia to return _all_ resulting post IDs, then hook into `pre_get_posts` (_after_ Algolia's `pre_get_posts` hook), iterate through all the posts and check the access permission, generate a new list of post IDs and replace `WP_Query`'s `post__in` array with that list, and get `WP_Query` to do the paging.

From what I can tell so far, option 1 might not be possible because Zippy Courses doesn't seem to have a function to query available lessons by student. Can only just take a post ID and check it.

For option 2, Algolia doesn't seem to give me a way to return _all_ search results, but I guess the limit of 1000 will suffice…

If anyone has any better ideas, they'd still be appreciated…

**Comment by rayrutjes** [comment]
Hi @farmerpaul ,

Unfortunately what you try to achieve is not what the plugin is designed for.
It is probably do-able but would need some extensive usage of hooks here and there.

Maybe ask this question on our forum here: https://discourse.algolia.com/c/wordpress
I know that some of our users did manage to provide scoped search for different users.
