### ISSUE TITLE
Method is_wpml_enabled doesn't work when Polylang is installed

### ISSUE THREAD

**Issue by GaetanFa** [algolia/algoliasearch-wordpress#567]
The **is_wpml_enabled** method in \includes\class-algolia-compatibility.php does't work as expected when Polylang is installed and not WPML.

Indeed this method checks if the WPML function **icl_object_id** exists but Polylang sets this function too.
A fatal error is then encountered due to the variable **sitepress** which is not set.

### Technical info
* WordPress version: 4.7.4
* Algolia Search plugin version: 2.0.0
* Polylang plugin version : 3.3.2

**Comment by rayrutjes** [comment]
That is very unfortunate, thanks for reporting it.
That being said, it is the WPML recommended way of detecting if WPML is enabled.

Do you have a Polylang specific method I could call to check if Polylang is there?

Could you share the error message?

**Comment by GaetanFa** [comment]
The message is :
```
Fatal error: Call to a member function get_current_language() on a non-object in .../plugins/search-by-algolia-instant-relevant-results/includes/class-algolia-compatibility.php on line 34
```

You can check if the class Polylang exists, this is my awaiting hack :

```
private function is_wpml_enabled()
{        
	return function_exists( 'icl_object_id' ) && !class_exists('Polylang');
}
```

**Comment by rayrutjes** [comment]
That makes a lot of sense @GaetanFa , let me push that. Thanks a ton.

**Comment by GaetanFa** [comment]
Thank you @rayrutjes !
