### ISSUE TITLE
Skipping product while Indexing

### ISSUE THREAD

**Issue by deepankarpathak** [algolia/algoliasearch-wordpress#58]
By default, Algolia index all Published items. Can we Skip any products / article based on attribute (condition)? 

Also, can we cronjob website indexing?

**Comment by redox** [comment]
The ability to skip/remove items from the the indexing has been mentioned in #44.

We can create a new issue about the cron-based indexing, which can probably make sense for big use-cases.

**Comment by maxiloc** [comment]
Closing this in favor of #63
