### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by poisa** [algolia/algoliasearch-wordpress#583]
### What did you expect to happen?
See any of the Algolia setting pages in the WP admin.

### What happened instead?
Blank page. HTTP 500 error. PHP logs said "Operations quota exceeded, change plan to get more Operations."

### How can we reproduce this behavior?
Create a free account, let it lapse past the first month. This error starts happening if you don't manyally set your account to FREE. The operations counter on the Algolia dashboard actually shows 0 but the PHP error log says you are above the quota because there is no actual plan selected. If you switch to the free plan this error goes away.
I was expecting the plugin to not throw a 500 but instead let me know in the interfase. For non tech saavy people this would definitely mean "this plugin is broken" when in fact the problem is that Algolia doesn't default to the FREE plan when the 1st month pases.

### Technical info
* WordPress version: 4.7.4
* Algolia Search plugin version: 2.2.1

**Comment by rayrutjes** [comment]
Thanks for reporting this @poisa ,

I will make sure we handle this properly.
