### ISSUE TITLE
wordpress woocommerce problem

### ISSUE THREAD

**Issue by asritad** [algolia/algoliasearch-wordpress#59]
so i have this wordpress woocommerce website and i installed this plugin and everything done as per mentioned and at last when clicked on reindexing needed (4646 records) it shows ok till 4% but when the bar progresses to 8% the page gets filled up with warnings.

Warning: array_keys() expects parameter 1 to be array, null given in /home/mart4all/public_html/wp-content/plugins/algoliasearch-wordpress-master/algolia.php on line 93

Warning: in_array() expects parameter 2 to be array, null given in /home/mart4all/public_html/wp-content/plugins/algoliasearch-wordpress-master/algolia.php on line 93

these 2 warnings repeats again and again.

**Comment by maxiloc** [comment]
Fixed on develop
