### ISSUE TITLE
New task sync_item was queued. error in wordpress database

### ISSUE THREAD

**Issue by duplich** [algolia/algoliasearch-wordpress#592]
### What did you expect to happen?
Work without error tasks in my database. 
### What happened instead?
![task_sync-algolia](https://cloud.githubusercontent.com/assets/3776355/26169041/95a62eda-3b3c-11e7-9207-60c93a52a13a.jpg) like 300+ of those items

### How can we reproduce this behavior?
I do not know. It seems to happen when auto update is triggered.

### Can you provide a link to a page which shows this issue?
I can not. The  problem happens in the backend dashboard. On the front end I have setup the template that shows only posts with post_status=publish. Theme is custom made, using Timber (but I think this has nothing to do with the error)

### Technical info
* WordPress version: 4.6.6
* Algolia Search plugin version: 1.6.0

I am using the pluggin in the Multisite environment. It is anoying to have 300 private posts with the same title (see the image above).  Is there anyone else seeing this error?

**Comment by rayrutjes** [comment]
Hey @duplich ,

This has been addressed starting from version 2.x.
Make sure you read the changelog before updating, and use a staging environment: https://wordpress.org/plugins/search-by-algolia-instant-relevant-results/#developers

If you previously overwrote the autocomplete.php or instantsearch.php template, you will need to take into account the new files. See: https://community.algolia.com/wordpress/upgrade.html#from-v1-7-0-to-v2-0-0

In any case, you will need to re-index your indices after the update.

Once you upgraded, you can safely delete all those private custom post types.

I hope that helps.

**Comment by duplich** [comment]
Hey @rayrutjes Thanks a lot, The update solved my problem. Everything works fine now. And the search seems even faster than before. Amazing Service :)

**Comment by rayrutjes** [comment]
You are welcome, glad the upgrade went smoothly.
Feel free to check out our Forum and why not share your project there ;)

https://discourse.algolia.com/tags/wordpress

Cheers!
