### ISSUE TITLE
Why can't I use the already indexed wp_searchable_posts with autocomplete?

### ISSUE THREAD

**Issue by afuggetta** [algolia/algoliasearch-wordpress#595]
### What did you expect to happen?
Enable Autocomplete without the need to re-index duplicate records to a new index.
I would want to use the already indexed wp_searchable_posts, ideally with the possibility to filter at query time. This was not an issue on older versions of the plugin.
There may be a hook for this already but it seems like the documentation is not updated to the latest plugin.

### What happened instead?
I get a WordPress error notice asking to select one or multiple indices for Autocomplete to work. 

### How can we reproduce this behavior?
Enable Autocomplete and do not select any indices.

Can you provide a link to a page which shows this issue? Not yet - this is on a sandbox for the moment.

### Technical info
* WordPress version: 4.7.5
* Algolia Search plugin version: 2.2.3

**Comment by rayrutjes** [comment]
Thanks for reporting this. Will try to solve this for you next week.
In the meantime, you should be able to hack your way around with the `algolia_autocomplete_config ` filter.

I indeed need to refresh the docs, which is a bit outdated. This is on my todolist.

**Comment by afuggetta** [comment]
Thanks, @rayrutjes!

Appreciate the quick response. I will try to use that filter in the meantime.

Andrea

**Comment by rayrutjes** [comment]
This will be possible from the Autocomplete admin screen starting from next version 2.4.0.

Stay tuned!
