### ISSUE TITLE
Deleted attachment are not deleted from Algolia index

### ISSUE THREAD

**Issue by BenjTa** [algolia/algoliasearch-wordpress#596]
### What did you expect to happen?

If you delete a post in Wordpress it delete it via the function wp_delete_post() which call the hook 'before_delete_post' ... The post is deleted from Agolia Index via this Hook in \wp-content\plugins\search-by-algolia-instant-relevant-results\includes\watchers\class-algolia-post-changes-watcher.php
=> It works as expected

But if you delete a media from wordpress media librairy it delete the post via the function wp_delete_attachment() which call a different hook do_action( 'delete_attachment', $post_id );
This hook is not implemented in algoliasearch-wordpress so the media is deleted from wordpress but not in the Algolia index.

### How can we reproduce this behavior?

You can add a new media via the wordpress media librairie, index it in algolia, delete the media from the media librairie, the media is still index in Algolia

### Solution ###
Maybe you can just add the delete_attachment hook as you did for the post hook before_delete_post ...

Kind regards,
Benjamin

**Comment by rayrutjes** [comment]
Thanks for reporting this one. 
Would you like to provide a PR?

**Comment by BenjTa** [comment]
Hi,
Sorry but what do you mean by "PR" ?

**Comment by rayrutjes** [comment]
Hey, 

By PR I meant Pull Request, which is the name of a contribution you can do on GitHub.
If you are not comfortable submitting a pull request, I'll try to find sometime to do this.

Thanks again for the feedback,

Cheers,

**Comment by GaetanFa** [comment]
Hi @rayrutjes 

@BenjTa and i work together, there is the PR : #599
We just add the 'delete_attachment' hook, attachment are correctly removed from the index with it.

Thanks

**Comment by rayrutjes** [comment]
Perfect @GaetanFa thanks a lot.
The PR looks good to me.

**Comment by rayrutjes** [comment]
PR has been merged in #606 

Will release soon.
