### ISSUE TITLE
Wordpress Indexing Problem

### ISSUE THREAD

**Issue by deepankarpathak** [algolia/algoliasearch-wordpress#60]
It seems some issue with Algolia indexing on server. It is showing 100% complete but no data is shown on Algolia front. 

it is showing empty array error on website plguin. 

Algolia logs - http://snag.gy/GJiRn.jpg
Website Screenshot - http://snag.gy/86HsM.jpg

**Comment by maxiloc** [comment]
Did you modify the extension code ? Seems like there is a debug + die
