### ISSUE TITLE
Indexing not present in side menu

### ISSUE THREAD

**Issue by gendall** [algolia/algoliasearch-wordpress#601]
### What did you expect to happen?
'Indexing' page not visible in sub-menu of Algolia. Have tried deactivating plugins and switching themes. Only options visible are 'Autocomplete', 'Search Page'  & 'Settings'

![screen shot 2017-05-24 at 11 41 59](https://cloud.githubusercontent.com/assets/4195265/26399752/0ee8d07a-4076-11e7-92ea-5308806eb6f5.png)

### Technical info
* WordPress version: 4.7.5
* Algolia Search plugin version: 2.2.3

**Comment by gendall** [comment]
Hi @rayrutjes 

We wanted to exclude certain post types. Do we now do this in the functions file?

**Comment by rayrutjes** [comment]
Hi @gendall ,

To exclude post types for the autocomplete dropdown, you can do this on the autocomplete screen.

For excluding post types from the search page, you indeed need to use a filter, but that was already the case before.
Here you will find more information: https://community.algolia.com/wordpress/indexing-flow.html#indexing-decision

I hope that helps.

**Comment by gendall** [comment]
Awesome. Thanks @rayrutjes

**Comment by rubas** [comment]
@rayrutjes 
How do you sync with the current version `wp_searchable_posts`?

We use the plugin to sync the data only to Algolia and use instantsearch.js manually in our templates.

**Comment by rayrutjes** [comment]
Hey @rubas do you mind opening a new issue explaining your use case more in detail?

Thanks a bunch. Closing this one given the initial subject has been addressed.
