### ISSUE TITLE
ALGOLIA_SPLIT_POSTS causing PHP errors 

### ISSUE THREAD

**Issue by chiplay** [algolia/algoliasearch-wordpress#603]
### What did you expect to happen?
I'm using the latest version of the Algolia Wordpress plugin (2.2.3) and just attempted to use the `ALGOLIA_SPLIT_POSTS` constant to prevent post splitting when I started getting some php errors:

`PHP Warning:  Invalid argument supplied for foreach() in /www/wp-content/plugins/search-by-algolia-instant-relevant-results/includes/indices/class-algolia-posts-index.php on line 99`

I'm pretty sure [this refactor](https://github.com/algolia/algoliasearch-wordpress/commit/3925e219bf244413c261eab3ea7f2314099dac81#commitcomment-22308111) is causing the issue, though my php is a little rusty and I'm not exactly sure why $parts would be invalid. Thanks for taking a look!

### Technical info
* WordPress version: 4.7.5
* Algolia Search plugin version: 2.2.3

**Comment by rayrutjes** [comment]
Thanks @chiplay ,

Will take a look as soon as possible.

**Comment by chiplay** [comment]
@rayrutjes no problem - and thank YOU for this amazing plugin.  We're building our new CMS off this WP -> Algolia auto-indexing solution and it's pretty amazing so far.

**Comment by rayrutjes** [comment]
Thanks for reporting this @chiplay .

Will release ASAP.
