### ISSUE TITLE
Cannot find or sync "usermeta" index

### ISSUE THREAD

**Issue by WinstonGFX** [algolia/algoliasearch-wordpress#604]
### What did you expect to happen?
In the Wordpress backend, on the Autocomplete page, I expect "usermeta" to be an index name available to me. This is different than the "users" index which holds a very limited number of fields whereas "usermeta" can hold custom fields.

### What happened instead?
"usermeta" is not an option.

### How can we reproduce this behavior?
Visit the Autocomplete page in any Wordpress backend.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.7.5
* Algolia Search plugin version: 2.2.3

**Comment by rayrutjes** [comment]
Thanks for reporting this @WinstonGFX , I will investigate.
If you have a solution please submit a PR.

**Comment by Mamaduka** [comment]
'usermata' shouldn't be indexed separately as it only holds data related to 'users' table (relation via 'user_id').

@WinstonGFX you should hook into `algolia_user_record` and add any custom user meta manually.

**Comment by rayrutjes** [comment]
I'm closing this for now, I hope @Mamaduka 's answer is helpful.

Let me know if there is anything else we could help with.

**Comment by WinstonGFX** [comment]
Adding user data to `algolia_user_record` has been successful, but I'm having an interesting added issue:

In my Algolia backend, users are only indexing and showing if the user has published a post. Any users with zero posts is not included. I assume it is something in `functions.php`, any idea how to get all users indexed?

**Comment by rayrutjes** [comment]
Hey @WinstonGFX ,

Indeed, by default we only index [users that have at least one post](https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-users-index.php#L26).

To index everyone, you can add the following to your `functions.php` file:

```php
add_filter( 'algolia_should_index_user', '__return_true' );
```

You will need to "re-index" all users from the "autocomplete" page of the plugin.
