### ISSUE TITLE
[docs]: Missing icons for community projects

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-wordpress#611]
### What did you expect to happen?
I wanted to see icons for each of the Algolia Community projects

### What happened instead?
I saw some icons missing
![image](https://cloud.githubusercontent.com/assets/283419/26753198/59de3e24-4861-11e7-84a2-be016cb8ce01.png)

### How can we reproduce this behavior?
Hovering the "Community" part on top of the screen

Can you provide a link to a page which shows this issue?
https://community.algolia.com/wordpress/

cc @JonasBa @LukyVj I saw the issue on other community website but I'm not sure where the image should be loaded from? Cloudinary? Website of the linked project? Website of the current project?

**Comment by JonasBa** [comment]
Thanks @pixelastic I'll take a look.

**Comment by rayrutjes** [comment]
It looks like it is fixed now. Did you handle this @JonasBa ?

**Comment by JonasBa** [comment]
yes, sorry I forgot to close this :)

**Comment by rayrutjes** [comment]
No problem, thanks for taking care of it @JonasBa !
