### ISSUE TITLE
Access a Post's Featured Image at a Size Other than Thumbnail

### ISSUE THREAD

**Issue by WinstonGFX** [algolia/algoliasearch-wordpress#617]
### What did you expect to happen?

I'm able to output the post featured image to the frontend using 'images.thumbnail.url', but it only allows me to post the thumbnail size image at 150x150px. I'd like my instantsearch results to be able to access and post another size such as the medium and/or large image sizes. Is this possible?

### What happened instead?

Index only has access to 'images.thumbnail.url' which is 150x150

### How can we reproduce this behavior?

View an index of Wordpress posts that has a featured image attached.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version:
4.8

* Algolia Search plugin version:
2.3.0

**Comment by rayrutjes** [comment]
Hey @WinstonGFX , I just added the answer to the frequently asked question.
See PR #618 .

Let me know if that helps.
