### ISSUE TITLE
restart.sh does not index well products it seems

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-wordpress#62]
![2015-09-20-223844_595x755_scrot](https://cloud.githubusercontent.com/assets/123822/9982812/67f58e44-5fe8-11e5-966a-f4cfc313b6e6.png)

I get empty products and data in my index after running the script.
![2015-09-20-223926_1224x327_scrot](https://cloud.githubusercontent.com/assets/123822/9982815/760a0578-5fe8-11e5-89ed-3bfae5e007f9.png)

**Comment by redox** [comment]
Default configuration is broken right now. Go to the 1st tab and use the "Reset Configuration" button, then reindex.

**Comment by redox** [comment]
https://github.com/algolia/algoliasearch-wordpress/issues/53

**Comment by vvo** [comment]
Ok, to avoid a third developer spending time on this @maxiloc do you know how to fix this for good? I can help but no easy clues. I am sure you know :)

**Comment by maxiloc** [comment]
yep I am on it
