### ISSUE TITLE
PHP Notices in WP-CLI command

### ISSUE THREAD

**Issue by Mamaduka** [algolia/algoliasearch-wordpress#624]
When running `wp algolia re-index <indexName>`, it generates following PHP notice:
```
[25-Jun-2017 16:28:36 UTC] PHP Notice:  Undefined index: all in /app/public/wp-content/plugins/algoliasearch-wordpress/includes/class-algolia-cli.php on line 50
```

Few other notes regarding CLI code:

- Fix coding standards to match one used across the plugin. Which I think is mix of WPCS and PSR-2.
- Use WP-CLI util function to get flag values - [`WP_CLI\Utils\get_flag_value()`](https://make.wordpress.org/cli/handbook/internal-api/wp-cli-utils-get-flag-value/).
- No need to specify global scope for WP-CLI classes. Plugin doesn't use namespaces, so all classes and function are in global scope - [http://php.net/manual/en/language.namespaces.global.php](ref).

I will send PR. Just wanted to know, if you want me to send them separately for each issue or all together.

### Technical info
* WordPress version: 4.8
* Algolia Search plugin version: 2.4/master branch

**Comment by rayrutjes** [comment]
Wow, I actually missed this one when I came back from vacation :/

Sounds great @Mamaduka, let me know if I can help with anything.
