### ISSUE TITLE
Can no longer overwrite 'content' field

### ISSUE THREAD

**Issue by jon-heller** [algolia/algoliasearch-wordpress#625]
We use several ACF fields which contain the main post content. We found it easiest to just concatenate these fields together and set those to be the main content field for Algolia. We never use the main post body in WordPress, so that is always empty. 

This used to work fine. Maybe the recent changes with splitting the content effected it? 

### What did you expect to happen?

Using the `algolia_searchable_post_shared_attributes` hook, insert my own custom value into the content field using `$attributes['content']`

### What happened instead?

The updated value of the content field was not stored in Algolia

### How can we reproduce this behavior?

```
function submission_post_attributes( array $attributes, WP_Post $post ) {
    $attributes['content'] = 'test';
}
add_filter( 'algolia_searchable_post_shared_attributes', 'submission_post_attributes', 10, 2 );
```

### Technical info
* WordPress version: 4.7.5
* Algolia Search plugin version: 2.3.0

Lastly, I know that our hook is firing correctly as the `contenttest` field here gets populated fine.

```
   $attributes['content'] = get_field( 'excerpt', $post->ID ) . get_field( 'legacy_summary', $post->ID ) . get_field( 'summary', $post->ID );
   $attributes['contenttest2'] = get_field( 'excerpt', $post->ID ) . get_field( 'legacy_summary', $post->ID ) . get_field( 'summary', $post->ID );
```

Thank you!

**Comment by Mamaduka** [comment]
Based on index design `content` shouldn't be shared attribute, because of post content splitting. I don't think this is bug in new version, just a matter of code/index design.

Not fully tested example code, but it should do the same trick:

```
function submission_post_attributes( array $records, WP_Post $post ) {
	$updated_records = array();

	foreach ( $records as $record ) {
		$record['content'] = get_field( 'excerpt', $post->ID ) . get_field( 'legacy_summary', $post->ID ) . get_field( 'summary', $post->ID );
		$updated_records[] = $record;
   }

   return $updated_records;
}
add_filter( 'algolia_searchable_post_records', 'submission_post_attributes', 10, 2 );
```

**Comment by jon-heller** [comment]
That seems to work perfectly, thank you very much!

Also might be worth adding that filter (`algolia_searchable_post_records`) into the list of filters [in the documentation](https://community.algolia.com/wordpress/filters.html) since I don't believe it's in there currently.
