### ISSUE TITLE
Use InstantSearch V2

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-wordpress#628]
### What did you expect to happen?

The newest version of InstantSearch is used

### What happened instead?

The version 1.11.7 is required as a file.

### How can we fix this behavior?

Simply update when there's time for it 😄

**Comment by rayrutjes** [comment]
I fear it is not that simple @Haroenv.
We have to ensure 100% backward compatibility.

Users can customize the instantsearch templates, so if we push a new version, it would break existing implementations.

What we could possibly do is offer IS v2 as an opt-in option, but then we have to make sure it adds a lot of value.

**Comment by Haroenv** [comment]
Yes, this obviously is not a simple upgrade, but should better happen at *some* point. I made this issue solely as a tracking issue

**Comment by rayrutjes** [comment]
I'm wondering about the added value for the users vs the complexity of implementing this.

**Comment by rayrutjes** [comment]
That makes sense.
This will need some syncing though, because I really do not want to break things.
We learned the hard way going from 1.x to 2.x that introducing even small backward incompatible changes is very annoying for WordPress users.
The WordPress community does not care about semver, and likes to stay up to date with latest versions.

There is unfortunately no concept of major version :/

**Comment by rayrutjes** [comment]
Also, if someone wants to go with ISv2 it is a matter of overwritting the default template and loading ISv2 script and probably unregistering the isv1 script.

**Comment by abrudtkuhl** [comment]
@Haroenv that was me that commented on the blog :) 

What if there was a toggle to switch between versions of the API? Otherwise a V2 version as a separate plugin? Anything the community can do to help out?

**Comment by Mamaduka** [comment]
I think we can introduce template version, plugins like WooCommerce are doing this since I can remember.

Then we can do something like this:
```php
// Get template version
$version = Algolia_Template_Loader::get_version( $template );

if ( version_compare( $version, '2.0.0', '>=' ) ) {
// Load ISv2
} else {
// Load ISv1
}
```

P.S. We can also display admin notice in 'Algolia Search' -> 'Settings', with upgrade suggestion and guide link.

**Comment by rayrutjes** [comment]
Sounds like a plan, yet might require some work.
I'd gladly accept a PR from someone willing to use ISv2 ;)

**Comment by Mamaduka** [comment]
Can send PR for this one as well.

**Comment by ethansmith** [comment]
I think a toggle would be great. FWIW, as a user of this plugin over the past year or so (i've customized just about everything possible, to boot) it's been a little bit confusing to wrap my head around which instantsearch features are only available in v1.x, since most of the current instantsearch documentation online refers to v2.x.

**Comment by Haroenv** [comment]
@ethansmith, overall there's not much breaking changes in v1/v2 features, it's more an internal rewrite and some folds that are smoothed out, as well as the introduction of connectors.

v1 doc: https://community.algolia.com/instantsearch.js/
v2 doc: https://community.algolia.com/instantsearch.js/v2/

Does that make it clearer?

**Comment by ethansmith** [comment]
Thanks!

Source of my confusion was that a number of months ago I was trying to use the infiniteHits widget, based on info I gathered from the v2 git repo. I kept running into dead ends and eventually came to the conclusion that it was a v2 feature, and thus unavailable to me. That said, I just tried implementing the infiniteHits widget a moment ago and it worked like a charm, so I'm perfectly happy for now 👍

**Comment by rayrutjes** [comment]
I'm closing this for now given this will add a lot of "noise" to the existing plugin.
I would like to not have to maintain 2*2 different templates + 2 different versions of IS.

Users that really want to leverage the V2 can customize the templates already and import IS v2 manually.

Anyway, I would expect we decouple the UI logic from indexing in the future to solve this kind of problem.
