### ISSUE TITLE
Make an indexing script to be able to run it as a cronjob

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-wordpress#63]

**Comment by rayrutjes** [comment]
Allow me to ping @deepankarpathak which initiated #58.

## Regarding CRON job:
In the new version of the plugin, there is a cron job that will try to process the whole task queue every hour. That said, the queue will be processed every time a new task is queued, making the CRON job only useful for re-starting the queue if something went wrong during the last processing.

The task queues are always triggered asynchronously, which makes sure we do not add loading time to the different pages.

## Regarding the exclusion of items during indexing
Please see #44 

Feel free to open a new issue if the [documentation](https://community.algolia.com/wordpress/installation.html) is not clear or if you are missing a feature.
