### ISSUE TITLE
Best way to specify a custom index for an instantsearch view?

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#637]
### What did you expect to happen?
Ability to specify an index (other than xxx_searchable_posts) for an instantsearch view.

### What happened instead?
Not sure what the best way to do this is.

### Technical info
* WordPress version: latest as of July 17, 2017
* Algolia Search plugin version: latest as of July 17, 2017

**Comment by Mamaduka** [comment]
Can you share your current code or part of it where you specify index?

I've done this few times, but just want to sure we're referring to the save "instantsearch view".

**Comment by rayrutjes** [comment]
@ethansmith you are fast, I expected this feedback in about 2/3 weeks after my last release and there you go ;)

This is definitely something that is not do-able.

Should be fairly simple to implement.

Here is where we need some changes: https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/class-algolia-plugin.php#L134

Adding a filter there could help.

I just need to check how this affects other parts, like indexing. 
I think if we just add a filter hook there it should be fine.

Feel free to submit a PR if you are in a hurry!

Thanks for submitting this ;)

**Comment by ethansmith** [comment]
Shucks, thanks for the speedy response, guys!

Turns out I didn't look hard enough at the code that was right in front of me. Turns out it's super easy to select the target index via the `indexName` parameter in the `instantsearch` js call.

```
var search = instantsearch({
            appId: algolia.application_id,
            apiKey: algolia.search_api_key,
            indexName: algolia.indices.INDEX_NAME_GOES_HERE.name,
            etc ... });
       ```

**Comment by rayrutjes** [comment]
That is indeed an easy way to go about it @ethansmith .
The only drawback is that this does not work if you are only using Algolia in the backend.
I'll keep this issue open so that I can provide a better way to solve this in the future.

**Comment by rayrutjes** [comment]
Hey @ethansmith ,

After investigation you indeed implemented it the right way.
I made sure with #676 that you can also specify your custom index in the backend.

**Comment by ethansmith** [comment]
Thanks @rayrutjes !
