### ISSUE TITLE
[doc] Screenshots out of date

### ISSUE THREAD

**Issue by JeramyNS** [algolia/algoliasearch-wordpress#638]
The screenshots in the documentionation are out of date.
They show 5 menu items and pages when it appear there is only 3 menu items now: "Autocomplete", "Search Page", "Settings".

Also the autocomplete page is a little confusing. Took me a second to realise that the "Configuration" area is not autocomplete specific. It also controls whether or not it gets indexed at all.
Probably just needs a small note, because at first it had me double checking the documentation.

**Comment by rayrutjes** [comment]
Thanks for the feedback, we indeed need to update the docs.
Feel free to submit a PR if you have some time.

**Comment by raae** [comment]
I agree that it is strange that indexing is under auto-complete. As I am not using auto-complete it took me a while to realize that indexing was happening there.

**Comment by rayrutjes** [comment]
This is happening her #655 🎉

**Comment by rayrutjes** [comment]
This has now been merged in #655 🚀

**Comment by raae** [comment]
What about the 

> Also the autocomplete page is a little confusing. Took me a second to realise that the "Configuration" area is not autocomplete specific. It also controls whether or not it gets indexed at all.

Does it have its own issue? I was helping developers at a wp agency get going with Agolia and this had stopped them in their tracks before our workshop.

**Comment by rayrutjes** [comment]
@raae this is a bit of a technical debt.
I'm honestly not sure how to move forward from what we currently have.
What I do know, is that I don't want to introduce any backward incompatible change.

The plugin currently has 2 main features:
- autocomplete
- instantsearch.js

The autocomplete page "is" autocomplete specific, unless you build your custom search UI on top of existing autocomplete indices.

I'd love to hear what your perception is to see if we can change something.

I appreciate your candid feedback!
