### ISSUE TITLE
Short codes are not resolved

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#64]
It seems the shortcodes are not resolved in the content attribute:
<img width="1230" alt="capture d ecran 2015-09-30 a 11 19 04" src="https://cloud.githubusercontent.com/assets/29529/10193822/9be94836-6785-11e5-8955-17349e6c0a72.png">

**Comment by rayrutjes** [comment]
In the new version of the plugin, 0.2.5 at the time of writing this, the shortcodes are now correctly resolved.

We do so by ensuring we call the `the_content` filter on the post content before sending it to Algolia.

Please not however that this new version of the plugin is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
