### ISSUE TITLE
Content in pre tags is ignored

### ISSUE THREAD

**Issue by aymg** [algolia/algoliasearch-wordpress#640]
Our [documentation](sparkpost.com/docs) tends to have API responses in pre tags which should be searchable. It would be great to have a filter around the `$noise_patterns` array 
 in [`remove_content_noise`](https://github.com/algolia/algoliasearch-wordpress/blob/b806e3fcea6d7982928682a57fc2523426c71e1a/includes/class-algolia-utils.php#L173) so we can customize what tags get removed when indexed.

### Technical info
* Algolia Search plugin version: 2.x

**Comment by rayrutjes** [comment]
Good idea, we could introduce a new filter for this.

Feel free to submit a PR 👍

**Comment by aymg** [comment]
Will do! I'm thinking `algolia_strip_patterns` or `algolia_strip_content_patterns`. Do you have a preference?

**Comment by rayrutjes** [comment]
`algolia_strip_patterns` sounds good and a bit shorter 👍

**Comment by aymg** [comment]
Deal 👍

**Comment by aymg** [comment]
On a related note - are the `algolia_post_parser` and `algolia_searchable_post_parser` filters deprecated? They are still listed in the documentation.

**Comment by rayrutjes** [comment]
Yes they are, they must be removed :/ 
I really need to find some time to update the docs with changes introduced in v2.

We no longer use the external parser because it was not adapted to parsing blog posts.

**Comment by aymg** [comment]
Cool, I'll rip those out from the filters doc ¯\_(ツ)_/¯

**Comment by rayrutjes** [comment]
For the record, this can now be done thanks to #646 .
