### ISSUE TITLE
Newer releases have "v" prefix in tag

### ISSUE THREAD

**Issue by mikeschinkel** [algolia/algoliasearch-wordpress#642]
### What did you expect to happen?

Release tags would not have a preceding "v", .e.g `2.5.0` not `v2.5.0`.

### What happened instead?

Release tags had a preceding "v."

### How can we reproduce this behavior?

Just look at GitHub list of tags.

### Can you provide a link to a page which shows this issue?

https://github.com/algolia/algoliasearch-wordpress/releases

### Technical info
* WordPress version: n/a
* Algolia Search plugin version: n/a

This might cause issues when using [Composer](https://getcomposer.org/).  Minimally it is inconsistent with prior revision tagging.

**Comment by rayrutjes** [comment]
Can you be more specific, do you encounter an error when using it with composer?
Would it be ok to just release the new tag without the "V" and keep the 2 tags that have been published with it? would be simpler.

**Comment by mikeschinkel** [comment]
@rayrutjes Actually, I wrote the above before testing. It does appear to work with the `v`, but is in consistent with your earlier tags and most everyone else's tags I've seen when working with composer _(I have never seen another `v` prefix, fwiw.)_  

Adding new non-`v` tags and leaving the old `v` tags as is would be fine.

So yes I am being pedantic, thanks for supporting me anyway. :-)

**Comment by rayrutjes** [comment]
Composer will consider v1.x == 1.x, the v is actually ignored.
You are right though regarding consistency, and we will want to go back to the old notation probably.

Thanks for raisin the issue ;)
