### ISSUE TITLE
Add a filter to override searchable post types

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#649]
Currently there is no easy way to customize the post types that should be part of the searchable_posts index (index used for the InstantSearch page).

Here is the line we should add a filter to:
https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/class-algolia-plugin.php#L177

**Comment by raae** [comment]
This would be great, and/or the possibility to choose a specific index.

**Comment by a-mishra-niku** [comment]
yea same here want to search by index name for individual index .. now it results from all the indices

**Comment by rayrutjes** [comment]
@raae @a-mishra-niku : I just opened a PR #667 , would this work for you?

**Comment by raae** [comment]
Yes it looks like it would solve my issue of wanting only one post_type to be available in the backend search take over. 

I would also be able to combine post_types into one index as mentioned in #665.

**Comment by raae** [comment]
Sorry, didn't realise it was a PR (sloppy reading). I will test it locally shortly.

**Comment by raae** [comment]
Tested locally and it works well.

**Comment by rayrutjes** [comment]
Awesome @raae ,

I'll move forward with the PR then and have it merged ASAP.

**Comment by rayrutjes** [comment]
This is now deployed as 2.8: https://wordpress.org/plugins/search-by-algolia-instant-relevant-results/ 🎉 

Thanks for your interest @raae & @a-mishra-niku !
