### ISSUE TITLE
Index Outputs Array Separated with Commas, but no Spaces

### ISSUE THREAD

**Issue by WinstonGFX** [algolia/algoliasearch-wordpress#650]
### What did you expect to happen?
I have successfully connected my custom Wordpress post type (employees) to my Algolia index, but I'm having an issue with the output of lists of items in the index displaying as a single long comma-separated word with no spaces, leading to line-break issues in the HTML display. Instead of a comma between strings, I'd like a comma and a space between strings.

For instance:
<img width="478" alt="screen shot 2017-08-08 at 4 01 39 pm" src="https://user-images.githubusercontent.com/2249061/29098337-cd4dab12-7c53-11e7-9cba-fb5b68c709a6.png">

`"likes": [
        "Cycling",
        "Sci-fi and fantasy books",
        "Photography",
        "Cats"
      ]`

should display as:
Cycling, Sci-fi and fantasy books, Photography, Cats

### What happened instead?

Instead, it outputs as:

Cycling,Sci-fi and fantasy books,Photography,Cats

### How can we reproduce this behavior?

Use any index attribute that is list of multiple strings and output to HTML

Can you provide a link to a page which shows this issue?
http://intranet2.winstongfx.com/

### Technical info
* WordPress version: WordPress 4.8.1
* Algolia Search plugin version: Version 2.6.0

**Comment by rayrutjes** [comment]
Hey @WinstonGFX ,

It appears that the screenshot references the display on the Algolia dashboard, correct?
The display there is just to make it nice to visually identify the data.

When you get back results from Algolia, you can process the data as you wish.
In JavaScript you could for example join the items like you requested:

```js
const hit; // contains 1 result
hit.likes.join(', ');
```

Unsure if that answers your question :/

Please let me know how I could help you more.
