### ISSUE TITLE
Some of the post types are not being indexed using WordPress Algolia plugin

### ISSUE THREAD

**Issue by balazimichal** [algolia/algoliasearch-wordpress#654]
### What did you expect to happen?
All post types should get indexed into Algolia's database.

### What happened instead?
I get pop up with error message telling me that "Error occured" and under the text I have excerpt (html code) of the area where the indexing function broke. In my case this is tied to Gravity Forms form being present in the content.

### How can we reproduce this behavior?
Install Gravity Forms and insert form shortcode into content.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.8.1
* Algolia Search plugin version: 2.6.0

**Comment by rayrutjes** [comment]
Thanks for reporting this here @balazimichal .
Do you think you could share the forms you are currently having on the website?
Is it one or multiple forms on pages? on posts?

**Comment by balazimichal** [comment]
We only have such cases on pages. Good example of such page would be:
https://riverbankoxf.staging.wpengine.com/it-security-audit/

**Comment by rayrutjes** [comment]
Can you make a screenshot of the error?
Also, can you take a look at the XHR request in the console and screenshot that as well?

**Comment by rayrutjes** [comment]
I just released a fix in 2.7.0 for an issue that might be similar to this one.
Can you update the plugin and let me know if it solves the issue?

Thanks!

**Comment by rayrutjes** [comment]
I hope the latest release fixed your issue.
If not, please re-open the the issue and give us some more information.

Cheers,
