### ISSUE TITLE
[Security-Issue] Search key visible even when search/autocomplete disabled

### ISSUE THREAD

**Issue by JeramyNS** [algolia/algoliasearch-wordpress#658]
Due to the setup and multi-tenancy application I use, the public search key is something that needs to remain hidden from public view.

Imagine my surprise when viewing the source code of the WordPress website and sitting there in public view was the search key. 
Both the Autocomplete feature and Search page settings are turned off, so I just assumed that would mean no code would be added to the front end of the site.

I think that you either need a clear warning about this somewhere or just some code to disable the config if it never gets used.

For anyone interested, its quite easy to disable the config yourself:
```
function disable_algolia_config() {
    return []; // Hide the config from the public
}
add_filter( 'algolia_config', 'disable_algolia_config');
```

**Comment by rayrutjes** [comment]
Hey @JeramyNS ,

Thanks for opening the issue.

Given the data accessible by the search API key is publicly accessible somewhere we do not consider this as a security issue.

That being said, I'd gladly accept a PR to adhere with your example.

**Comment by JeramyNS** [comment]
Hey @rayrutjes 
Are you saying that there is somewhere else that this API key is publicly available?

I was under the impression from your forum post below that it was possible to make the public API key secure and scoped to a given set of parameters depending on the person logged-in.
https://discourse.algolia.com/t/multi-tenant-algolia-index/147/2

**Comment by rayrutjes** [comment]
Hey @JeramyNS ,

The post is referring to "secured API keys", which are keys generated on the fly in the backend.
These keys are generally used to implement multi-tenancy and let a user access only his data while restrict access to others.

There is no usage of secured API keys by default in this plugin.

**Comment by JeramyNS** [comment]
Yes, absolutely, exactly what I am talking about. 
I am using secured API keys to do all my search queries, meaning that I personally do not publish my search api key anywhere. 
None of the search is performed on the WordPress site and the only reason I use the plugin is to sync data to Algolia.

So back to my question, are you saying that there is somewhere else that this API key is publicly available?
I can't see anything, but your previous response implies that it is publicly accessible somewhere, which is a major concern for me right now.

Now I get it that you don't really take this seriously, because it's a WordPress plugin and chances are there will a handful of use cases like my own. I still wish there was some sort of warning or notification to let you know this would happen as in my use case it is a major security concern. 
I need to keep my clients and their combined 125,000 websites, secure and apart from this hiccup, I am fairly confident about that.

**Comment by rayrutjes** [comment]
We take security very seriously, and if you find a security breach in the future, please don't reveal it publicly but send it to security@algolia.com instead.

In this case, the exposed key is a "public" key used for searching data that is displayed publicly to users.

If you are using this plugin outside of its initial scope which is secured, then you will indeed need to adapt the implementation.

In the plugin there is a filter that will let you override the outputted config: `algolia_config`.
You can return an empty array from there to display no data at all.

I hope that helps.
