### ISSUE TITLE
How to best combine taxonomy terms from several taxonomies into one index?

### ISSUE THREAD

**Issue by raae** [algolia/algoliasearch-wordpress#665]
I would like to be able to create an index that includes terms from several taxonomies. How would I go about doing that?

### Why?
On my site I let users search a database of books. Today if they search for an author, illustrator, category or tag they will get books with this term attached. But I would like to display matching terms on top so the user can go directly to that terms archive.

However, it feels wrong to search 5 or more indices at the same time which is the option with the current solution.

**Comment by raae** [comment]
Is the issue (use case) understandable?

**Comment by rayrutjes** [comment]
Hi @raae ,

Thanks for the gentle ping here!

> However, it feels wrong to search 5 or more indices at the same time which is the option with the current solution.

This is actually the best option you have.
Another solution would be to embed the term URL in every book record, but then you would have to update the logic of pushing that information yourself.

I'd be curious to see the UI you end up with. Maybe we could take a sneak peak into it to eventually give you some feedback. It's sometimes hard to give guidance when we do not have the whole scope of what is being built ;)

I'm closing this, but feel free to continue the discussion!
Our forum might be better for such exchanges: https://discourse.algolia.com/
But I know you are already a user there 👍

**Comment by raae** [comment]
Thanks @rayrutjes and I will remember to take my implementation questions to the discourse.
