### ISSUE TITLE
How to combine Indices from multiple sites

### ISSUE THREAD

**Issue by d4mation** [algolia/algoliasearch-wordpress#668]
### What did you expect to happen?
Tried to add the default `getstarted_actors` Index to the Search Results (as a test before attempting to include other Indices) using an instance of the `Algolia_Posts_Index` Class via the `algolia_indices` Filter.

I expected it to not work perfectly as the data structure is different between indexed posts from this Plugin and that default data. However, from what I can tell, it isn't possible to include any "foreign" Indices. 

Since the permalink is included in the data structure in Indices built by this plugin, I was trying to find a way to include Indices in a search result that were generated for another site with the same data structure. A Cross-Site Search basically.

### What happened instead?
This assumes that it is a Post Type local to the website instead of pulling from a remote Index. It instead attempts to build an Index named `posts_getstarted_actors` and since it finds no Posts in the Post Type `getstarted_actors`, it just bails.

![image](https://user-images.githubusercontent.com/7770631/30605493-541f3508-9d3c-11e7-982d-c3b8336e1e48.png)

### How can we reproduce this behavior?
```
add_filter( 'algolia_indices', function( $indices ) {
	
	$test = new Algolia_Posts_Index( 'getstarted_actors' );
	
	// Tried to force there to be no prefix on the Index ID
	$test->set_name_prefix( null );
	
	$indices[] = $test;
	
	return $indices;
	
} );
```

### Technical info
* WordPress version: 4.8.1
* Algolia Search plugin version: 2.7.0

**Comment by rayrutjes** [comment]
Hey @d4mation ,

This is somewhat out of the initial scope of the plugin.
That being said, if you want to add external indices to the autocomplete, you could use the `autocomplete_config` filter: https://discourse.algolia.com/t/using-multiple-indices-on-wordpress/2617

Let me know if that helps.

You could also customize the template of the autocomplete dropdown by following: https://community.algolia.com/wordpress/customize-autocomplete.html

**Comment by d4mation** [comment]
Excellent, I was hoping there was a Filter I had just not found!

So from what I'm understanding here, _both_ sites must have the same Index Prefix (So, the indices must all start with something like `wp_` as configured in the Plugin Settings) and when I add them to the `autocomplete_config` Filter, I should be _including_ the Prefix? I'm guessing in the linked example, `corporate_posts_` is the Index Prefix.

And this would allow the external Indices to be used for both the Autocomplete Dropdown and the Search Results page?

**Comment by rayrutjes** [comment]
> both sites must have the same Index Prefix 

Not exactly,
The custom indices you want to display must have the same records structure (same attributes).
If they don't, then you will have to customize the autocomplete template like explained here: https://community.algolia.com/wordpress/customize-autocomplete.html

I hope that makes sense.

**Comment by d4mation** [comment]
I wasn't able to get to this until significantly after you replied, but I wanted to say thanks! I ended up getting it to work after looking at your links as well as the source itself.

It seems like there's no way to include results from these other indices on the InstantSearch page aside from adding those results directly into your `searchable_posts` index, right? At least without not heavily modifying `templates/instantsearch.php` considering it seems to be hardcoded to use only the Searchable Posts index defined on the settings page.
