### ISSUE TITLE
Feature request: Have both "Use Algolia in the backend" and "Use Algolia with Instantsearch.js" active at the same time

### ISSUE THREAD

**Issue by raae** [algolia/algoliasearch-wordpress#669]
If javascript is disabled or broken in some way I would still like the results to be served by Algolia in the same way as when using "Use Algolia in the backend".

**Comment by rayrutjes** [comment]
Hey @raae ,

This is already the current behavior:
- https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/class-algolia-plugin.php#L130
- https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/class-algolia-settings.php#L150

When instantsearch.js is enabled, Algolia is also powering the backend.

**Comment by raae** [comment]
Great, maybe just make that a little clearer in the documentation or in the option selection. Also if you mark some issues "good for first-time contributor" or something similar I might find the time to contribute.
