### ISSUE TITLE
Divide hits based on post types

### ISSUE THREAD

**Issue by webmagicz** [algolia/algoliasearch-wordpress#68]
Hello,

I have 2 different post types in Wordpress: teams and players. I indexed both types and search works great - but what I want achieve is that I get teams search results on left hand side and players on right hand side, but without menu. So result for both types should be immidiatelly shown separated from each other. 

At this moment, if I use Attribute "type" set to "Menu", I have menu on left hand side and results mixed on right hand side. Can you help me get results for 1 post type on left hand side and results for other post type on right hand side of instant search results template? 

Thank you.

**Comment by maxiloc** [comment]
@webmagicz Sorry for the late reply, You should have a look at our new library https://community.algolia.com/instantsearch.js/ it will allow you to do this easily.
The goal is to make it part of the extension very soon
