### ISSUE TITLE
Plugin still using Instantsearch.js v1.11.7 instead of latest v2.2.5

### ISSUE THREAD

**Issue by dhavalgshah** [algolia/algoliasearch-wordpress#689]
Hi,

Any particular reason that WordPress plugin is still using v1.11.7 of Instantsearch.js instead of latest v2.2.5?

Are there any conflicts which I should be aware of in case I want to replace the older version with newer in my WP install?

**Comment by rayrutjes** [comment]
This has been discussed in #628 .
For now, the work to be done to upgrade to IS v2 is to high if we want to keep backward compatibility.
Having the 2 versions along each other would also be problematic in terms of support.

I haven't tried manually using v2 with existing index but I don't see any issue doing so as long as you follow the [InstantSearch v2 documentation](https://community.algolia.com/instantsearch.js/v2/getting-started.html).

I'd love to have your feedback if you decide to use the v2.

**Comment by 2aces** [comment]
@rayrutjes following what has been discussed here and in #628 . What would you suggest as a "safe" path for those of us willing to try integrate v2? I see the 1.11.7 uses a preact version and preact is something I have no experience yet, so it's not clear what should we do.

**Comment by rayrutjes** [comment]
@2aces preact is an internal concern of InstantSearch V2 AFAIK. You shouldn't need to work with it directly.

I would recommend creating your very own template and not rely on existing code. Just enqueue the InstantSearch library and start implementing your search.

You can definitely ask for help about InstantSearch on our forum: https://discourse.algolia.com/

**Comment by 2aces** [comment]
Thanks @rayrutjes
