### ISSUE TITLE
Create / customizing indexes

### ISSUE THREAD

**Issue by ValentinJcqmt** [algolia/algoliasearch-wordpress#691]
I need 3 types of algolia search bar with autocompletion:
- Searching in all custom posts "annonce" but only looking for user input matching one custom field (Search bar on page "A")
- Searching in all custom posts "annonce" but only looking for user input matching the terms associated with the posts (another search bar on page "A")
- Searching in custom posts "annonce" but only looking for user input matching the post title (Search bar on page "B")

I achieved to to get all of these separately bu I can't figure how to have multiple indexes for each one.
Currently, I have the fist case I need working with customizing the filters "algolia_post_annonce_shared_attributes", "algolia_searchable_post_annonce_shared_attributes" and "algolia_posts_annonce_index_settings". And it's applied to the Wordpress widget "WP_Widget_Search"

But I couldn't find in the doc, if I'm able to separate the 3 indexes that I need, and apply them to 3 different search field. I'm not sure this is what I need, I'm quite new to Algolia Search, any help will be apreciated.

Algolia Search plugin version:  2.8.1

**Comment by rayrutjes** [comment]
Hi @ValentinJcqmt sorry about the delay on this one.
What you are asking is out of scope of the plugin.

If the records are the same but the ranking different, you can leverage replicas.
This is explained here: https://community.algolia.com/wordpress/replicas.html#algolia-search

I hope that helps.
