### ISSUE TITLE
Where would I change the code to open a new tab when clicking on a search result

### ISSUE THREAD

**Issue by damarusama** [algolia/algoliasearch-wordpress#692]
I would like to be able to open a new tab when clicking on a search result. 

I cannot find where/ what to change to do that.

**Comment by rayrutjes** [comment]
Hi @damarusama ,
I think you are requesting this feature for the autocomplete dropdown experience.

This is unfortunately not possible for now.

Please follow the issue here: https://github.com/algolia/autocomplete.js/issues/207

I'm closing this one until it becomes actionable.
