### ISSUE TITLE
Function for single record index request?

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#695]
I'd like to trigger user indexing via several hooks, so that user records get indexed/updated when a user does things like adding comments, adding friends, joining groups, etc. 

Is there a function that I can use to trigger reindexing of a particular user_id (or post_id, for that matter)? Right now I'm just calling wp_update_user(...) as a workaround.

Thanks!

**Comment by rayrutjes** [comment]
Wow, this one slipped through, sorry about the delay.

I think using `wp_update_user` is fine.

Another way of doing it for the users for example would be to get an instance of the watcher, and call `sync_item`: https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/watchers/class-algolia-user-changes-watcher.php#L40

The problem being that those watchers are currently not retrievable :/.

For now I would stick with  `wp_update_user`.

**Comment by ethansmith** [comment]
Thanks, Ray!
