### ISSUE TITLE
Algolia search is showing all languages in search title.

### ISSUE THREAD

**Issue by iamsahmad** [algolia/algoliasearch-wordpress#713]
I am using qtranslate x multilanguage plugin and algolia search, but the problem now is Algolia search is showing all of my languages in search titles(on search result page and autocomplete).

**Can you provide a link to a page which shows this issue?**
Yes, here is the link: https://dxboffplan.com/new/villas-for-sale-sharjah/?s=&is_v=1

### Technical info
* WordPress version: Latest Version
* Algolia Search plugin version: Latest Version

**Comment by rayrutjes** [comment]
Hi @iamsahmad,

So far the plugin is not compatible with Qtranslate.

The reason being that it impacts the way you index data, the way you present it. So it changes more or less all the plugin's logic.

We have some users that manage to make it work, however I'm not sure how they did it.

I'm closing this one as we do not plan to make the plugin compatible anytime soon.

All other translation plugins are easier to integrate with.
