### ISSUE TITLE
Is there a way to stop posts from being indexed based on wordpress tags?

### ISSUE THREAD

**Issue by jdwallace12** [algolia/algoliasearch-wordpress#716]
Hey there, I have some legacy posts that I do not want to delete but do not want them to show up in the search results.  I have all these post tagged in wordpress under the same tag, is it possible to not index a particular post with a tag?  Thanks!

**Comment by Mamaduka** [comment]
You can use [`algolia_should_index_post/algolia_should_index_searchable_post `](https://community.algolia.com/wordpress/indexing-flow.html#indexing-decision) filters.

```php
add_filter( 'algolia_should_index_searchable_post', function( $should_index, WP_Post $post ) {
	if ( false === $should_index ) {
		return false;
	}

	return has_term( 'exclude-term', 'taxonomy', $post );
}, 10, 2 );
```

Haven't tested the code, but general logic should be something similar.

P.S. Probably will have impact on indexing performance, since `has_term` has to query DB for each record.

**Comment by rayrutjes** [comment]
Thank you so much @Mamaduka for commenting on this.

@jdwallace12 please give the above solution a try.

Feel free to re-open this if needed!

**Comment by jdwallace12** [comment]
Thanks @Mamaduka and @rayrutjes  for your response.  This seems to only index posts with this tag, I am non wordpress developer, so maybe I am missing something obvious.  The code you sent seems straightforward but I am not sure what "has_term" comes from.  Is there a "does_not_have_term" function or something like that?  Thanks!

```
add_filter( 'algolia_should_index_searchable_post', function( $should_index, WP_Post $post ) {
	if ( false === $should_index ) {
		return false;
	}

	return has_term( 'TraceView', 'post_tag', $post );
}, 10, 2 );
```

**Comment by jdwallace12** [comment]
this worked for me, thanks again
`add_filter( 'algolia_should_index_searchable_post', function( $should_index, WP_Post $post ) {
	if ( false === $should_index ) {
		return false;
	}

	return has_term( 'TraceView', 'post_tag', $post );
}, 10, 2 );`
