### ISSUE TITLE
Using Algolia in wp-admin area

### ISSUE THREAD

**Issue by SamAnthonyWP** [algolia/algoliasearch-wordpress#73]
Hey Guys,

I am trying to implement algolia in the admin area. It seems as if I am very close. When I click into a search box on the posts page of the admin and type a letter, I get the dropdown with blank results.

The links in the blank boxes are active and correct, but the text is not visible. I can cycle through the results with the arrows or click on them and I get to the right page, but the page titles just don't appear in the suggestion boxes. They do, however, appear when using the search from the front-end of the website.

Any ideas on what might fix this issue?
![algolia-inside-admin](https://cloud.githubusercontent.com/assets/13756714/12490397/f6ecd032-c03a-11e5-92d1-62392afa52d6.png)
![algolia-front-end](https://cloud.githubusercontent.com/assets/13756714/12490429/1bf5af8e-c03b-11e5-9bbd-289d593e892b.png)

I really appreciate it!

--Sam

**Comment by rayrutjes** [comment]
Hi @SamAnthonyWP, we are actively working on a new release of the plugin.
I think your request is a bit out of scope of this plugin for now. That said, I am curious. Could you tell us a bit more about your use case, and why you would want to use the Algolia autocomplete in the admin?

**Comment by SamAnthonyWP** [comment]
Hey @rayrutjes --
Thanks for the response, I totally understand that it is a bit out of the scope. Well, as we all know, the wordpress search functionality is bad on the front-end, but it is also horrible on the backend. For any site that has a ton of posts or pages (like several sites that we run), it takes forever to get to them in the admin in order to make an edit. I just think it would be super slick if we could pile this functionality into a standalone plugin and make it available to everyone. The odd part is that the autocomplete would need to produce links to the edit post/page screen, rather than the front-end post/page.

Hope that helps. Let me know if I can be of any assistance. I am a big fan of Algolia.

**Comment by rayrutjes** [comment]
First of all, thank you for the kind words @SamAnthonyWP !

Your use case totally makes sense to me, and I would love to work on an admin integration in the future.

For now we are focusing on a new release that will be more developer friendly and user friendly.

They way we built our new indexing mechanism will allow for extension and I think it would not take too much time to implement that kind of admin search feature. Let's keep in touch, and feel free to add some kind of wishlist of features for the admin part on this issue!

Cheers.

**Comment by SamAnthonyWP** [comment]
@rayrutjes -- nice. I will definitely keep in touch.

**Comment by rayrutjes** [comment]
Hi again @SamAnthonyWP , please give the new plugin a try and be sure to go over the [documentation](https://community.algolia.com/wordpress/installation.html).

You should now fairly easily be able to add autocomplete search experiences in the backend of WordPress.

Please share your work if you decide to move forward with this, I'm sure a lot of users would love better search in the backend of WordPress!

Closing this as we will never integrate this kind of feature in this repo.
