### ISSUE TITLE
New filter hookup: Change post type's index name

### ISSUE THREAD

**Issue by PaKZer0** [algolia/algoliasearch-wordpress#732]
### What did you expect to happen?
I looked up over the docs and through the code to find if there's a way to override the algolia index name that the plugin would use to store certain post type data.

### What happened instead?
I could't find any filter hookups for the task, so I made up my own. I thought about setting a serious PR, but the required change is minimal, so I made a quick gist for the task:

https://gist.github.com/PaKZer0/4fba733c9ae6cef5f50fefdc33ce879e

### How can we reproduce this behavior?
This request may seem a bit odd, but we have two different content types with the same fields that we want to store in the same index without distinctions. It could be useful to others with the same problems or just another fine grain config option that could be set programatically.

Can you provide a link to a page which shows this issue? Not really =/

### Technical info
* WordPress version: WordPress 4.9.4
* Algolia Search plugin version: 2.10.2

**Comment by rayrutjes** [comment]
Hi @PaKZer0 ,

Thanks for opening this.
I'm worried about the additional mental overhead this introduces.

I'd love to hear more about your usage of this. Does it mean that depending on the post type, you will dispatch content to different indices?

This might break other behaviour like clearing indices, pushing settings, no?

**Comment by PaKZer0** [comment]
Yes, in fact I've been trying to hack this and my minimal gist is not enough. What I'm trying to do is to index two different post types on the same index.

**Comment by rayrutjes** [comment]
I see, do you actually use the "searchable posts" index for something already?
Otherwise you could use that one, and remove the post types that you do not need.

**Comment by PaKZer0** [comment]
I'm not currently using the "searchable posts" index and it is a good solution for the current situation, but I also forgot to mention that setting a custom name for the indexes (besides the prefix) may be also desirable for the site I'm working on.

(I forgot so say thanks btw ^_^)

**Comment by rayrutjes** [comment]
> setting a custom name for the indexes (besides the prefix) may be also desirable for the site I'm working on

I'm mostly interested in the reason of that so that I can eventually guide you to a solution.

If you are not using the searchable posts for now, you could use that index and filter out the post types there.
Here is an example: https://gist.github.com/rayrutjes/6b1de96b3687b937086428c37bf144f9
You can basically return just an array containing the post types you want. Not sure if that helps let me know.

**Comment by PaKZer0** [comment]
> I'm mostly interested in the reason of that so that I can eventually guide you to a solution.

I'm sorry if I'm being a bit dodgy. Basically I'm migrating a wp site which is using Algolia as a search/indexing engine, the old site was using the old Maven Algolia and the reason behind the name override is mantaining a legacy index with the same contents but changing the plugin backend.

**Comment by rayrutjes** [comment]
Thank you for sharing the context.

Quite honestly, you are about to introduce a lot of complexity.

I wouldn't recommend moving forward in this direction given the Maven plugin has nothing in common with this plugin.
Chances are you are going to loose a lot of time.

The best you can do is keep the old index as a temporary solution and start using the new ones.

You can customize the autocomplete & instantsearch experiences by following guides here: https://community.algolia.com/wordpress/customize-autocomplete.html#algolia-search

Beyond that, there is not much I'll be able to do to guide you. I don't even know how the Maven plugin works :)

**Comment by PaKZer0** [comment]
Thanks anyways =)

**Comment by rayrutjes** [comment]
You are welcome @PaKZer0 .
Sorry to not have an easy solution here.

Please re-open an issue if there is anything else you'd like to discuss.
