### ISSUE TITLE
Quotes are double escaped

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#734]
It seems like quotes get double escaped in the following scenario:
- submit a search input with a query containing `'`
- resulting page displays the query with escaped value instead of the quote
![image](https://user-images.githubusercontent.com/5570853/37346473-aef64472-26cf-11e8-9bd1-14434c800cf2.png)

**Comment by rayrutjes** [comment]
I've been unable to re-produce this.
It seems unrelated to this plugin.

**Comment by rayrutjes** [comment]
This issue still isn't solved as quotes still are prefixed with backslashes: `gone\'s \"`

**Comment by Mamaduka** [comment]
I think [`wp_unslash()`](https://developer.wordpress.org/reference/functions/wp_unslash/) might be the right function for "escaping" in this case.
