### ISSUE TITLE
I cannot disable the template loader on front-end...

### ISSUE THREAD

**Issue by mtskf** [algolia/algoliasearch-wordpress#738]
### What did you expect to happen?
I use the plugin only for indexing, and set Search Page option to "Do not use Algolia".
I don't use the plugin scripts on front-end at all.

### What happened instead?
However, still it prints the header scripts on front-end and causes errors.
(as I don't use jQuery...)

**Comment by rayrutjes** [comment]
Hey there, do you have a live example?
Can you confirm you didn't enable the autocomplete experience?

**Comment by mtskf** [comment]
Thanks @rayrutjes !
I didn't notice the autocomplete option!
That solved the issue, great! :) 👍
