### ISSUE TITLE
Trashed posts is searchable

### ISSUE THREAD

**Issue by sebastianthulin** [algolia/algoliasearch-wordpress#746]
When a page is deleted WordPress adds the suffix __trashed to the url of the page. Still, the post is appearing in autocomplete-searchresults. 

### What did you expect to happen?
The post should not appear in search results. It should be handles similar to a unpublished post in both autocomplete and search-page.  

### What happened instead?
The post is searchable. 

### How can we reproduce this behavior?
Trash a post and have a look in algolia search dashboard. It will remain the same. Only the __trashed suffix has been appended to the permalink.

### Can you provide a link to a page which shows this issue?
Not at the moment. I have cleared all trashed posts from Algolia index manually. 

### Technical info
* WordPress version: 4.9.5
* Algolia Search plugin version: 2.10.2

**Comment by rayrutjes** [comment]
Hi @sebastianthulin ,
By default this plugin will remove trashed posts from the index.
Could it be that you are using a plugin that somehow interfers with the post hooks?
Or maybe you have a special plugin that is handling your trashed posts?

**Comment by sebastianthulin** [comment]
I can't recall such behaviour from another plugin, i will do a clean install and submit a video.

**Comment by sebastianthulin** [comment]
I have located it to one of your own themes. I will try to find whats causing this behaviour.

**Comment by sebastianthulin** [comment]
Behaviour was caused by a faulty if-statement in our own "algolia_should_index_searchable_post" filter.
