### ISSUE TITLE
Advanced Custom Fields missing attribute data

### ISSUE THREAD

**Issue by ddibiase** [algolia/algoliasearch-wordpress#76]
We make heavy use of the ACF (Advanced Custom Fields) plugin with most of our WP deployments. ACF is extremely common in the WP world these days as a matter of fact.

We're noticing that we can't easily gain access to the correct ACF custom field attributes with the Algolia plugin. ACF has a habit of prefixing the name of it's fields with an underscore. So if you have a field called "bio" then the field that stores it's internal ID is called "_bio".

Currently Algolia is ONLY seeing the prefixed values and hence not grabbing the correct fields it needs to build our index. I'm wondering if someone else has uncovered this yet and if it's been resolved or in the process of being resolved?

I've attached a screenshot of what we see in our dashboard:

![screen shot 2016-02-03 at 6 21 35 pm](https://cloud.githubusercontent.com/assets/1168397/12800462/248576da-caa3-11e5-8fe9-9fe62654e259.png)

Also for the time being I'm wondering if I could manually query and assign the values myself using the prepare record hook with the syntax:

    add_filter('prepare_algolia_record', function($data) {
        if ( $data->type == 'speaker' )
        {
            $data->bio = get_field( 'bio', $data->ID );
            $data->bio = get_field( 'trueline', $data->ID );
        }
        return $data;
    });

This would be a good way of getting around the issue for now I suppose. I can just append the values to the $data object and call ACFs get_field() function manually. My only concern is how can I get access to the record post ID? Is the value populated in the $data object? The above sample code is what I'm hoping to achieve.

The documentation should identify what data comes with the object so other developers don't have to attempt printing the variable and inspecting its structure.

**Comment by maxiloc** [comment]
Right now this is the way to handle it, your filter is good. The extension is not yet production ready and this is one of the issue we need to handle.

**Comment by ddibiase** [comment]
If I plug that code into my functions.php, the payload doesn't seem to be
affected.

Also can someone answer my question about the filter hook $data object?

Thanks.
On Thu, Feb 4, 2016 at 2:57 AM maxiloc <notifications@github.com> wrote:

> Right now this is the way to handle it, your filter is good. The extension
> is not yet production ready and this is one of the issue we need to handle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-wordpress/issues/76#issuecomment-179699147>
> .
>

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by ddibiase** [comment]
For anyone else using the prepare_algolia_record hook note that the above example for accessing the post ID is incorrect. Algolia includes the value as "objectID". Correct example below:

    add_filter('prepare_algolia_record', function($data) {
        if ( $data->type == 'speaker' )
        {
            $data->bio = get_field( 'bio', $data->objectID );
            $data->bio = get_field( 'trueline', $data->objectID );
        }
        return $data;
    });

**Comment by rayrutjes** [comment]
Hey @ddibiase, as a follow up to this thread and the releasing of version 0.2.5, I integrated some documentation related to Advanced Custom Fields, hope that will help all users of Advanced Custom Fields.

You can access the documentation here: https://community.algolia.com/wordpress/advanced-custom-fields.html

Let me know if we missed use cases, I'd gladly iterate on the documentation!

I'm closing this issue because it was related to version 0.0.1 of the plugin, but please open a n issue if needed.
