### ISSUE TITLE
Ability to use different autocomplete filters for multiple search inputs

### ISSUE THREAD

**Issue by enkota** [algolia/algoliasearch-wordpress#762]
I am manually adding in search input boxes for 2 custom post types `news` and `help` with the following:

`<input type="search" class="search-field" aria-owns="algolia-autocomplete-listbox-0" dir="auto">
`
Is there a parameter I can add which only displays `news` autocomplete results while on the `News` page and only results from `help` while using the search box on the `Help` page?

Thanks!

**Comment by rayrutjes** [comment]
Hi @enkota ,

Unfortunately, we have no way of currently doing that easily.
Basically the current implementation plugs itself to all `name="s"` input fields and uses the configuration provided on the "algolia search -> autocomplete" page.

You could customize the `templates/autocomplete.php` file to detect what search input you are currently attaching to, and override the sources for the autocomplete accordingly.
This is however a bit out of the initial scope of this plugin.

**Comment by rayrutjes** [comment]
Maybe try to duplicate parts of the logic in the autocomplete.php file.
If you start heading in that direction, feel free to send me a gist or something to review. Happily give it a quick look.

**Comment by enkota** [comment]
Morning @rayrutjes. Thanks for the info, I will give it a shot and let you know how I get on 👍

**Comment by rayrutjes** [comment]
If you want to ship the changes along with a theme, you can elegantly override the templates/autocomplete.php like explained here: https://community.algolia.com/wordpress/customize-autocomplete.html#algolia-search

**Comment by enkota** [comment]
@rayrutjes I have discovered the source section inside `autocomplete.php` 

Since I am only using 2 indexes I will probably just manually empty these. Would it be possible to enter the index value manually like:

`Would posts_help be entered in the source area?`
```
source: algoliaAutocomplete.sources.hits(client.initIndex(config['posts_help']), { 
		  hitsPerPage: config['max_suggestions'],
		  attributesToSnippet: [
			'content:10'
		  ],
		  highlightPreTag: '__ais-highlight__',
		  highlightPostTag: '__/ais-highlight__'
		}),
```
Thanks!

**Comment by rayrutjes** [comment]
Yes that should do the trick, as long as you don't have the 2 searches on the same page.

**Comment by enkota** [comment]
Got it working with the following (need to update the dropdown title but should be easy enough to do in the template):

```
    //Checks if input ID exists on page and sets indices
    if ($('#playlist_search').length){
      var indexType = 'wp_posts_playlists';
    } else if ($('#docs_search').length){
      var indexType = 'wp_posts_docs';
    }
	  sources.push({
		source: algoliaAutocomplete.sources.hits(client.initIndex(indexType), {
		  hitsPerPage: config['max_suggestions'],
		  attributesToSnippet: [
                  ...
```

**Comment by rayrutjes** [comment]
Awesome! I'm closing this but feel free to open other issues as needed.
