### ISSUE TITLE
[WPML integration with Algolia Search] after implementation no results at all

### ISSUE THREAD

**Issue by senlin** [algolia/algoliasearch-wordpress#766]
I followed the instructions on [this page](https://community.algolia.com/wordpress/wpml.html) to try and get singular language results instead of results in both languages. However the result is I get nothing at all.

### What did you expect to happen?
singular language search results

### What happened instead?
no search results whtasoever

### How can we reproduce this behavior?
go [here](https://tesellefamily.org/) and search for example for "ollie", nothing will show in the dropdown, but hitting enter, the first search result shows what should show in the dropdown.

EDIT: On the [staging site](https://sandbox-online.com/ts2018/) (login & pass: demo) I have disabled the lot and there it works, be it with results in both languages.

### Technical info
* WordPress version: 4.9.6
* Algolia Search plugin version: 2.11.1

**Comment by rayrutjes** [comment]
Hoi @senlin ,

Could your send a support request to support@algolia.com?
Please make sure to grant us read access to your account.
https://www.algolia.com/users/edit#?tab=access-control

Implementation looks correct on the live website.
Did you try deleting the Algolia indices from Algolia dashboard and re-index everything?

**Comment by senlin** [comment]
okay, as this is a live site and thus cannot have no search results at all, I have now turned it around:

the live site has the original results in two languages, the staging site has the "solution" implemented and thus no results at all.

**Comment by senlin** [comment]
After sending the email I haven't heard anything anymore. Can't say that I understand the reason for asking for an email then...

**Comment by rayrutjes** [comment]
Sorry about the delay @senlin .
I will get to it as soon as possible.
Please bear with me.

**Comment by senlin** [comment]
issue solved via email support, many thanks for following up!

**Comment by rayrutjes** [comment]
You are welcome, sorry about the delay @senlin .

**Comment by alishanster** [comment]
So what was the solution? 
I am facing exactly the same problem. Would be wonderful if you could share a solution, without having me to do all the emailing back and forth with support staff.
Thank you.

**Comment by senlin** [comment]
@alishanster if you give me an email address I can forward you the instructions, it basically had to do with correctly following all the steps of the instructions found on https://community.algolia.com/wordpress/wpml.html and then if you followed the tutorial, you should be able to hit the `push settings` button on the `Algolia Search -> autocomplete` page next to every index you are using.

**Comment by alishanster** [comment]
Thank you, it worked!
