### ISSUE TITLE
Searching with ',",\ are incorrectly escaped on output

### ISSUE THREAD

**Issue by stevenatwork** [algolia/algoliasearch-wordpress#77]
eg. https://wp.sr-sandbox.com/?instant=1&s=\%22%3E\\\%22%3C#q=\">\\\"<&page=0&refinements=%5B%5D&numerics_refinements=%7B%7D&index_name=%22all%22

`">\"<`

becomes

`\">\\\"<`

**Comment by maxiloc** [comment]
@stevenatwork Can you try on the develop branch and tell me if you manage to reproduce ?

**Comment by stevenatwork** [comment]
It appears to be fixed on the develop branch :+1:
