### ISSUE TITLE
Disable inline JS injected into wp_head

### ISSUE THREAD

**Issue by daanvosdewael** [algolia/algoliasearch-wordpress#771]
### What did you expect to happen?
I would like to disable the inline Javascript that get's injected into the `wp_head`. In my project I'm handling all the `instantsearch.js` frontend manually with Webpack.

This is being added with a filter:

https://github.com/algolia/algoliasearch-wordpress/blob/0e9e3efa8ac80294fdd57196e6ecfc4b0492d067/includes/class-algolia-template-loader.php#L19

Normally I can deregister these kind of hooks with something like this:

```php
remove_filter('wp_head', ['Algolia_Template_Loader', 'load_algolia_config']);
```

### What happened instead?
Deregistering of the inline JS is not working.

### How can we reproduce this behavior?
Adding the `remove_filter` function and checking if the Javascript global variable `algolia` is still being injected in the `<head>`.

Can you provide a link to a page which shows this issue?
No

### Technical info
* WordPress version: 4.9.6
* Algolia Search plugin version: 2.11.1

**Comment by rayrutjes** [comment]
Hello, 
Before addressing the issue itself, I'm curious to know if the single variable introduced by `load_algolia_config` is causing you trouble.

**Comment by daanvosdewael** [comment]
@rayrutjes Not necessarily, it's more a personal preference thing. We are not using Algolia on every page, so only on our search template all the `instantsearch.js` stuff get's loaded. All the config is inside a JS module. It would be a lot cleaner if the global variable `algolia` is not present.

I don't expect that you have to change something on the codebase of the plugin. If I have to take a guess, it's probably a WordPress thing where I'm not using `remove_filter` correctly.

**Comment by rayrutjes** [comment]
You can retrieve the template loader as follow:

```php
$plugin = Algolia_Plugin::get_instance();
$template_loader = $plugin->get_template_loader;
remove_filter('wp_head', [$template_loader, 'load_algolia_config']);
```

You need to make sure this code snippet is called after the plugin is initialized and before the header is rendered.

**Comment by daanvosdewael** [comment]
Ahh yeah, the instance was assigned to a property on the `Algolia_Plugin` class.

Thanks! I got it working with the [wp_loaded](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_loaded) action hook:

```php
add_action('wp_loaded', function () {
  $plugin = Algolia_Plugin::get_instance();
  $template_loader = $plugin->get_template_loader();
  
  remove_filter('wp_head', [$template_loader, 'load_algolia_config']);
});
```

**Comment by rayrutjes** [comment]
Awesome, thanks for having shared back the actual complete solution. I'm sure this will be useful to others.
