### ISSUE TITLE
[WPML] algolia wordpress plugin re-index function doesn't pick up the other language taxonomies

### ISSUE THREAD

**Issue by haog1** [algolia/algoliasearch-wordpress#772]
So currently I'm using wmpl to translate my whole site including custom post types and custom taxonomies.

But I can see that algolia plugin works fine with default and custom post types. 

However every time when I re-index custom taxonomies, it only re-index one kind of language. For example, if I have english and latin so it is either re-indexing all english taxonomies or all latin version taxonomies but not both. So this gives me a trouble that I cannot show custom taxonomies when switching to the other language

I tried the code below but it's just showing my custom taxonomies on both languages webpages.
```
// Add the locale of every post to every record of every post type indexed.
function add_locales_to_records( array $attrs, WP_Post $post ) {
    // Here we make sure we push the post's language data to Algolia.
    $attrs['wpml'] = apply_filters( 'wpml_post_language_details', null,  $post->ID );
    return $attrs;
}

function add_locales_to_terms( array $attrs, WP_Term $term ) {
    // Here we make sure we push the term's language data to Algolia.
    $attrs['wpml'] = apply_filters( 'wpml_post_language_details', null,  $term->term_id );
    return $attrs;
}

add_filter( 'algolia_post_shared_attributes', 'add_locales_to_records', 10, 2 );
add_filter( 'algolia_searchable_post_shared_attributes', 'add_locales_to_records', 10, 2 );
add_filter( 'algolia_term_record', 'add_locales_to_terms', 10, 2 );

```

So does anyone knows how to fix it?

Deep appreciation in advance.

* Algolia Search plugin version:2.11.1

**Comment by rayrutjes** [comment]
Hi,

[This line](https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-posts-index.php#L315) is supposed to ensure no filter on languages is applied.

I don't think we have this for taxonomies.

Could you try manually adding `suppress_filters` to taxonomies?

You need to add it in 2 places, here as well: https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/indices/class-algolia-posts-index.php#L293

**Comment by haog1** [comment]
@rayrutjes 

Thanks for replying.

I might not explain my question clearly. So the issue is no matter which language I switch to in backend, algolia plugin will only upload(re-index) the current language taxonomies. Not like posts, it will upload both languages.

So are you saying that currently this plugin doesn't support taxonomies' wpml?

If so, how would I manually adding `suppress_filters` to support wpml between language switching? Adding some scripts in `get_items()`, and is that what you're trying to say?

Thanks for your patience!

**Comment by rayrutjes** [comment]
@haog1 ,

Correct me if I'm wrong.
You are using WPML and everything works fine for Posts (including for custom post types).

Regarding taxonomies, everything works fine as well except when you are re-indexing all the taxonomies. In that case it only re-indexes the terms of the current language.

If the above statements are correct, then refer to my previous answer.
The `suppress_filters` WP_Query` argument, will remove the WPML language sibling such that it will re-index all languages regardless of the current active one.

**Comment by haog1** [comment]
@rayrutjes 
I think you're correct. But this confuses me more. Since the template already have set `suppress_filters => true`, so can I add `suppress_filter` again?

**Comment by haog1** [comment]
For those who might be interested in, here is the approach how I solved it: 
```
function add_locales_to_terms( array $attrs, WP_Term $term ) {
    $args = array(
        'element_id'  => $term->term_id,
        'element_type' => $term->taxonomy,
    );
    $langCode = apply_filters( 'wpml_element_language_details',  null,  $args);

    if ($langCode->language_code == 'yo') {
        $wpml = array(
            'language_code' => 'yo',
            'locale'        => 'yo_AU',
            'text_direction' => false,
            'display_name'  => 'Yolngu',
            'native_name'  => 'Yolngu',
            'different_language' => get_locale() == 'yo_AU' ? true : false
        );
    } else {
        $wpml = array(
            'language_code' => 'en',
            'locale'        => 'en_US',
            'text_direction' => false,
            'display_name'  => 'English',
            'native_name'  => 'English',
            'different_language' => get_locale() == 'en_US' ? true : false
        );
    }

    $attrs['wpml'] = $wpml;
    return $attrs;
}
```

So basically I created this hook and applied to aloglia's filter hook `algolia_term_{$taxonomy}_record`.  

Also, since wpml has a hook called `wpml_post_language_details`, which is for posts. So there is also a hook for taxonomies: `wpml_element_language_details`, which is just what I used
