### ISSUE TITLE
Check if Algolia PHP API is already present before including it

### ISSUE THREAD

**Issue by nicholasio** [algolia/algoliasearch-wordpress#781]
### What did you expect to happen?
I'd expect this plugin to only try to load the algolia php client if it isn't included already.
### What happened instead?
The plugin includes the algolia php client without checking for its presence, causing a PHP Fatal error if there are other plugin including the library first. In a ideal world all plugins loading the algolia php client should check for its presence before including it. See https://github.com/algolia/algoliasearch-wordpress/blob/master/classmap.php#L8
### How can we reproduce this behavior?
Having two plugins that loads the algolia php client. Even if the other one checks before loading the php client, the order in which the plugins are loaded vary so there's also the chance of getting a PHP Fatal when using this plugin in conjunction with any other plugin or theme that loads the php client.

 I've tried to used this plugin with a custom plugin we built for a client that loads the algolia php client (via composer) and we were unable to because this plugin was loading after ours and hence it was loading the lib twice.

### Technical info
* WordPress version: all
* Algolia Search plugin version: all

**Comment by rayrutjes** [comment]
Hello, thanks for contributing.

Ideally you are right that it would be better to first check if another library exists.
However it is a bit more complex than that as you would also need to check that the versions of the libraries match. 

What we should have done is namespace the library from the beginning to a unique name in this plugin.

It is now too late to move away from the current logic though.

I'm closing this, however feel free to suggest an alternative solution.

**Comment by nicholasio** [comment]
Can we have at least a filter to let other plugin developers disable loading the php client?

**Comment by rayrutjes** [comment]
> Can we have at least a filter to let other plugin developers disable loading the php client?

That sounds like a good idea!
