### ISSUE TITLE
Use is_uploaded_file in /algoliasearch-wordpress-master/AlgoliaPlugin.php

### ISSUE THREAD

**Issue by stevenatwork** [algolia/algoliasearch-wordpress#79]
http://au2.php.net/manual/en/function.is-uploaded-file.php

bool is_uploaded_file ( string $filename )

Around /algoliasearch-wordpress-master/AlgoliaPlugin.php:195

The if statement should contain `is_uploaded_file($_FILES['import']['tmp_name']))` just after `& isset($_FILES['import'])`

**Comment by maxiloc** [comment]
@stevenatwork Can you try on the develop branch and tell me if you manage to reproduce ?

**Comment by stevenatwork** [comment]
I've submitted a PR.

Any idea what the purpose of the str_replace in https://github.com/algolia/algoliasearch-wordpress/blob/develop/AlgoliaPlugin.php#L203 is for?

**Comment by maxiloc** [comment]
If I remember well it's because '\' needs to be escape before being sent so then we need to unescape it.
