### ISSUE TITLE
JavaScript output even if Autocomplete is turned off

### ISSUE THREAD

**Issue by jmagnone** [algolia/algoliasearch-wordpress#793]
The following output is generated even if the Autocomplete option is turned off. Is this strictly required to make Algolia work? We have some issues running this with the Autoptimize plugin for WordPress, generating a new cache file every time the user search for a string. I am under the impression the inline JavaScript is not necessary to be generated in these cases.

https://github.com/algolia/algoliasearch-wordpress/blob/97e1d3e2f77c72d35f12e5298b052c25cd0d7442/includes/class-algolia-template-loader.php#L61

**Comment by rayrutjes** [comment]
Hi @jmagnone ,
Please check out the following issue: https://github.com/algolia/algoliasearch-wordpress/issues/771
