### ISSUE TITLE
Can't add new types to be indexed

### ISSUE THREAD

**Issue by gtenaschuk** [algolia/algoliasearch-wordpress#81]
When i try to add new types to be indexed any of them are replaced by `product`. So it doesn't work and also i can't add more than 1

It is in develop branch

**Comment by SamAnthonyWP** [comment]
I have seen this as well. Went back to the other version.

**Comment by eemi** [comment]
Nico from our team (we are clients of Algolia) created pull request #93 to fix this. It's working fine in the development branch.
