### ISSUE TITLE
Question: Taxonomy Hierarchy

### ISSUE THREAD

**Issue by rentageekmom** [algolia/algoliasearch-wordpress#85]
More of a question than an issue. 

Any thoughts on the best way to either 1) limit the taxonomy filter attributes to the parents only or 2) show the hierarchy in the display?

Not familiar with hogan.js and trying to catch up here to determine how to customize for it; I'd guess an option to show the taxonomy hierarchy would be useful to others as a future update as well.

**Comment by maxiloc** [comment]
Hierarchy would be a bit complicated to implement.
To limit the number of taxonomies I would go for modifying the indexing part to fit your needs => https://github.com/algolia/algoliasearch-wordpress/blob/develop/core/WordpressFetcher.php#L222

**Comment by rayrutjes** [comment]
Hi @rentageekmom , not sure this issues still applies to the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please open a new issue.
