### ISSUE TITLE
Geo-Search based on IP -- Distance to location displays in meters (change to miles?)

### ISSUE THREAD

**Issue by SamAnthonyWP** [algolia/algoliasearch-wordpress#86]
Hey All,

I feel like this should be simple, but I have spent hours trying to convert the distance from the user's IP address to the location item in my algolia search from meters to miles with no luck. Is this even possible with this implementation of Algolia? I think the issue is that this one is php based and the distance data comes in too late to be changed with php.

Any insight would be hugely appreciated. Thanks in advance!

**Comment by SamAnthonyWP** [comment]
for reference: [link to search](http://lyfekitchen.wpengine.com/?instant=1&s=#q=&page=0&refinements=%5B%5D&numerics_refinements=%7B%7D&index_name=%22lyfe_all%22)

**Comment by maxiloc** [comment]
I am not sure to understand the issue. Do you have a small snippet of code ?

**Comment by SamAnthonyWP** [comment]
Hey @maxiloc  -- so I have done some serious reading since posting this and think I have a better understanding of how this all works. Please note that I am not using the develop version. Here are some snippets:

I added these lines to my template.js file:
```javascript
helper.setQueryParameter('getRankingInfo', true);
helper.setQueryParameter('aroundLatLngViaIP', true).search();
```
Which has allowed me to utilize distance to a location (all items in my index are restaurant locations) as a ranking factor, as well as display the one's current distance to each location. Here is the snippet from my templates.php file that shows the variable -- {{{ _rankingInfo.matchedGeoLocation.distance }}} -- for displaying the distance to a location:
```html
<div class="result_details"><h1 class="result-title">
                            <a href="{{permalink}}">
                                {{{ _highlightResult.title.value }}}
                            </a>
                        </h1>
                        <h6 class="lyfe_state"><span>{{{ _highlightResult.lyfe_state.value }}}</span> &nbsp; <a href="{{lyfe_directionslink}}" rel="nofollow" target="_blank">Get Directions >></a></h6>
                        <p class="lyfe_address">{{lyfe_address_1}}<br>{{lyfe_address_2}}<br><span id="distance">{{{ _rankingInfo.matchedGeoLocation.distance }}}</span> meters</p>
                        <p class="lyfe_hours">{{lyfe_hours}}<br>{{lyfe_phone}}<br>{{lyfe_emailaddress}}</p>
                        <p class="ordernow_link"><a class="tk-bebas-neue" href="{{lyfe_ordernowurl}}" rel="nofollow" target="_blank">Order Now</a></p>
                        <p class="menu_link"><a class="tk-bebas-neue" href="{{permalink}}" rel="nofollow" target="_blank">Menu</a></p>
                        <p class="catering_link"><a class="tk-bebas-neue" href="{{permalink}}catering/">Catering Menu</a></p>
                        </div>
```
This is working as I believe it is supposed to, however the {{{ _rankingInfo.matchedGeoLocation.distance }}} variable displays the distance to the location in meters.

So my question is: how can I get the distance and display it in miles?

Hopefully this helps. I really appreciate your time.

**Comment by maxiloc** [comment]
You should probably do the conversion directly on the javascript part before displaying it in the template.js file

**Comment by SamAnthonyWP** [comment]
Hi @maxiloc -- I am a noob with js. Any tips on how/where to do that?

**Comment by maxiloc** [comment]
Is it for instantsearch or autocomplete ?

**Comment by SamAnthonyWP** [comment]
instantsearch

**Comment by maxiloc** [comment]
I guess you should do it in this function => https://github.com/algolia/algoliasearch-wordpress/blob/develop/lib/helper.js#L30

It will modify every hits

**Comment by SamAnthonyWP** [comment]
Can you give me a snippet to add in that would modify the distance and make it in miles?

**Comment by maxiloc** [comment]
Something like
```
_rankingInfo.matchedGeoLocation.distance = _rankingInfo.matchedGeoLocation.distance *0.000621371192
```

**Comment by SamAnthonyWP** [comment]
Just to clarify -- you saw that I mentioned I am not using develop branch. Does this change things?

**Comment by maxiloc** [comment]
So it will be more here => https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/woo/template.js#L237
and replacing "_rankingInfo.matchedGeoLocation.distance" by "content.hits[l]._rankingInfo.matchedGeoLocation.distance"

**Comment by SamAnthonyWP** [comment]
so:
    content.hits[l]._rankingInfo.matchedGeoLocation.distance = content.hits[l]._rankingInfo.matchedGeoLocation.distance *0.000621371192

**Comment by maxiloc** [comment]
yes should be ok

**Comment by SamAnthonyWP** [comment]
still seeing the exact same output in meters.

**Comment by SamAnthonyWP** [comment]
Got it to work. Just had to move it up a couple lines in the code to get it out of that if-statement.

**Comment by SamAnthonyWP** [comment]
thank you so much.
