### ISSUE TITLE
Results page is empty, produces JS error

### ISSUE THREAD

**Issue by fschroiff** [algolia/algoliasearch-wordpress#89]
A search input gets rendered, and the word "refine", that's it. 
This is the error I am seeing: `TypeError: undefined is not an object (evaluating 't.getConfiguration')`

**Comment by kazkovsky** [comment]
+1

**Comment by warrenseine** [comment]
Same problem here.

Looking at the repository, I can only find a reference to `getConfiguration` in `algoliaBundle.min.js`. Is this proprietary code?

**Comment by warrenseine** [comment]
Building the bundle from its [repository](https://github.com/algolia/algoliasearch-extensions-bundle) raised another error: `Uncaught TypeError: algoliaBundle.instantsearch.widgets.indexSelector is not a function` from `template.js?ver=4.5.2:122`.

**Comment by warrenseine** [comment]
I've managed to update the code in `template.js` to match API changes (`facetName` became `attributeName` apparently) and don't have any error anymore, but the result page displays results as JSON, not formatted to HTML.

**Comment by che2on** [comment]
Facing same issue. Not able to see search results... just shows "Refine"... only autocomplete template works, but not static search page

**Comment by rayrutjes** [comment]
Not sure this issue still applies to the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

In the new version of the plugin, instantsearch.js based search experiences are left to the developer. However here is a gist that should  get you started quickly: https://gist.github.com/rayrutjes/0814a08ec0ad78e370299b572840405b
We are still trying to find out ways to ease the process of implementating instantsearch experiences, so if you have any suggestion, please share!

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please open a new issue.
