### ISSUE TITLE
Drag and drop does not work on Dashboard pages

### ISSUE THREAD

**Issue by fschroiff** [algolia/algoliasearch-wordpress#91]
For example reordering pages and posts under "enabled sections". I get this error: `angular.min.js:108:330 Error: algoliaBundle.$(element).sortable is not a function. (In 'algoliaBundle.$(element).sortable', 'algoliaBundle.$(element).sortable' is undefined)`

**Comment by redox** [comment]
Thank you for all the bug reports @fschroiff :+1:  The development of the extension is currently staled but we'll start again in a few weeks. The current state is definitely BETA :bug:

**Comment by fschroiff** [comment]
@redox so I should keep going? ;)

**Comment by redox** [comment]
> @redox so I should keep going? ;)

Oh yeah :+1: Just don't worry if we don't take care of them in the next few days :tired_face:

**Comment by rayrutjes** [comment]
Hi again @fschroiff, we don't use drag & drop features in the admin UI in the latest release of the plugin (0.2.5).

I'm closing this issue, but feel free to open new ones!
