### ISSUE TITLE
Custom WP_Query gets overridden on results page

### ISSUE THREAD

**Issue by fschroiff** [algolia/algoliasearch-wordpress#92]
A simple WP_Query-loop that returns three posts comes up empty on the search results page with Algolia plugin enabled. Displays fine without Algolia plugin.

**Comment by rayrutjes** [comment]
Hi again @fschroiff, the latest release (0.2.5) is shipped with an "override native search" feature that will make the autocomplete feature play nicely with the search operating in backend.

You can read more about it here https://community.algolia.com/wordpress/configuration.html#native-search

I'm closing this for now, but I'd gladly read your feedback.

Please re-open an issue if you still have some input on this feature.
