### ISSUE TITLE
Index question

### ISSUE THREAD

**Issue by jzhangCat** [algolia/algoliasearch-wordpress#94]
Can users be indexed automatically via the plugin?

**Comment by rayrutjes** [comment]
@jzhangCat Sorry for the very late reply.

You will be able to index users in the next release that will come out in approximately a month.

**Comment by rayrutjes** [comment]
Hi @jzhangCat, users can now be indexed in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
