### ISSUE TITLE
"Notice: Array to string conversion" on reindex

### ISSUE THREAD

**Issue by mattrepublic** [algolia/algoliasearch-wordpress#97]
Hi Algolia, 

On first reindex (new VVV setup, but existing index and db) I'm getting this error repeated a couple dozen times. Plugin installed today from develop branch. WP version 4.5.2.

[OK]	
Notice: Array to string conversion in /htdocs/wp-content/plugins/algoliasearch-wordpress-develop/core/WordpressFetcher.php on line 198

Notice: Undefined property: stdClass::$Array in /htdocs/wp-content/plugins/algoliasearch-wordpress-develop/core/WordpressFetcher.php on line 198

Any thoughts on what could be causing this?

<img width="1130" alt="screen shot 2016-06-08 at 2 57 43 pm" src="https://cloud.githubusercontent.com/assets/645847/15907050/7cabc19a-2d89-11e6-9f80-592fe66ba41b.png">

**Comment by mattrepublic** [comment]
As an afterthought, does this plugin play nice with Advanced Custom Fields? ACF stores a lot of stuff under key[0] for some reason...

**Comment by rayrutjes** [comment]
Hi @mattrepublic,

We released a brand new version of the plugin, 0.2.5 at the time of writing this.

Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also added a dedicated section related to Advanced Custom Search integration which you can access here: https://community.algolia.com/wordpress/advanced-custom-fields.html

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
